### ISSUE TITLE
Problem: incorrect base fee used during tracing, that effects `tx.gasPrice` value during contract execution

### ISSUE THREAD

**Issue by VictorTrustyDev** [crypto-org-chain/cronos#1118]
**Describe the bug**
Base fee (feemarket) is calculated every BeginBlock and used to adjust gas price of Ethereum Tx messages of the same block.
(block height = N, start context = N-1, base fee for N, gas price = gas price + base fee of N)

When `debug_traceTx/Block`, at starting, context state is minus by one so actual base fee used in the tracing context is from previous block, not the same block and that effects `gasPrice` of the tx thus effect values of `tx.gasPrice` during contract execution.
(block height = N, start context = N-1, base fee of N - 1, gas price = gas price + base fee of N - 1)

**Comment by mmsqe** [comment]
Not sure which version you tried, but do you mean this [test](https://github.com/crypto-org-chain/ethermint/blob/v0.20.11-cronos/tests/integration_tests/test_fee_history.py#L132) doesn't cover it?

**Comment by VictorTrustyDev** [comment]
No I didn't try any. This is a bug in Evmos so I paste it here for you guys aware it.

**Comment by VictorTrustyDev** [comment]
https://github.com/crypto-org-chain/ethermint/blob/develop/x/evm/keeper/config.go#L41

You will get base fee of `N-1` by this. And it should be `N`

**Comment by yihuang** [comment]
I think the bug description makes sense, because we don't run begin blockers in trace api
