### ISSUE TITLE
Problem: Panic when calculating base fee for legacy block

### ISSUE THREAD

**Issue by VictorTrustyDev** [crypto-org-chain/cronos#1120]
https://github.com/crypto-org-chain/ethermint/blob/8ebf0e8b5d9c477804d4dbadad06ba56991c3d23/x/feemarket/keeper/eip1559.go#L104

MinGasPrice can be nil on legacy blocks thus this method will panic during tracing on legacy blocks.

Suggestion change: [view this single commit](https://github.com/VictorTrustyDev/fork-evmos/pull/2/commits/c4d0f1e09ebabe28ac901b4e16d439084d901f52)

**Comment by mmsqe** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/1444
