### ISSUE TITLE
 genesis.json: failed to unmarshal feeibc genesis state: EOF

### ISSUE THREAD

**Issue by alpha-omega-labs** [crypto-org-chain/cronos#1122]
Hello,
We are forking cronos to be new GenesisL1 codebase (migrating from old ethermint) and experiencing issue during genesis.json validation:

 genesis.json: failed to unmarshal feeibc genesis state: EOF

genesis.json was successfully migrated via "migrate" command of cronosd. And this issue appears. 
Can you please provide heads up on how to solve it and where is potential bug?
https://github.com/cosmos/cosmos-sdk/issues/17198

Thank you!

**Comment by mmsqe** [comment]
Not sure how you operate, but export works fine after [migrate](https://github.com/crypto-org-chain/cronos/compare/v1.0.9...mmsqe:v1.0.9_feeibc).

**Comment by alpha-omega-labs** [comment]
Yes, but we are looking at import/ genesis.json state initialization bug - not export with cronosd.

1. Export state from other chain sdk v 0.44
2. Migrate state to v0.46 with cronosd
3. Validate genesis.json with cronosd, got error:
genesis.json: failed to unmarshal feeibc genesis state: EOF

**Comment by alpha-omega-labs** [comment]
You mean your custom module or our custom module? Because we don't have any custom module :)
We just want to use up-to date open source ethermint software for managing our general blockchain with specific data. Our state is a state of first evmos version (by modules structure). And we will be glad to gain some new modules implemented by cronos during time.

**Comment by mmsqe** [comment]
> You mean your custom module or our custom module? Because we don't have any custom module :)

since sdk only migrate gov and staking in v43 and v46, we need custom handle for feeibc, evm, cronos related migrate in different versions
