### ISSUE TITLE
Problem: VersionDB memStore not updating

### ISSUE THREAD

**Issue by GAtom22** [crypto-org-chain/cronos#1226]
**Describe the bug**
While writing some tests for a node with versionDB identified a bug with the store keys. In particular, there seems to be an issue with the memStore related to the 'capability' module. 

The testing scenario that fails is performing an IBC transfer via a precompiled contract (e.i, ethereum tx). When performing the IBC transfer via cosmos msg, works alright.

The test fail when calling the [GetCapability](https://github.com/cosmos/cosmos-sdk/blob/3b509c187e1643757f5ef8a0b5ae3decca0c7719/x/capability/keeper/keeper.go#L369) on the sendTransfer function. What I see is that the memStore root is nil, so it does not find the key (see image below)
![Screenshot from 2023-10-23 15-57-25](https://github.com/crypto-org-chain/cronos/assets/54514587/c498d229-5af3-44e4-9bf3-236f4d9a20d1)

Without version DB, the tests pass successfully. In this case, the memStore root has some entries:
![Screenshot from 2023-10-23 16-01-55](https://github.com/crypto-org-chain/cronos/assets/54514587/4a55fecc-3462-4a51-9305-fbc76f1c38d2)

The reason is that the memStore is not updated in the qms. A workaround is adding the memKeys to the store & the streaming service. But I guess a better solution would be to have a mechanism to update the memStore.

**To Reproduce**
in case you want to look closer into this test case, [here's the PR with the changes](https://github.com/evmos/evmos/pull/1911). The test is the test_precompiles.py

**Expected behavior**
memStore should have entries

**Comment by yihuang** [comment]
Yeah, we see that too, investigating.

**Comment by yihuang** [comment]
yeah, you are right, the qms create it's own mem store instance, I try to make it share the same mem store instance as the main cms.
