### ISSUE TITLE
Problem: versionDB migration does not support pebbleDB

### ISSUE THREAD

**Issue by GAtom22** [crypto-org-chain/cronos#1236]
**Describe the bug**
At the moment, versionDB migration procedure does not support pebbleDB

```
~ $ evmosd changeset dump "/home/evmos/.evmosd/data_rocks" --home "/home/evmos/.evmosd/" --log_level "debug"
Error: unknown db_backend pebbledb, expected one of goleveldb,memdb,rocksdb
```

Would be great to add support for this DB

**To Reproduce**
1. Start a node with pebbleDB.
  Usually this requires to replace the cometbft-db module
  ```
  go mod edit -replace github.com/cometbft/cometbft-db=github.com/notional-labs/cometbft-db@pebble
  go mod tidy
  COSMOS_BUILD_OPTIONS=pebbledb make build
  ```
2. Run a node with this config and store some data
3. Perform the migration procedure to versionDB

**Comment by yihuang** [comment]
I think the dump cmd use the `cometbft-db` db opener as usual, maybe sth wrong with the cometbft-db replacement?

**Comment by GAtom22** [comment]
will look into this, thanks!

**Comment by GAtom22** [comment]
Closing because this issue is not related to versionDB, but related to the `cometbft-db` dependency
