### ISSUE TITLE
Feature: bump cosmos-sdk version to v0.50 in VersionDB

### ISSUE THREAD

**Issue by GAtom22** [crypto-org-chain/cronos#1257]
**Is your feature request related to a problem? Please describe.**
Currently, versionDB is using cosmos-sdk v0.47. This will not be compatible with a cosmos chain that uses sdk v0.50

**Describe the solution you'd like**
Would be great to have a new version of VersionDB with cosmos-sdk v0.50.
This will be required for any cosmos chain that is using the v0.50 sdk version.

**Describe alternatives you've considered**
Create new tag with the bump

**Comment by yihuang** [comment]
we'll try sdk 0.50 ASAP, after the 0.47 upgrade.

**Comment by mmsqe** [comment]
closing in favour of https://github.com/crypto-org-chain/cronos/pull/1377
