### ISSUE TITLE
Question: why `x/authz` was removed

### ISSUE THREAD

**Issue by VictorTrustyDev** [crypto-org-chain/cronos#1289]
Ref: #1274

I have looked at some PR relates to x/authz but I still don't understand why it is risky?

With my knowledge, it can be used to grant permission to re-stake, that's so convenient.

Could you please share me more details?

Thanks

**Comment by yihuang** [comment]
there were a security report that authz can be used to execute messages directly bypassing the ante handlers, so we've already disabled it in mempool level in `v1.0.x`.
And right now Cronos is PoA, so there seems no usage for authz.
But technically, we can add back authz in a safe way, just maintain a black list of messages that are not allowed to be executed with authz, but we need to be careful that we don't miss one.

**Comment by VictorTrustyDev** [comment]
I got it, @yihuang thank you
