### ISSUE TITLE
Not able to download archive versiondb snapshot

### ISSUE THREAD

**Issue by tmeinlschmidt** [crypto-org-chain/cronos#1312]
Not able to download archive snapshot, getting bunch of 403 (not sure why's that) and it's repeatedly breaking

downloading with aria2c (for resuming), getting
```
02/08 21:30:08 [ERROR] CUID#17 - Download aborted. URI=https://snapshot.cronos.org/cronos/mainnet-snapshot/cronosmainnet_25-1-versiondb-archive-latest.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=22 URI=https://snapshot.cronos.org/cronos/mainnet-snapshot/cronosmainnet_25-1-versiondb-archive-latest.tar.lz4
  -> [HttpSkipResponseCommand.cc:239] errorCode=22 The response status is not successful. status=403
```

tried from both Europe and US regions.

**Comment by ivanslwong-crypto-com** [comment]
Hi @tmeinlschmidt , would you be able to use curl to download the snapshot from your instances? 

`curl -LOJ https://snapshot.cronos.org/cronos/mainnet-snapshot/cronosmainnet_25-1-versiondb-archive-latest.tar.lz4`

**Comment by mmsqe** [comment]
free to ping us if this issue still exist
