### ISSUE TITLE
Enhance visibility of blacklist hash logging at startup for production nodes

### ISSUE THREAD

**Issue by Perseverance42** [crypto-org-chain/cronos#1333]
The addition of logging for blacklisted addresses (referenced in #1328) currently employs the `info` log level. Given that production nodes predominantly operate at the `warn` level, operators are compelled to adjust the log level to facilitate the cross-verification of blacklist hashes with peers. This adjustment necessitates node restarts, introducing avoidable restarts in production environments.

Considering that this logging activity is confined to node startup, elevating these log messages to a higher severity would significantly enhance operational efficiency by obviating the need for manual log level modifications and subsequent restarts.

**Comment by Perseverance42** [comment]
Considering the straightforward nature of the proposed code changes, I believe this issue would serve as an excellent opportunity for me to familiarize myself with the project's contribution process. It appears to be a manageable task that still encompasses all the necessary steps required for contributing. I'm eager to take this on as my first contribution. May I proceed?

**Comment by yihuang** [comment]
> Considering the straightforward nature of the proposed code changes, I believe this issue would serve as an excellent opportunity for me to familiarize myself with the project's contribution process. It appears to be a manageable task that still encompasses all the necessary steps required for contributing. I'm eager to take this on as my first contribution. May I proceed?

sure, PR is welcome.

**Comment by mmsqe** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/1334
