### ISSUE TITLE
Feedback on latest release

### ISSUE THREAD

**Issue by kaber2** [crypto-org-chain/cronos#1365]
I thought you might appreciate some feedback from your latest release. First of all, performance has improved a lot, the RPC streams API pays of and RPC latencies have gone done a lot, and foremost of all, I'm very happy about the support of the tracing API.  Thanks guys, good job.

Two things for the wishlist: backfilling data is rather slow, in my local fork I'm using a LRU cache for blocks received through internal RPC, which speeds up things 10x, also while not strictly necessary for Cronos, the accesslist API is useful for analyzing smart contract behaviour and should be easy to support.

Cheers!

**Comment by yihuang** [comment]
Thanks for your feedback.

> the RPC streams API pays of

Do you mean the subscribe/filter APIs and the code refactors we released?

> backfilling data

What do you mean by this?
