### ISSUE TITLE
Ambiguous release schedule

### ISSUE THREAD

**Issue by Undead8** [crypto-org-chain/cronos#1369]
When new versions are released, it is not clear as to when they take effect or when the new binary should be used. For instance, the latest release v1.2.0-rc0 has no indication as to when it takes effect (block height, timestamp?) or if production nodes should upgrade right now or at a later version.

Could you please mention in all the release notes when nodes used in production environment should upgrade to the new binary?

**Comment by yihuang** [comment]
The general rules are like this:
- The third part of the version number means a non-breaking version, which user can upgrade anytime.
- The first and second part means a consensus breaking version, which we need a coordinated upgrade, user should pay attention to the govenance proposal for the upgrade schedule.
- rc versions means it's being tested internally or on testnet, not ready for mainnet use, after test finish, we'll make another formal release.

**Comment by Undead8** [comment]
May I suggest that for breaking release, the release note include a link to the specific governance proposal that shows the upgrade schedule? I operate non-validating nodes and I don't necessarily follow governance updates. I'm most likely not alone :)

**Comment by yihuang** [comment]
> May I suggest that for breaking release, the release note include a link to the specific governance proposal that shows the upgrade schedule? I operate non-validating nodes and I don't necessarily follow governance updates. I'm most likely not alone :)

the proposal can only be submitted after the binary is released, but we can try to update the release notes with the upgrade schedule.

**Comment by kaber2** [comment]
So can we expect an update in the release announcement for 1.3.0?

**Comment by yihuang** [comment]
> So can we expect an update in the release announcement for 1.3.0?

there's a upgrade proposal posted in discussions: https://github.com/crypto-org-chain/cronos/discussions/1505, I just added the link to the release notes.

**Comment by kaber2** [comment]
Thank you!
