### ISSUE TITLE
- Fixed a minor bug that incorrectly printed the wrong status message to the user during remote verification.

### ISSUE THREAD

**Issue by tuttheking81** [crypto-org-chain/cronos#1426]
- Fixed a minor bug that incorrectly printed the wrong status message to the user during remote verification.

_Originally posted by @swaroop-osec in https://github.com/Ellipsis-Labs/solana-verifiable-build/pull/53_

**Comment by Nasiru15** [comment]
018225

**Comment by Nasiru15** [comment]
wc:47271a3039290c36e40df62275f263b3dff9945f6e7fc760ed61621b745fca8d@2?expiryTimestamp=1727743554&relay-protocol=irn&symKey=64b1f6e676150739152b4e65a54dc916dd45b3bb9cdcdbfd584f440190cdd331
