### ISSUE TITLE
Thanks for the add!

### ISSUE THREAD

**Issue by tuttheking81** [crypto-org-chain/cronos#1427]
Thanks for the add!

_Originally posted by @joeymeere in https://github.com/StockpileLabs/awesome-solana-oss/pull/9#issuecomment-2040272683_

_Originally posted by @MANAALHARBI in https://github.com/Ellipsis-Labs/solana-verifiable-build/issues/60_

**Comment by MANAALHARBI** [comment]
> Thanks for the add!
> 
> _Originally posted by @joeymeere in https://github.com/StockpileLabs/awesome-solana-oss/pull/9#issuecomment-2040272683_
> 
> _Originally posted by @MANAALHARBI in https://github.com/Ellipsis-Labs/solana-verifiable-build/issues/60_
