### ISSUE TITLE
Problem: missing decision record for a custom fork of ibc-go

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/cronos#146]
currently, ibc-go is replaced by a custom fork:
https://github.com/crypto-org-chain/cronos/blob/ce17b4ef3e6e11ddfcced29daec9d550ccc68d8c/go.mod#L35
based on 1.0.1

Besides the fact that 1.0.1 was discontinued: https://github.com/cosmos/ibc-go/releases/tag/v1.0.1 the decision of using a custom fork is undocumented (related: https://github.com/crypto-org-chain/cronos/issues/64 ) and changes related to the custom fork changes (e.g. https://github.com/crypto-org-chain/cronos/commit/81c72107339876c9de53f5e6c644e51bf51a9bb4) don't describe the solutions to the problems related to the custom fork. It is also unclear what the implications of the custom fork usage are: will there be a need to maintain the custom ibc-go fork forever? If not, how is the transition to the official upstream version going to happen -- e.g. how will it behave with regards to the ibc versioning: https://github.com/cosmos/ibc-go/blob/29d44551292309a97f63267e698357e27c86f023/docs/migrations/ibc-migration-v100.md#ibc-apps (will the custom fork signal "v1" transfer app and it's oblivious to the counterparty? if the later upstream version negotiates down to v1 with the counterparty chain, will it be a problem? etc.) ?

**Comment by yihuang** [comment]
https://github.com/cosmos/ibc-go/pull/348

Should we push the change to upstream?

**Comment by thomas-nguy** [comment]
This PR is a very simple implementation which is redundant with the ICS30 middleware implementation.

The plan is to replace this version with a ibc-go version with middleware support (probably v2.x.x)

The current fork is v1.0.1 with a single commit which add the custom code needed for the hook
https://github.com/crypto-org-chain/ibc-go/commits/v1.0.1-hooks

We can probably bump it to v1.2.1 and cherry pick this commit for the mainet binary

**Comment by tomtau** [comment]
> The plan is to replace this version with a ibc-go version with middleware support (probably in v2.x.x)

but would that cause any issues with regards to version negotiating: e.g. if the v2 ibc-go negotiated to use v1 with the counter-party, would it turn off the middleware capability?

**Comment by thomas-nguy** [comment]
yeah possibly, except if the middleware also support v1 (not quite sure about the current implementation)

I think what is the most important currently is the compatibility with crypto.org chain. It is not clear if we want to open Cronos to other cosmos chains to have a free flow IBC->CRC20 (which does not work currently because of the token-mapping restriction) or just allows the CRC20 wrapping to be done on IBC tokens issued from crypto.org chain.

IBC logic will remains the same overall for tokens that are not "whitelisted"

**Comment by tomtau** [comment]
> It is not clear if we want to open Cronos to other cosmos chains 

I recall @CeruleanAtMonaco mentioned this was desirable -- e.g. to have UST usable in EVM.
but there's no need to have some extra complexity because of that, such as maintaining an ibc-go fork -- so if the other native tokens can be exposed to EVM via manual actions, as described in wrapping: https://github.com/tharsis/ethermint/discussions/392 it's good enough. That's potentially something good to link/mention in the decision record as well.
