### ISSUE TITLE
Unable to start mainnet node with quicksync snapshots

### ISSUE THREAD

**Issue by mookmookoolala** [crypto-org-chain/cronos#1514]
Hi team, Im trying to setup a mainnet full node  and decided to use the snapshot from quicksync.

I downloaded the snapshot for levelsdb from quicksync however after replacing data directory and restarting the service, i get this error.

> failed to load latest version: version of store authz mismatch root store's version; expected 14790217 got 0

**Comment by mmsqe** [comment]
@mookmookoolala can you try sync from [v1.2.0](https://quicksync.io/networks/cronos.html) since authz get removed since [v1.1.0-rc2](https://github.com/crypto-org-chain/cronos/releases/tag/v1.1.0-rc2)

**Comment by mookmookoolala** [comment]
Alright seem to solve the issues! Thanks
