### ISSUE TITLE
E2EE: missing amino codec for sign with Ledger hadware wallet

### ISSUE THREAD

**Issue by Galadrin** [crypto-org-chain/cronos#1543]
Validators with Ledger will not be able to sign E2EE module transaction,
the amino codec is empty

https://github.com/crypto-org-chain/cronos/blob/867d53c281f2ca535ae1276dc203804607148af0/x/e2ee/types/codec.go#L12

**Comment by yihuang** [comment]
it's not supported in 1.3, will be supported 1.4, it takes a breaking upgrade to fix the 1.3, so maybe we'll just wait for 1.4.
