### ISSUE TITLE
Cronos testnet unable to sync

### ISSUE THREAD

**Issue by mookmookoolala** [crypto-org-chain/cronos#1565]
Im currently stuck at blockheight of 14046800, however when i upgrade to cronos 1.3.0, i get this error. If i do not upgrade they will just get stuck at that height saying no peer found of peer disconnected straight away.

Sep 02 09:24:08 test systemd[1]: Started cronosd.
Sep 02 09:24:08 test cronosd[3493321]: 9:24AM INF Unlocking keyring module=server
Sep 02 09:24:08 test cronosd[3493321]: 9:24AM INF starting ABCI with Tendermint module=server
Sep 02 09:24:08 test cronosd[3493321]: 9:24AM ERR Setting ante handler without blacklist module=server
Sep 02 09:24:09 test cronosd[3493321]: failed to load latest version: version of store e2ee mismatch root store's version; expected 14046800 got 0; new stores should be added using StoreUpgrades

**Comment by mookmookoolala** [comment]
6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:38:59 test cronosd[3494025]: 9:38AM INF Reconnecting to peer addr=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 module=p2p server=node
Sep 02 09:38:59 test cronosd[3494025]: 9:38AM ERR error while stopping peer error="already stopped" module=p2p server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF service start impl="Peer{MConn{35.206.109.1:26656} b8e6d6e16d236fa6a7101316d96de718200c500c out}" module=p2p msg="Starting Peer service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF service start impl=MConn{35.206.109.1:26656} module=p2p msg="Starting MConnection service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF invalid peer blockHeight=14046862 module=blockchain peer=b8e6d6e16d236fa6a7101316d96de718200c500c server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM ERR Stopping peer for error err="error with peer b8e6d6e16d236fa6a7101316d96de718200c500c: invalid peer" module=p2p peer="Peer{MConn{35.206.109.1:26656} b8e6d6e16d236fa6a7101316d96de718200c500c out}" server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF service stop impl="Peer{MConn{35.206.109.1:26656} b8e6d6e16d236fa6a7101316d96de718200c500c out}" module=p2p msg="Stopping Peer service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF service stop impl=MConn{35.206.109.1:26656} module=p2p msg="Stopping MConnection service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:39:00 test cronosd[3494025]: 9:39AM INF Reconnecting to peer addr=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 module=p2p server=node
Sep 02 09:39:01 test cronosd[3494025]: 9:39AM INF service start impl="Peer{MConn{35.206.109.1:26656} b8e6d6e16d236fa6a7101316d96de718200c500c out}" module=p2p msg="Starting Peer service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node
Sep 02 09:39:01 test cronosd[3494025]: 9:39AM INF service start impl=MConn{35.206.109.1:26656} module=p2p msg="Starting MConnection service" peer=b8e6d6e16d236fa6a7101316d96de718200c500c@35.206.109.1:26656 server=node

**Comment by yihuang** [comment]
> failed to load latest version: version of store e2ee mismatch root store's version; expected 14046800 got 0; new stores should be added using StoreUpgrades

this error says you switched binary too early

**Comment by mookmookoolala** [comment]
i will resync it from scratch, for testnet wise, I do not see any guide other than 1.0.2 being the final upgrade needed after height 6969900

**Comment by yihuang** [comment]
there's one explanation for the p2p issue, there might be something happened that makes your node blacklisted by other nodes for a while, in that case, you need to wait for a while, or reset the node id.
