### ISSUE TITLE
Probelm: missing integration test of cronos transfer-tokens (cronos → chainmain)

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/cronos#182]
1. send amount chainmain -> cronos_777
2. cronosd tx cronos transfer-tokens  ...
3. check amount is re-claimed back in chainmain successfully.

**Comment by leejw51crypto** [comment]
## convert-token is a cronos message type
it does 
- convert basetcro to ibc tokens and multiply by 10^10
- wire with IBC and transfer directly ibc tokens to chainmain

**Comment by yihuang** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/367.
