### ISSUE TITLE
Problem: missing ADR draft for a transition to CCV

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/cronos#194]
Cronos to be a child chain.

https://github.com/cosmos/interchain-security
https://github.com/cosmos/ibc-go/pull/116 
https://github.com/informalsystems/cross-chain-validation/pull/26/files

**Comment by tomtau** [comment]
one potential alternative to explore: https://github.com/celestiaorg/optimint
https://docs.google.com/document/d/12gZow_JTJjRrmaD2mNTmYniLhyxVLSyDd7Fbxo5UnA8/edit?usp=sharing

Having the crypto.org chain mainnet or other network as the data availability layer

**Comment by thomas-nguy** [comment]
while https://github.com/crypto-org-chain/cronos/commit/5a4dd00732fc8a6a30c45cbfe9a10fe8ce5e7765 gravity bridge as a child chain proposal was rejected, I think cronos as a child chain of crypto.org could still be a consideration
