### ISSUE TITLE
Problem: hermes is not supported on 'x86_64-darwin'

### ISSUE THREAD

**Issue by damoncro** [crypto-org-chain/cronos#198]
**Describe the bug**

After pulling the commit 9c3ba89b259f6da54a2c9f6096c8f0dd496efdc4, then
run `nix-shell integration_tests/shell.nix`, it prints out the following error:
```
error: Package ‘hermes’ in /Users/damonchen/Documents/cronos/nix/hermes.nix:4 is not supported on ‘x86_64-darwin’, refusing to evaluate.

a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
   for a single invocation of the nix tools.

     $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

b) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.

(use '--show-trace' to show detailed location information)

```

As it states, run `export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1` can temporarily avoid it.

**Desktop (please complete the following information):**
 - OS: macOS Big Sur
 - Version 11.6.1

**Comment by leejw51crypto** [comment]
for this issue,
how about updating document ?

**Comment by damoncro** [comment]
The test_ibc failed in mac, how about skip the tests in mac?

```
@pytest.mark.skipif(os.name == 'posix', reason="do not run on mac os")

```

**Comment by yihuang** [comment]
> The test_ibc failed in mac, how about skip the tests in mac?
> 
> ```
> @pytest.mark.skipif(os.name == 'posix', reason="do not run on mac os")
> ```

I think it's not supposed to fail?

**Comment by damoncro** [comment]
It is failed because error: Package ‘hermes’ in /Users/damonchen/Documents/cronos/nix/hermes.nix:4 is not supported on ‘x86_64-darwin’.

**Comment by yihuang** [comment]
> It failed because error: Package ‘hermes’ in /Users/damonchen/Documents/cronos/nix/hermes.nix:4 is not supported on ‘x86_64-darwin’.
> 
> https://github.com/crypto-org-chain/cronos/blob/main/nix/hermes.nix#L17

Update it like this: https://github.com/crypto-org-chain/chain-main/blob/master/nix/default.nix#L15
There's no problem building it on mac.
