### ISSUE TITLE
The version number in default.nix is hardcoded as 0.5.5 which is confusing

### ISSUE THREAD

**Issue by damoncro** [crypto-org-chain/cronos#199]
**Describe the bug**
The version number in default.nix is hardcoded as **0.5.5** which is confusing. User may think that we always use **0.5.5** to do testing.

Because in nix-shell environment, it always use the latest source code to test. Version number here is just a place holder or for displaying (Clarify me if it has other meanings).

**Expected behavior**
Change **0.5.5** to other text?

**Comment by yihuang** [comment]
maybe sth like `dev`?
