### ISSUE TITLE
./cronosd start : error during handshake: error on replay: wrong Block.Header.AppHash

### ISSUE THREAD

**Issue by dytfght** [crypto-org-chain/cronos#200]
**Describe the bug**
./cronosd start

11:16PM ERR failed init node error="error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 702DC60359362E3D03038E2C58EB6BC176574474848B3C7C2F93EE0B5B45069B, got 61BAA08C8C960B8873DAD2760E38DE73AC6DBBFC46A840DB435F20616AB570B5"

**To Reproduce**
--Ubuntu 18.04 
-- Follow the steps described here : https://cronos.crypto.org/docs/getting-started/cronos-testnet.html 
-- Just replace by new version 0.6.1

Exacts steps : 
`sudo su
apt-get update 
apt-get upgrade -y
curl -LOJ https://github.com/crypto-org-chain/cronos/releases/download/v0.6.1/cronos_0.6.1-testnet_Linux_x86_64.tar.gz
tar -zxvf cronos_0.6.1-testnet_Linux_x86_64.tar.gz
rm cronos_0.6.1-testnet_Linux_x86_64.tar.gz
cd bin
./cronosd unsafe-reset-all

./cronosd init totototototo --chain-id cronostestnet_338-3
curl https://raw.githubusercontent.com/crypto-org-chain/cronos-testnets/main/cronostestnet_338-3/genesis.json > ~/.cronos/config/genesis.json
sed -i.bak -E 's#^(minimum-gas-prices[[:space:]]+=[[:space:]]+).*$#\1"5000000000000basetcro"#' ~/.cronos/config/app.toml
sed -i.bak -E 's#^(persistent_peers[[:space:]]+=[[:space:]]+).*$#\1"8fcba3485c67a2a00a383b6f45660a4ac529c6ca@52.77.30.18:26656,e65199bc579ffd89d7c021c5611f9f1c97f7ff13@54.251.209.254:26656"#' ~/.cronos/config/config.toml
sed -i.bak -E 's#^(create_empty_blocks_interval[[:space:]]+=[[:space:]]+).*$#\1"5s"#' ~/.cronos/config/config.toml
sed -i.bak -E 's#^(timeout_commit[[:space:]]+=[[:space:]]+).*$#\1"5s"#' ~/.cronos/config/config.toml
./cronosd keys add Default

./cronosd start`

What is not OK ? No firewall. Disk 1To. 4 Vcpu, 16 Gb Ram.

/******/
EDIT : No problem with version 0.6.0 after testing same steps.

**Comment by thomas-nguy** [comment]
Yeah testnet is still running with version v0.6.0 and v0.6.1 has a breaking change with (#190)
