### ISSUE TITLE
Problem: CI fails with nix 2.4

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#206]
The github action installs nix 2.4 now, and it fails to run.

**Comment by leejw51crypto** [comment]
please add new flag for nix
```
--extra-experimental-features nix-command
```

which is disabled from nix 2.4

**Comment by damoncro** [comment]
Here is the latest test result, it should be ok now. 

Please check: https://github.com/chenyanming/cronos/runs/4176396505?check_suite_focus=true

**Comment by damoncro** [comment]
Same as https://github.com/cachix/install-nix-action/issues/110
