### ISSUE TITLE
Problem: My node doesn't accept any signedTX

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#214]
**Describe the bug**
I noticed I couldn't use web3.eth.sendSignedTransaction from today.

**To Reproduce**
` var signedTx = await web3.eth.accounts.signTransaction(tx, private_key);`
`await web3.eth.sendSignedTransaction(signedTx.rawTransaction);`

Then I get:
`(node:1199) UnhandledPromiseRejectionWarning: Error: Returned error: internal`

in the node it shows:
`ERR failed to broadcast tx error=internal client=json-rpc`

It worked well before. Not sure any change in the chain cause this

**Comment by gap370** [comment]
Also, I just noticed some of my wallets tx couldn't be broadcasted, but some could.

**Comment by yihuang** [comment]
The `internal` is usually about incorrect nonce, or no enough balance to pay the fee.

**Comment by tomtau** [comment]
related issue https://github.com/tharsis/ethermint/issues/731

**Comment by gap370** [comment]
Hi @yihuang, I checked both. The nonce I used in my node failed but it worked in metamask. Also, i have over 100 CRO in the wallet.
