### ISSUE TITLE
Problem: 3k CRO disappeared

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#215]
**Describe the bug**
After I submitted some tx, I noticed my 3k CRO (not WCRO) disappeared. I didn't call any functions with message.value, so I suppose no one could touch my CRO in my wallet? In the explorer, I couldn't locate which tx costed me 3k CRO either.

This is the transaction of my wallet:
https://cronos.crypto.org/explorer/address/0xE11cbdA91F5ccfaa91b35e6Bb10E1f65AEe294da/transactions
This is the coin balance history:
https://cronos.crypto.org/explorer/address/0xE11cbdA91F5ccfaa91b35e6Bb10E1f65AEe294da/coin-balances

According to coin balance history, I had **18561 CRO at block 132633** and it became **1559 CRO at block 132669**.
Meanwhile, I submitted 3 failed SwapExactTokensForETHSupportingFeeOnTransferTokens at block 132637, 132638, 132641, but I didn't send any CRO tokens (tx value are zero). However, I noticed I lost 3k CRO then. Then I decided to transfer most of my CRO away to avoid some potential hack, so I transfered 15k CRO at block 132650. Then I swapped some tokens and got 1k CRO at block 132669. As a result, there was 3k CRO just disappear between block 132633 and 132669. 

Any idea? Thanks!

**Comment by yihuang** [comment]
https://cronos.crypto.org/explorer/tx/0xba7841d057cb096c36b752c188e202cb32184b835d3ff8cf53acf37e4442f0d6/internal-transactions

theres' a 3k cro transfer tx here

**Comment by gap370** [comment]
Hello yihuang, but that's at block 132768. According to my coin balance history, I lost my 3k CRO between block 132633 to 132669.
<img width="1256" alt="Screen Shot 2021-11-16 at 21 37 23" src="https://user-images.githubusercontent.com/14858037/142110604-1e30766d-9c97-49f2-8638-6c85cc4131af.png">

**Comment by gap370** [comment]
@yihuang Sir, this happened again.
https://cronos.crypto.org/explorer/address/0x7FBF20916a966Ce00A1cA00F2E679E2A25B3A719/transactions
I sent 30 CRO two this wallet, and after two failed tx, only 8CRO left. It didn't send anything away.

**Comment by gap370** [comment]
I suspect the chain took the gas_limit * gas_price CRO when a tx execution revert. since I sent 30 CRO there and the first tx is 6k gwei * 2m = 12 CRO and second tx is 5k gwei * 2m = 10CRO. 22CRO gone

**Comment by gap370** [comment]
https://cronos.crypto.org/explorer/address/0x5E40AFf89A4aE267eda57f2401304bF43615De3f/transactions
Here as well. I sent over 30 CRO, after 1 failed tx. 10 CRO is gone.

**Comment by thomas-nguy** [comment]
Thank you for the report on the Cronos mainnet beta version. 

This issue appears to be connected with https://github.com/crypto-org-chain/cronos/issues/221 which has been mitigated in the latest binary release and will be fully resolved in the next network upgrade. If you would like to follow up regarding the investigation of these funds (which appear to be spent in transaction fees due to setting high gas limits and transaction fees appear to be incorrectly displayed in the BlockScout explorer), feel free to reach out to chain@crypto.org
