### ISSUE TITLE
Hello 

### ISSUE THREAD

**Issue by Mita1354** [crypto-org-chain/cronos#228]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/cronos/blob/main/CONTRIBUTING.md#requests-involving-no-code-changes-eg-conventions-processes-or-network-parameters

**Comment by Mita1354** [comment]
Yes I've been mining and staking for BTC for a year and he's yet to pay me he's stiffed all my addresses he's hacked my phone and he's just saying that he's not going to f****** pay me what do I do
