### ISSUE TITLE
Investigate on ICS29 fee middleware

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#234]
In order to bring cosmos tokens to cronos, we need a fee mechanism to cover the cost of maintaining relayers 

ICS29 fee middleware in ibc-go seems still WIP, but worth to have a look and experiment

https://github.com/cosmos/ibc-go/tree/ics29-fee-middleware

**Comment by Muggle-Du** [comment]
I can work on investigating the ICS29 and how could I experiment with this? @thomas-nguy
