### ISSUE TITLE
Problem: no integration test for EIP-1559 feature

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#245]
New ethermint main branch added feemarket, it's good to have it a test.

**Comment by damoncro** [comment]
Good

**Comment by thomas-nguy** [comment]
for this one, yijia added some solidity test on ethermint side
https://github.com/tharsis/ethermint/pull/656

**Comment by yihuang** [comment]
> for this one, yijia added some solidity test on ethermint side [tharsis/ethermint#656](https://github.com/tharsis/ethermint/pull/656)

it only check a basic eip-1559 tx works, I want to check the base fee adjustment based on block load actually works.
