### ISSUE TITLE
Problem: no integration test for transaction index

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#246]
There are some complex logics around transaction index, it's good to check them in the integration test:
- Try different status of tx, and check how they are handled by json rpc API
  - failed, check error message, check it's not included in getBlock API.
  - reverted, check it is included in getBlock API, check getBlockAndTxIndex API works ok, check the tx index in the logs are correct.

**Comment by damoncro** [comment]
I'll look into it.

**Comment by damoncro** [comment]
There are many possible failed cases, I have tested locally: 
- negative coin amount: -42233720368547758080000000000000: panic: panic'}
- ValueError: {'code': -32000, 'message': 'rlp: input string too long for uint64, decoding into (types.LegacyTx).Gas'}
- insufficient fee: insufficient fee'

And many others.

What kind of failed cases should be tested? Or we just need to test one simple failed case, for example, insufficient fee?

**Comment by damoncro** [comment]
By the way, I can not find `getBlockAndTxIndex` api in web3.py, may I know where it is defined?

**Comment by damoncro** [comment]
The transaction index related api are possible: `get_transaction`, `get_transaction_by_block` etc.

**Comment by yihuang** [comment]
> The transaction index related api are possible: `get_transaction`, `get_transaction_by_block` etc.

yes, that's what I mean.

**Comment by yihuang** [comment]
> What kind of failed cases should be tested? Or we just need to test one simple failed case, for example, insufficient fee?

Test the transactions failed at cosmos level are not included in `getBlock` response, and don't accupy a tx index, while reverted tx do.

**Comment by damoncro** [comment]
Would you like to provide more information about `at cosmos level`?

Is doing contract calls `at cosmos level`?

That would help me keep digging into this topic.
