### ISSUE TITLE
Reverted transaction cost too high

### ISSUE THREAD

**Issue by kzadum007** [crypto-org-chain/cronos#248]
On a reverted transaction, total gas cost is gas_limit*gas_price instead of gas_used*gas_price.

Example: https://cronos.crypto.org/explorer/tx/0xca7e168a2d8a841769b1d6e1139b496caa140a762668339db0da8cfccfda196d/internal-transactions

Transaction view:
![image](https://user-images.githubusercontent.com/83700153/145293011-56705bf6-a77a-43c2-b510-c23a9ca5ea9b.png)

Coin balances:
 ![image](https://user-images.githubusercontent.com/83700153/145293038-472a7e72-5822-4e95-b7c5-40b8db9b027c.png)

**Comment by gap370** [comment]
this is a known issue. #221
