### ISSUE TITLE
Problem: pystarport serve --config scripts/cronos-devnet.yaml failling

### ISSUE THREAD

**Issue by rarcif** [crypto-org-chain/cronos#263]
**Describe the bug**
pystarport serve --config scripts/cronos-devnet.yaml is failing when reading the yaml file. It seems as if pystaport is unable to read the env variables set in the .env file. further, pystaport seems to start withouth failing when commenting out the options that are impacted (see screenshot below).

**To Reproduce**
1. git clone https://github.com/crypto-org-chain/cronos
2. cd cronos 
3. pystarport serve --config scripts/cronos-devnet.yaml
4. Error in reading options.

**Expected behavior**
dev node should be starting as usual 

**Screenshots**
<img width="1234" alt="Screenshot 2021-12-17 at 08 46 31" src="https://user-images.githubusercontent.com/92729550/146543240-ec07ccb6-390b-463c-b11f-f11724045a69.png">
<img width="1536" alt="Screenshot 2021-12-17 at 09 14 16" src="https://user-images.githubusercontent.com/92729550/146543274-399a04f8-bb81-4ca5-bcc4-b76a905d69af.png">

**Desktop (please complete the following information):**
 - OS: [iOS, Linux]
 - Browser [chrome]

**Comment by yihuang** [comment]
I think you should install `pip install pystarport==0.2.3`

**Comment by damoncro** [comment]
1. As @yihuang said, `dotenv` is a new feature in 0.2.3
2. `dotenv` is optional, you can delete it. And replace `${}` with fixed values.
3. if `dotenv` is provided, you have to make sure the path you specified (either relative or absolute) and the values inside are correct. In your case, you just simply setup the correct path of the `.env` (located in `scripts` folder), or run pystarport` under `scripts` folder.

**Comment by yihuang** [comment]
closing now, feel free to reopen if the issue still exists.
