### ISSUE TITLE
Problem: test_ibc.py does not cover the reverse flow using evm hook

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#267]
To send CRO from cronos -> crypto.org, we have designed a mechanism relying on `evm-hooks` to be able trigger an IBC transaction through smart contract.

https://github.com/crypto-org-chain/cronos/blob/main/integration_tests/contracts/contracts/CroBridge.sol

This flow is currently not tested by the integration test

TODO:

Complete test_ibc.py 

- After `test_ibc` , create a test that send back the CRO from destination to sender, but instead of creating an ibc transaction, deploy the "CroBridge.sol" contract and call `send_cro_to_crypto_org` function

**Comment by yihuang** [comment]
duplicated with https://github.com/crypto-org-chain/cronos/issues/182 ?

**Comment by damoncro** [comment]
In #182, we do transactions via ` cronosd tx transfer-tokens` command (would it trigger the contract call), is it the same?

**Comment by yihuang** [comment]
> In #182, we do transactions via ` cronosd tx transfer-tokens` command (would it trigger the contract call), is it the same?

they are almost the same, maybe you can do them together.

**Comment by damoncro** [comment]
Good~

**Comment by yihuang** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/367.
