### ISSUE TITLE
the transaction hash is not correct when transaction is creating contract by eth_getBlockByNumber

### ISSUE THREAD

**Issue by wxw1111** [crypto-org-chain/cronos#269]
**Describe the bug**
This transaction is creating a contract, 0x197344bc65be67f1a1e036abcece85a42d95edf277b6c021c7d4c62452948079, you can find in cronos explore. But when you using eth_getBlockByNumber to get the block, 7A44C, you can not find it.
**To Reproduce**
1. eth_getBlockByNumber("7A44C", true) to get all transactions
2. you will find the transaction create contract , with hash: 0xe32a2fb01ab7aef581477b7df287e30124d11f2d0e369d8ca9337474fb6a170a
3. the content of above transaction is the same as 0x197344bc65be67f1a1e036abcece85a42d95edf277b6c021c7d4c62452948079

**Expected behavior**
correct transaction hash
**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. linux]
 - Version [e.g. 0.6.4]

**Additional context**

**Comment by yihuang** [comment]
```
$ curl -H "Content-Type: application/json" -X POST --data '{
    "id": 1337,
    "jsonrpc": "2.0",
    "method": "eth_getBlockByNumber",
    "params": ["0x7A44C", false]}' https://evm-cronos.crypto.org | jq -r ".result.transactions[]" | grep 0x197344bc65be67f1a1e036abcece85a42d95edf277b6c021c7d4c62452948079
0x197344bc65be67f1a1e036abcece85a42d95edf277b6c021c7d4c62452948079
```

I can find the tx in the block.

**Comment by yihuang** [comment]
not reproduced, feel free to reopen if still exists.
