### ISSUE TITLE
Feat: Add `CONTRACTS` dict for contract paths

### ISSUE THREAD

**Issue by damoncro** [crypto-org-chain/cronos#271]
**Is your feature request related to a problem? Please describe.**
As you know, all paths of artifact contract json files are fixed. And we always get the path by
```
Path(__file__).parent
        / "contracts/artifacts/contracts/Greeter.sol/Greeter.json"
```
when deploying the contract.

Paths of artifact contract json files are better to be saved/retrieved in a constant value.

**Describe the solution you'd like**
Make a `CONTRACT` dictionary (just like `KEYS`, `ADDRS`) to save all contract paths. The benefits:
1. No need to type the PATH every time we deploy the contract.
2. Make all path consistent.
3. More readable and avoid typing error. 
etc.

**Comment by yihuang** [comment]
```python
TEST_CONTRACT_PATH = Path(__file__).parent / "contracts/artifacts/contracts"

TEST_CONTRACT_PATH / "Greeter.sol/Greeter.json"
```

make a shared constant `TEST_CONTRACT_PATH`?

**Comment by damoncro** [comment]
Adding `TEST_CONTRACT_PATH` can not serve the purpose.

1. User still needs to type a long path `TEST_CONTRACT_PATH / "Greeter.sol/Greeter.json"` to access the contract.
2. If user wants to change the contract path of all same contract, they still need to change all locations that appeared in the program. But if we just simply makes one simple constant. We only need to change one place.
3. Some contracts not under `TEST_CONTRACT_PATH` can not be managed.
