### ISSUE TITLE
json-rpc flooding debug messages

### ISSUE THREAD

**Issue by nebkas** [crypto-org-chain/cronos#277]
I public provide some json-rpc endpoints and I'm getting flooded with debug messages like:

`cronosd[44300]: t=2021-12-23T18:43:13+0100 **lvl=dbug** msg="Served eth_getTransactionReceipt" conn=xxx.xxx.xxx.xxx:35500  reqid=126253                               t=2.105339ms`

As you can see under the "api" settings 'debug' is not activated but it seems that cronosd ignores this.

```
# Enable defines if the gRPC server should be enabled.
enable = true

# Address defines the EVM RPC HTTP server address to bind to.
address = "xxx.xxx.xxx.xxx:8545"

# Address defines the EVM WebSocket server address to bind to.
ws-address = "0.0.0.0:8546"

# API defines a list of JSON-RPC namespaces that should be enabled
# Example: "**eth,txpool,personal,net,debug,web3**"
api = **"eth,net,web3**"
```

**Comment by yihuang** [comment]
https://github.com/tharsis/ethermint/issues/862

**Comment by yihuang** [comment]
The fix is included in Cronos now: https://github.com/tharsis/ethermint/pull/948.
The RPC access log is redirected to tendermint logger under the debug log level, so it don't display under the default `info` log level.
