### ISSUE TITLE
node losing sync sometimes

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#314]
Hi, I noticed my node would lose sync time by time. Is there any possible reason for this? After I notice it, I just restart the node and wait for it catch up again.  I am in 0.6.5

**Comment by thomas-nguy** [comment]
Hi, 

Is it the same error as the one mentioned [here](https://github.com/crypto-org-chain/cronos/issues/256)? 

Could you try to set the log level to debug and check if you can see something relevant?

**Comment by yihuang** [comment]
duplicated: https://github.com/crypto-org-chain/cronos/issues/284
