### ISSUE TITLE
Feature: Create a proposal type to reinitialize feemarket base fee

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#341]
Given the nature of the feemarket, it would be possible that the network reach some absurd value due to the lack of traffic or congestion for a long duration.

In that case it would be useful to be able to reajust the feemarket parameter through a governance proposal

**Comment by yihuang** [comment]
it's better to implement in ethermint?

**Comment by thomas-nguy** [comment]
okay https://github.com/tharsis/ethermint/issues/937
