### ISSUE TITLE
Bug: My NFT minted results are not recorded on cronos chain.

### ISSUE THREAD

**Issue by Liffion** [crypto-org-chain/cronos#355]
In 2/10, I first transfer(deposit) 25CRO to my wallet. Then I minted some 20 free NFT.
Each mint cost ~1CRO, so my wallet has ~3CRO left.

As you can see, my wallet balance show only ~3CRO.
But no any other transfer and minted success or failed records.
 
This is my wallet transactions.
https://cronos.org/explorer/address/0x383879932db456590cC70C32AAf34E309909e16d/transactions

**Comment by yihuang** [comment]
The transaction has executed succesfully, but tx not found in rpc, this issue is fixed, will be released in 0.7.0 upgrade.
