### ISSUE TITLE
Websocket multiple subscription from same ip causes duplicate responses

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#356]
**Describe the bug**
When I run two instances and subscribe to the same websocket, although the subscription returns different subscription id, it causes cuplicate responses.

**To Reproduce**
```
var main_provider = "ws://localhost:8546";
const Web3 = require('web3');
const web3 = new Web3(main_provider);

const monitor = async () => {

	var subscription = web3.eth.subscribe('newBlockHeaders', async (error, block_info) =>{

		if (!error) {
			console.log('[Block Number] ' + block_info.number.toString());
		}
	});
};
monitor();
```
If you run the code from `n` terminals, each terminal will print the result n times. (in the screenshot, you can see the block 1609002 shows twice because i ran two instances. After i shut down another instance, it becomes normal again in block 1609005.)
<img width="484" alt="Screen Shot 2022-02-22 at 8 43 56 PM" src="https://user-images.githubusercontent.com/14858037/155249063-3ac0469b-b5c4-4743-94eb-5856c834ad16.png">

**Expected behavior**
I think they shouldn't affect each other

**Desktop (please complete the following information):**
Ubuntu 20.04
using v0.6.6 binary, but this issue was there from the first day of the mainnet

**Comment by kaber2** [comment]
The cause of this seems to be some buggy handling of subscriptions in ethermint. Basically the subscription functions iterate over all filters, then for every filter of the same *type*, they deliver one event. The proper thing to do would be to either use only one filter for all subscriptions or just deliver the events from the filter created for each individual subscription.

The fix should be relatively simple, just remove the api.filter iteration in rpc/websocket.go and use the filter created before.

**Comment by gap370** [comment]
@kaber2 So I probably need to build myself to resolve this issue right? Thank you so much!

and hi @yihuang, should I submit an issue in ethermint? Thank you so much

**Comment by yihuang** [comment]
> The cause of this seems to be some buggy handling of subscriptions in ethermint. Basically the subscription functions iterate over all filters, then for every filter of the same _type_, they deliver one event. The proper thing to do would be to either use only one filter for all subscriptions or just deliver the events from the filter created for each individual subscription.
> 
> The fix should be relatively simple, just remove the api.filter iteration in rpc/websocket.go and use the filter created before.

yeah, it's exactly the reason you mentioned, just submitted a fix: https://github.com/tharsis/ethermint/pull/955

**Comment by yihuang** [comment]
the fix is backported to https://github.com/crypto-org-chain/cronos/releases/tag/v0.6.7
