### ISSUE TITLE
query tx receipt from local full node but  return Error:"message handle crashed"?

### ISSUE THREAD

**Issue by csquan** [crypto-org-chain/cronos#369]
hello,I have run a full node local which sync with mainnet follow official site.
when I find tx_hash in block,I have call eth_getTransactionReceipt use tx_hash but retrun error:"message handler crashed".
what is wrong?

**Comment by yihuang** [comment]
- is it full sync or state sync?
- what is the tx_hash
- what is the response of `eth_getTransactionReceipt`

**Comment by csquan** [comment]
not full sync,but my sync height is much low than current height.
when find txs in block,I will call eth_getTransactionReceipt use tx in txs.
but it return null,so ,my program crash...

**Comment by csquan** [comment]
some issues saw that when node reboot,it may miss some index data.
so I make sure my node not reboot while sync,but problem remains.

**Comment by csquan** [comment]
call eth_getTransactionReceipt return Error:"message handle crashed"

**Comment by csquan** [comment]
cronosd log：

t=2022-03-01T16:36:07+0800 lvl=eror msg="RPC method eth_getTransactionReceipt crashed: open /Users/chengshuangquan/.cronos/data/tx_index.db/001381.ldb: too many open files\ngoroutine 17083 [running]:\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call.func1()\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/service.go:200 +0x89\npanic({0x582f0e0, 0xc003021890})\n\t/usr/local/go/src/runtime/panic.go:1038 +0x215\ngithub.com/tendermint/tendermint/state/txindex/kv.(*TxIndex).Get(0xc009c86270, {0xc009bdf5a0, 0xc3, 0x5751301})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/txindex/kv/kv.go:48 +0x11f\ngithub.com/tendermint/tendermint/state/txindex/kv.(*TxIndex).Search(0xc008b0a840, {0x6453448, 0xc0001a4008}, 0xc005962f28)\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/state/txindex/kv/kv.go:256 +0x5a9\ngithub.com/tendermint/tendermint/rpc/core.TxSearch(0xc0034c5b80, {0xc008b0a840, 0xc0059630e8}, 0x0, 0x400bbc7, 0x0, {0x0, 0x0})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/rpc/core/tx.go:75 +0x118\ngithub.com/tendermint/tendermint/rpc/client/local.(*Local).TxSearch(0xc0059630e8, {0x3, 0x3}, {0xc008b0a840, 0x641fb10}, 0xd0, 0x1, 0x0, {0x0, 0x0})\n\t/go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/rpc/client/local/local.go:192 +0x3b\ngithub.com/tharsis/ethermint/rpc/ethereum/backend.(*EVMBackend).GetTxByEthHash(0xc0055d8000, {0x4e, 0xe9, 0xcd, 0x24, 0x2b, 0xed, 0x5f, 0x52, 0x5a, ...})\n\t/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-6/rpc/ethereum/backend/backend.go:612 +0x10d\ngithub.com/tharsis/ethermint/rpc/ethereum/namespaces/eth.(*PublicAPI).GetTransactionReceipt(0xc00000d2c0, {0x4e, 0xe9, 0xcd, 0x24, 0x2b, 0xed, 0x5f, 0x52, 0x5a, ...})\n\t/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-6/rpc/ethereum/namespaces/eth/api.go:586 +0x13c\nreflect.Value.call({0xc001a4f5c0, 0xc005ec0768, 0x7c68f18}, {0x5a49a63, 0x4}, {0xc009176820, 0x2, 0xc0098c97c0})\n\t/usr/local/go/src/reflect/value.go:543 +0x814\nreflect.Value.Call({0xc001a4f5c0, 0xc005ec0768, 0x415dd88}, {0xc009176820, 0x2, 0x3})\n\t/usr/local/go/src/reflect/value.go:339 +0xc5\ngithub.com/ethereum/go-ethereum/rpc.(*callback).call(0xc001a4f620, {0x6453410, 0xc0078510c0}, {0xc009bdf4e0, 0x19}, {0xc0005b26f0, 0x1, 0x408be37})\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/service.go:206 +0x405\ngithub.com/ethereum/go-ethereum/rpc.(*handler).runMethod(0xc0054b8730, {0x6453410, 0xc0078510c0}, 0xc007088ee0, 0xc005fd6598, {0xc0005b26f0, 0x0, 0x8})\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:389 +0x45\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCall(0xc0013a8750, 0xc003021470, 0xc007088ee0)\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:337 +0x239\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleCallMsg(0xc0013a8750, 0x30, 0xc007088ee0)\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:298 +0xd1\ngithub.com/ethereum/go-ethereum/rpc.(*handler).handleBatch.func2(0xc003021470)\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:119 +0xcc\ngithub.com/ethereum/go-ethereum/rpc.(*handler).startCallProc.func1()\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:226 +0xc8\ncreated by github.com/ethereum/go-ethereum/rpc.(*handler).startCallProc\n\t/go/pkg/mod/github.com/crypto-org-chain/go-ethereum@v1.10.3-patched/rpc/handler.go:222 +0x92\n"
t=2022-03-01T16:36:07+0800 lvl=warn msg="Served eth_getTransactionReceipt" conn=[::1]:59499 reqid=3973 t=1.209264ms               err="method handler crashed"

**Comment by yihuang** [comment]
what's your node's response to this request:
```
https://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%27$TXHASH%27%22
```
replace `$TXHASH` to your tx hash, hex encoding, prefixed with `0x`.

**Comment by yihuang** [comment]
I see, the error message is:
```
crashed: open /Users/chengshuangquan/.cronos/data/tx_index.db/001381.ldb: too many open files
```

So you just need to increase the limit, for example: `ulimit -n 10240`.

**Comment by yihuang** [comment]
increase file descriptor limit should fix it, closing now.
