### ISSUE TITLE
unnecessary replace genesis file & modify config file in node setup

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#374]
Hi, I am following the official document to start a fullnode, I can't understand why after `init` operation, we need replace genesis file & modify config files like this.

```bash
$ sed -i.bak -E 's#^(minimum-gas-prices[[:space:]]+=[[:space:]]+).*$#\1"5000000000000basecro"#' ~/.cronos/config/app.toml
$ sed -i.bak -E 's#^(seeds[[:space:]]+=[[:space:]]+).*$#\1"0d5cf1394a1cfde28dc8f023567222abc0f47534@cronos-seed-0.crypto.org:26656,3032073adc06d710dd512240281637c1bd0c8a7b@cronos-seed-1.crypto.org:26656,04f43116b4c6c70054d9c2b7485383df5b1ed1da@cronos-seed-2.crypto.org:26656"#' ~/.cronos/config/config.toml
$ sed -i.bak -E 's#^(create_empty_blocks_interval[[:space:]]+=[[:space:]]+).*$#\1"5s"#' ~/.cronos/config/config.toml
$ sed -i.bak -E 's#^(timeout_commit[[:space:]]+=[[:space:]]+).*$#\1"5s"#' ~/.cronos/config/config.toml
```
Suppose these things should be done in the `init` operation, why generate it then modified it manually.

**Comment by yihuang** [comment]
- the `minimum-gas-prices` and `timeout_commit` are irrelevant for a non-validator full node.
- I think the `create_empty_blocks_interval` is irrelevant too, because the state change for every block, there's no empty block anyway.

So for a normal full node, only need to update the `seeds`.

**Comment by lezzokafka** [comment]
Got it, I will transfer this issue to [cronos-docs](https://github.com/crypto-org-chain/cronos-docs).
Thanks Both!

**Comment by yihuang** [comment]
moved to https://github.com/crypto-org-chain/cronos-docs/issues/132.
