### ISSUE TITLE
Can't create validator, key is never found

### ISSUE THREAD

**Issue by artemisone-org** [crypto-org-chain/cronos#386]
Basically I did all the standard instructions but when it comes to the `create-validator` it will always say that the key is never found. I tried creating keyrings using os or file and both have failed miserably. I'm not sure why I can't convert my node to be a full validator never had issues with other executables...

**Comment by yihuang** [comment]
what's the full command you used?

**Comment by artemisone-org** [comment]
> what's the full command you used? do you specify keyring backend when start the node?
```
cronosd tx staking create-validator \
--moniker="Artemis One" \
--website="https://artemisone.org" \
--amount=xxxudenom \
--pubkey=$(cronosd tendermint show-validator) \
--min-self-delegation="1" \
--details="Artemis One welcomes all Cronos holders to stake with us." \
--commission-rate="0.00" \
--commission-max-rate="1.00" \
--commission-max-change-rate="0.01" \
--from=ArtemisOne \
--chain-id=cronosmainnet_25-1
```

**Comment by yihuang** [comment]
do you see the account name with `cronosd keys list`?

**Comment by artemisone-org** [comment]
> do you see the account name with `cronosd keys list`?

Yes, I see the two accounts I created (Default/ArtemisOne)

**Comment by yihuang** [comment]
does it still happens, have you tried `v0.7.0`?

**Comment by artemisone-org** [comment]
Seems the issue was fixed. I never tested in 0.7.0. Currently using 0.7.1 RC 

Either way I can't become a validator since I don't have the coin needed to become one.

**Comment by yihuang** [comment]
I see, so I'll close now.
