### ISSUE TITLE
Problem: rocksdb node start very slow

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#387]
On mainnet, the rocksdb node could take minutes to startup:
```
2:40AM INF starting ABCI with Tendermint
2:46AM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
```

Try to fine-tune some rocksdb options to optimize this.

**Comment by JayT106** [comment]
Is it happening at every start? suspect the compaction happens when the node opens the rocksdb.

**Comment by yihuang** [comment]
> Is it happening at every start? suspect the compaction happens when the node opens the rocksdb.

yeah, at every start.

**Comment by JayT106** [comment]
https://github.com/facebook/rocksdb/wiki/Speed-Up-DB-Open

**Comment by yihuang** [comment]
https://github.com/cosmos/cosmos-sdk/blob/master/db/rocksdb/db.go#L81
I think the db options used for iavl storage is set in cosmos-sdk, which should be the main bottleneck I think.

**Comment by yihuang** [comment]
the manifest file is small, I guess the issue is big number of sst files?

**Comment by JayT106** [comment]
> The db options used for iavl storage is set in cosmos-sdk, which should be the main bottleneck I think.

Yeah, if the bottleneck is on the Cosmos-SDK side, it would be easier to change the code.

> the manifest file is small, I guess the issue is big number of sst files?

so  we need to turn on the `options.skip_checking_sst_files_sizes_on_db_open` which the cosmos-sdk currently doesn't provide I think.

**Comment by yihuang** [comment]
It seems using lazy loading can significant speed up the `LoadLatestVersion` call: https://github.com/crypto-org-chain/cronos/pull/458/commits/d21dfb1057c7d22412c8ec390934a8cd78419fc4
Not sure about all the implications of this though.

**Comment by JayT106** [comment]
> It seems using lazy loading can significantly speed up the `LoadLatestVersion` call: [d21dfb1](https://github.com/crypto-org-chain/cronos/commit/d21dfb1057c7d22412c8ec390934a8cd78419fc4) Not sure about all the implications though. @JayT106

It should be fine if we are only using it in the `CLI` environment. But maybe it's not a good fit for the node operating.
See 
https://github.com/cosmos/iavl/blob/0dcb21b36728fb4d672edaa06d10488e217dedaa/mutable_tree.go#L353

**Comment by yihuang** [comment]
> > It seems using lazy loading can significantly speed up the `LoadLatestVersion` call: [d21dfb1](https://github.com/crypto-org-chain/cronos/commit/d21dfb1057c7d22412c8ec390934a8cd78419fc4) Not sure about all the implications though. @JayT106
> 
> It should be fine if we are only using it in the `CLI` environment. But maybe it's not a good fit for the node operating. See https://github.com/cosmos/iavl/blob/0dcb21b36728fb4d672edaa06d10488e217dedaa/mutable_tree.go#L353

I see, it's readonly.

**Comment by yihuang** [comment]
I think the main reason is the multistore will load all the versions on startup, the lazy load mode is much faster, but can only be used for the read-only scenario.
I guess there's not much we can do for now, closing the issue.

**Comment by yihuang** [comment]
> Do we consider to fork `tm-db` and making customized settings? The `tm-db` is moving slowly so it's not difficult to catch up with the changes from the upstream.

Since lazy load mode is much faster, the low level db open speed might not have big impact, but you can give it a try on production node to get some concrete data first.
