### ISSUE TITLE
stop sync after synced about 594G data

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#388]
This is the steps I used to start a cronos full node (not validator), it looks good at first, but after synced about `594G` data, the sync progress is stopped, local latest block doesn't increase anymore. I think the robustness of the network need be improved, because after start the node, I just leave it to sync, never touch it again, so why it's stuck?

I will provide additional info if you need(logs, for example), please help to check.

## Download cronos binary

Find the latest released binary at

```bash
https://github.com/crypto-org-chain/cronos/releases
```

Download right version according to your machine (find your machine architecture by `uname -a`)

```bash
wget https://github.com/crypto-org-chain/cronos/releases/download/v0.6.6/cronos_0.6.6_Linux_x86_64.tar.gz
tar -zxvf cronos_0.6.6_Linux_x86_64.tar.gz
```

## Add to path

```bash
sudo mv bin/cronosd /usr/local/bin
```

Check the version (optional)

```bash
cronosd version
```

## **Initialize cronosd**

```bash
cronosd init $moniker --home $datadir --chain-id cronosmainnet_25-1
```

- Replace `$moniker` to what name you want to, this is the name of your node in the network.

- Replace `$datadir`  to what path you want, if don’t specific, by default it’s `~/.cronos` .

After execute the init command, check your data dir, there should be two new dir `config`&  `data`  created.

## Replace genesis file

```bash
cd $datadir
curl https://raw.githubusercontent.com/crypto-org-chain/cronos-mainnet/master/cronosmainnet_25-1/genesis.json > config/genesis.json

```

## Modify config file

In `config/app.toml` update minimum gas price to avoid [transaction spamming](https://github.com/cosmos/cosmos-sdk/issues/4527)

```bash
cd $datadir
sed -i.bak -E 's#^(minimum-gas-prices[[:space:]]+=[[:space:]]+).*$#\1"5000000000000basecro"#' config/app.toml
```

in `~/.cronos/config/config.toml` modify the configurations of `seed`,`create_empty_blocks_interval` and `timeout_commit` by

```bash
cd $datadir
sed -i.bak -E 's#^(seeds[[:space:]]+=[[:space:]]+).*$#\1"0d5cf1394a1cfde28dc8f023567222abc0f47534@cronos-seed-0.crypto.org:26656,3032073adc06d710dd512240281637c1bd0c8a7b@cronos-seed-1.crypto.org:26656,04f43116b4c6c70054d9c2b7485383df5b1ed1da@cronos-seed-2.crypto.org:26656"#' config/config.toml
sed -i.bak -E 's#^(create_empty_blocks_interval[[:space:]]+=[[:space:]]+).*$#\1"5s"#' config/config.toml
sed -i.bak -E 's#^(timeout_commit[[:space:]]+=[[:space:]]+).*$#\1"5s"#' config/config.toml
```

## Start cronos

```bash
cronosd --home $datadir start
```

## Add to systemd service

```bash
cd /usr/lib/systemd/system
sudo rm -f cronos.service
sudo sh -c 'echo "[Unit]
Description=cronos service
[Service]
Type=simple
User=ec2-user
WorkingDirectory=/data/cronos
ExecStart=/usr/local/bin/cronosd --home /data/cronos start
RestartSec=1
[Install]
WantedBy=multi-user.target" >> cronos.service'
sudo systemctl enable cronos
sudo systemctl start cronos
sudo systemctl status cronos
```

## Node status

node syncing status

```bash
cronosd status 2>&1 | jq '.SyncInfo.catching_up'
```

get current highest block by query official node

```bash
curl -s https://rpc.cronos.org/commit | jq "{height: .result.signed_header.header.height}"
```

local node sync progress

```bash
cronosd status 2>&1 | jq '.SyncInfo.latest_block_height'
```

**Comment by allthatjazzleo** [comment]
@huahuayu 
If you dig into the log, you should find similar log
```
cronosd[213251]: 3:17AM ERR prevote step: ProposalBlock is invalid err="wrong Block.Header.AppHash.  Expected 5242079AFB3C5947EDC1374540554ACCA89C6CE94D230BA8C424AAABA2DE410F, got A64D30E6BA9A3D7905145EC3405F4EF53B1CB891C8760D3DCAD8E5443ACA5300" height=1803258 module=consensus round=0 server=node
```

Unfortunately, `^v0.6.6` contains small breaking change as it include cosmos-sdk 0.44.6. Please see the warning message [here](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.44.6).
We already removed those affected github release 

You may sync with 0.6.5 again or download data from [quicksync.io ](https://quicksync.io/networks/crypto.html)

**Comment by huahuayu** [comment]
Yes, noticed that, after restart the client got `wrong Block.Header.AppHash`. Thanks for reply, I will try 0.6.5.

**Comment by huahuayu** [comment]
@allthatjazzleo after downgrade to 0.6.5, can I start from breakpoint or I have to start from scratch?

**Comment by yihuang** [comment]
> @allthatjazzleo after downgrade to 0.6.5, can I start from breakpoint or I have to start from scratch?

I'm afraid you need to start from scratch, it'll be improved after the rollback command come out.

**Comment by huahuayu** [comment]
yes, just done a quick test

```
Mar 14 02:06:20 ip-192-168-2-7.ec2.internal cronosd[27912]: 2:06AM ERR failed init node error="error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 5242079AFB3C5947EDC1374540554ACCA89C6CE94D230BA8C424AAABA2DE410F, got A64D30E6BA9A3D7905145EC3405F4EF53B1CB891C8760D3DCAD8E5443ACA5300"
Mar 14 02:06:20 ip-192-168-2-7.ec2.internal cronosd[27912]: Error: error during handshake: error on replay: wrong Block.Header.AppHash.  Expected 5242079AFB3C5947EDC1374540554ACCA89C6CE94D230BA8C424AAABA2DE410F, got A64D30E6BA9A3D7905145EC3405F4EF53B1CB891C8760D3DCAD8E5443ACA5300
```

**Comment by yihuang** [comment]
due to wrong version, fixed.
