### ISSUE TITLE
Snapshot for sync block

### ISSUE THREAD

**Issue by joslee7410** [crypto-org-chain/cronos#391]
Good day Cronos,

may I know, cronos did provide official snapshot for syncing the block more faster instead of download all the block from scratch?

Thank you.

**Comment by gap370** [comment]
https://quicksync.io/networks/crypto.html

**Comment by JayT106** [comment]
Also, you can check this page for more details.
[#](https://cronos.org/docs/getting-started/cronos-mainnet.html#optional-step-4-quicksync)
