### ISSUE TITLE
public websocket endpoint for test

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#395]
Hi, I searched the doc and visited some third party node provider, I can't find an available websocket endpoint, would you please provide one for test?

**Comment by yihuang** [comment]
I think doing a state sync local node should be pretty fast?

**Comment by huahuayu** [comment]
after 1 day sync, the disk size is 260G，sync status is as below, it will take another several days I think

```bash
$  cronosd status 2>&1 | jq '.SyncInfo.latest_block_height'
"717875"
$ curl -s https://rpc.cronos.org/commit | jq "{height: .result.signed_header.header.height}"
{
  "height": "1908187"
}
```

anyway, if only there's public websocket endpoints :)

**Comment by yihuang** [comment]
I mean the state sync, not a full sync, it'll download most recent state snapshot and sync from there.

**Comment by huahuayu** [comment]
ok, I just searched the term `state sync` in doc, never heard before, it's mentioned in validator node section, but in this section the content is not included, so I don't know it https://cronos.org/docs/getting-started/cronos-mainnet.html

I am not gonna to be a validator now, but maybe in the future. The fullnode is easy to change to a validator, right?

**Comment by yihuang** [comment]
> The fullnode is easy to change to a validator, right?
yes.

closing now, feel free to open new issue if you have other issues.
