### ISSUE TITLE
NFT functionality ( issue, mint, transfer ...)

### ISSUE THREAD

**Issue by GehadG** [crypto-org-chain/cronos#396]
I see that chain-md has a cli functionality for NFTs
Is there any way to do that on cronos chain instead of crypto.com mainnet
Thanks a lot in advance

**Comment by yihuang** [comment]
I believe there are many NFT implementations on solidity which can be deployed to cronos.

**Comment by yihuang** [comment]
There's a native nft module in cosmos-sdk 0.46 now, and the plan is to integrate after interchain-nft is implemented in ibc.
closing now, duplicated: https://github.com/crypto-org-chain/cronos/issues/641
