### ISSUE TITLE
Problem: no integration test for acknowledgement of ibc/gravity-bridge token transfer

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#398]
test the tokens are refunded if the receiver side failed or timeout for `send_to_ethereum`/`send_to_ibc`.

**Comment by thomas-nguy** [comment]
I think there is no concept of timeout for send_to_ethereum. Means that this operation is irreversible.

It is possible to cancel if the transaction is not included in a batch, but the current way is not ideal because batch are created every x blocks, so it is very hard to be able to cancel on time

**Comment by yihuang** [comment]
failed ack scenarios are tested both for [ibc](https://github.com/crypto-org-chain/cronos/pull/613) and [gravity-bridge](https://github.com/crypto-org-chain/cronos/pull/627) now.
