### ISSUE TITLE
panic: invalid Bech32 prefix; expected crc, got tcrc

### ISSUE THREAD

**Issue by izidorit** [crypto-org-chain/cronos#408]
**Describe the bug**
Hi,
I'm new to this node, this was my first time install, but it fails. Followed instractions from here https://cronos.org/docs/getting-started/cronos-mainnet.html#pre-requisites step-by-step, used default folders, moved cronosd into usr/bin, and it fails. And I cannot see any suggestions to this error:
"panic: invalid Bech32 prefix; expected crc, got tcrc"

**To Reproduce**
curl -LOJ https://github.com/crypto-org-chain/cronos/releases/download/v0.6.5/cronos_0.6.5_Linux_x86_64.tar.gz
tar -zxvf cronos_0.6.5_Linux_x86_64.tar.gz
./cronosd init tuf-node --chain-id cronostestnet_338-3
curl https://raw.githubusercontent.com/crypto-org-chain/cronos-testnets/main/cronostestnet_338-3/genesis.json > ~/.cronos/config/genesis.json
cronosd keys add Default
So the result:

> cronosd start
5:44PM INF Unlocking keyring
5:44PM INF starting ABCI with Tendermint
5:44PM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
5:44PM INF Starting localClient service connection=query impl=localClient module=abci-client server=node
5:44PM INF Starting localClient service connection=snapshot impl=localClient module=abci-client server=node
5:44PM INF Starting localClient service connection=mempool impl=localClient module=abci-client server=node
5:44PM INF Starting localClient service connection=consensus impl=localClient module=abci-client server=node
5:44PM INF Starting EventBus service impl=EventBus module=events server=node
5:44PM INF Starting PubSub service impl=PubSub module=pubsub server=node
5:44PM INF Starting IndexerService service impl=IndexerService module=txindex server=node
5:44PM INF ABCI Handshake App Info hash= height=0 module=consensus protocol-version=0 server=node software-version=0.6.5
5:44PM INF ABCI Replay Blocks appHeight=0 module=consensus server=node stateHeight=0 storeHeight=0
panic: invalid Bech32 prefix; expected crc, got tcrc

> goroutine 1 [running]:
> github.com/cosmos/cosmos-sdk/x/bank/keeper.BaseKeeper.InitGenesis({{{{0x27f4520, 0xc0002613d0}, {0x27936b8, 0xc00102a220}, {0x27f5818, 0xc00100c090}}, {0x27f4520, 0xc0002613d0}, {0x27f5818, 0xc00100c090}, ...}, ...}, ...)
>         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.2/x/bank/keeper/genesis.go:21 +0x6ed
> github.com/cosmos/cosmos-sdk/x/bank.AppModule.InitGenesis({{{_, _}}, {_, _}, {_, _}}, {{0x27c9ce8, 0xc000052090}, {0x27fa3a0, 0xc0002128c0}, ...}, ...)
>         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.2/x/bank/module.go:148 +0x1a3
> github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x27c9ce8, 0xc000052090}, {0x27fa3a0, 0xc0002128c0}, {{0x0, 0x0}, {0xc0016ca168, 0x13}, 0x0, ...}, ...}, ...)
>         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.2/types/module/module.go:307 +0x29d
> github.com/crypto-org-chain/cronos/app.(*App).InitChainer(_, {{0x27c9ce8, 0xc000052090}, {0x27fa3a0, 0xc0002128c0}, {{0x0, 0x0}, {0xc0016ca168, 0x13}, 0x0, ...}, ...}, ...)
>         /go/src/github.com/crypto-org-chain/cronos/app/app.go:597 +0x1d2
> github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc002101380, {{0x22792648, 0xed8f8eab3, 0x0}, {0xc0016ca168, 0x13}, 0xc001232c00, {0x38e5ff8, 0x0, 0x0}, ...})
>         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.2/baseapp/abci.go:62 +0x475
> github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc0016f7e00, {{0x22792648, 0xed8f8eab3, 0x0}, {0xc0016ca168, 0x13}, 0xc001232c00, {0x38e5ff8, 0x0, 0x0}, ...})
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/abci/client/local_client.go:272 +0x118
> github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3, {{0x22792648, 0xed8f8eab3, 0x0}, {0xc0016ca168, 0x13}, 0xc001232c00, {0x38e5ff8, 0x0, 0x0}, ...})
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/proxy/app_conn.go:77 +0x55
> github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1dbf234, 0x7}}, {0xc0016ca168, 0x13}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:319 +0xd98
> github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc00103d910, {0x27fba20, 0xc000698b60})
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/consensus/replay.go:268 +0x3c8
> github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1dbf234, 0x7}}, {0xc0016ca168, 0x13}, 0x1, 0x0, ...}, ...)
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:325 +0x1b8
> github.com/tendermint/tendermint/node.NewNode(0xc000277a40, {0x27a3378, 0xc000ef5f40}, 0xc00102bf50, {0x27829e0, 0xc00000f878}, 0x0, 0x0, 0xc001052110, {0x27cace0, ...}, ...)
>         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.14/node/node.go:733 +0x578
> github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x280e3b8, 0xc000fbd0b0}, {0x0, 0x0}, {0x27d3b70, 0xc0002613d0}, ...}, ...)
>         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-6/server/start.go:290 +0xcbf
> github.com/tharsis/ethermint/server.StartCmd.func2(0xc0000fa780, {0x38e5ff8, 0x0, 0x0})
>         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.7.2-cronos-6/server/start.go:119 +0x228
> github.com/spf13/cobra.(*Command).execute(0xc0000fa780, {0x38e5ff8, 0x0, 0x0})
>         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
> github.com/spf13/cobra.(*Command).ExecuteC(0xc000278780)
>         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
> github.com/spf13/cobra.(*Command).Execute(...)
>         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
> github.com/spf13/cobra.(*Command).ExecuteContext(...)
>         /go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:895
> github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc000264cb0, 0xd})
>         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.44.2/server/cmd/execute.go:36 +0x1eb
> main.main()
>         /go/src/github.com/crypto-org-chain/cronos/cmd/cronosd/main.go:13 +0x2c

**Expected behavior**
It should start syncronization

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.10
 - cronosd version
0.6.5

**Additional context**
Any idea, what should I do? 
It's a fresh install, so no old versions to have old prefixesor something like that, but I even tried "cronosd unsafe-reset-all" to reset it.
Firewall was bypassed to avoid any service reachability issues.

Thank you all in advance for your help!

**Comment by yihuang** [comment]
It seems you connected to the testnet using mainnet binary, you should use the binaries whose name has testnet in it.

**Comment by izidorit** [comment]
> It seems you connected to the testnet using mainnet binary, you should use the binaries whose name has testnet in it.

Based on genesis file:

>  ~/.cronos/config # cat genesis.json
> {
>   "genesis_time": "2021-11-08T01:00:00Z",
>   "chain_id": "cronosmainnet_25-1",
>   "initial_height": "1",
>   "consensus_params": {
>     "block": {
>       "max_bytes": "1048576",
>       "max_gas": "10000000",
>       "time_iota_ms": "1000"
>     },
>     "evidence": {
>       "max_age_num_blocks": "403200",
>       "max_age_duration": "2419200000000000",
>       "max_bytes": "150000"
>     },
>     "validator": {
>       "pub_key_types": [
>         "ed25519"
>       ]
>     },
>     "version": {}
>   },

**Comment by yihuang** [comment]
Can you find anything like `tcrc` in your node's config directory?

**Comment by izidorit** [comment]
> Can you find anything like `tcrc` in your node's config directory?

These are the files inside of the default directory:

> -rw-r--r-- 1 root root  9141 Mar 30 17:05 app.toml
> -rw------- 1 root root   695 Mar 30 17:05 client.toml
> -rw-r--r-- 1 root root 15539 Mar 30 17:37 config.toml
> -rw-r--r-- 1 root root 15324 Mar 30 17:08 config.toml.bak
> -rw-r--r-- 1 root root 19442 Mar 30 18:52 genesis.json
> -rw------- 1 root root   148 Mar 30 17:08 node_key.json
> -rw------- 1 root root   345 Mar 30 17:38 priv_validator_key.json
