### ISSUE TITLE
Node stole my CRO

### ISSUE THREAD

**Issue by KutkovetskyiVolodymyr** [crypto-org-chain/cronos#409]
Hello chain team

here is my wallet
https://cronoscan.com/address/0x636ec58d17af00859322af557e040f29500d50bb

I send 3 tx at the about same time each for 25 CRO (+fee)

1st- Success 2136081 block 0xf668943179e3fa9f53ea6b8096c3ae50a2781a057275a4bbdd3dc6457c2cae38
2nd- Fail 2136084 block
3rd- missing ???????? block

![image](https://user-images.githubusercontent.com/25223556/160921352-9e3b20f8-1f92-47ac-8eb9-175911c0794d.png)

state before transactions (2136080 block) is 346.94078098001964867 CRO
image

1 tx for 25cro Success then i sell token for 61.98 (get profit)
after sell i saw balance and its 79.882208449691907471 CRO less then before this all tx's

after all my calculations

346.94078098001964867+(61.985256550308092529-(25+7.41156+2.04428+9.23423+0.221675)) = 365.01429253
but now my balance is 267.058572530327741199 CRO

 365.01429253-267.058572530327741199 = 97.9557199997

I realized what was missing from my balance 97.9557199997 CRO
CRO just disappeared

**Comment by KutkovetskyiVolodymyr** [comment]
I made a mistake, this is cronos chain

**Comment by KutkovetskyiVolodymyr** [comment]
.

**Comment by samuel-tay** [comment]
#221 Is your answer

**Comment by KutkovetskyiVolodymyr** [comment]
I still think it's a bug
