### ISSUE TITLE
Massive logs cannot be closed

### ISSUE THREAD

**Issue by wangzhen130** [crypto-org-chain/cronos#413]
I have two nodes, both using 0.6.5. One of them has been reporting some inexplicable logs. I can't close this part of the log, so the node cannot be synchronized to the latest. Can anyone help me?
![image](https://user-images.githubusercontent.com/81794451/161886576-7ed535b4-3125-4027-89c9-fcf8fbab5d4e.png)

**Comment by yihuang** [comment]
You should set `evm.tracer = ""` in `app.toml`.

**Comment by wangzhen130** [comment]
> You should set `evm.tracer = ""` in `app.toml`.

thanks, very useful
