### ISSUE TITLE
I've lost more than 100 CRO by reverted transactions.

### ISSUE THREAD

**Issue by dewasatriani** [crypto-org-chain/cronos#415]
Hello, i just found the unsynced balance about my transaction. Here my address: https://cronoscan.com/address/0xc49622df1a59d1c77ba1eaa3756ca5db0a6ba696

Starts with tx https://cronoscan.com/tx/0xed6f4d408ef6b61e40fb87314ba996fbccbde72ab07c080e5231a21bdd482694
- I swap 145.7675 USDC to 307.056411257681386814 CRO to my address with 1.13925625 CRO tx fees
- I call to the contract with 60 CRO value and 27.689381769 CRO tx fees (https://cronoscan.com/tx/0x5064706fd7becfc4124b7a28f4b045fd1141221c15cbbdbe6fabe0f92296beea)
- And i call the contract again with 0 CRO value and 37.520977527 CRO tx fees (https://cronoscan.com/tx/0x3b9882e161b0d45d5aa34e66b4f3bdc539e9fe4078e37c0e0d1c52dae5d30484) and i shuld receive the 
  - 14.960203929104020596 CRO
  - 15.077593941907513255 CRO
  - 15.059846897047421537 CRO
- Then, i make a call 4tx (all are reverted) with 3.492930672, 3.197960172, 1.71164, 4.378785 CRO tx fees
  - https://cronoscan.com/tx/0xc478860f0eea42f21fcc78bf8277a9e17eba4584ddfb1edf8d4496ce0ed12314
  - https://cronoscan.com/tx/0x2b15c0fdadeedf05e29e3f5e41c34f686f2c899f140b3527aa4abd3c7e7b7a80
  - https://cronoscan.com/tx/0x09f56afe0171431dfc126db114072ce62d178e504ce5a7d0d9e9d09f72b7a446
  - https://cronoscan.com/tx/0xfd6b130cf96d26456975fbfe641ef848f46b07a285a70b843d28f98780eb2ab8

When i calculate the all of fees + balance i receive and i sent, it should be 213.02146861 CRO. But, my balance is 
39.284792476520692279 CRO in total. Where the rest of my balance?

Thank you for understanding my issues. Hope they will fix this issue soon.

**Comment by dewasatriani** [comment]
UPDATE:

Turns out, the rest of gas is not refunded too. I lost 100 more CRO for reverted transaction with 10,000,000 gas * 5000 gwei gas price (50 CRO) * 2 tx

My balance before: 110
After 2 reverted transactions: 10

My address: https://cronos.org/explorer/address/0xf70c50b911ddf9472030c5092b5B989b712190e0/transactions

TX:
https://cronos.org/explorer/tx/0xd94ae3f74f8946aee2213e6045803b15f3553e7a121af3f95c2d5a5b166f0de8
https://cronos.org/explorer/tx/0xf928c9fae632c657a79a0716e9390668fb7d2cd7f647b0cc1c26ef6608849faf

Please check this transactions. Maybe it's bug?
If this is not bug, please explain why this is happend and how it works. Thanks

**Comment by yihuang** [comment]
Yeah, it's a known issue on mainnet that reverted transactions don't refund unused gas, the issue will be fixed by 0.7.0 upgrade.
In the meantime, we suggest to always use estimateGas to get a more accurate gas limit, plus some buffer just in case, always use the minimal gas price: `0.000005`.
