### ISSUE TITLE
Account nonce is not consecutive

### ISSUE THREAD

**Issue by jaredWu0805** [crypto-org-chain/cronos#417]
**Describe the bug**
The nonce of my account is not consecutive. There are tx for nonce `278` and tx for nonce `280`. But **there is no tx for nonce `279`**. Both `https://cronoscan.com/` and `https://cronos.org/explorer/` show there is no tx for nonce `279`. I also tried to scan through block #`2202922` to #`2204104` and still couldn't find the corresponding tx for nonce `279`.

my account address: 0x25eacdd7b45639142110874150ada35908046325

**Expected behavior**
The nonce of txs of an account should be confirmed consecutively.

**Screenshots**
![Screen Shot 2022-04-05 at 3 50 25 PM](https://user-images.githubusercontent.com/7738504/162106786-d7376fee-7f7f-434b-b765-fde28c950791.png)

tx for nonce 278:
https://cronoscan.com/tx/0x8a6cda8b769eb58b6b727a0d278e1b82740c8e1bd1252cbe241453ee8f594cae
tx for nonce 280:
https://cronoscan.com/tx/0x2cd5c46eb2f8bf778555cd60c7c816750e0e48564d2eadfbf0ef9b5336f1cff3

**Comment by JayT106** [comment]
I will suspect the explorer somehow missing the transaction(non 279) in the database.

**Comment by ViktorPegy** [comment]
> I will suspect the explorer somehow missing the transaction(non 279) in the database.

No, I have the same issue with one of my accounts. It is not an explorer problem, transactions also dropped from node

**Comment by JayT106** [comment]
right, just checked using `block_result`. the tx with nonce 279 is missing.

**Comment by yihuang** [comment]
I find the block `2203472` is the block that increased your nonce, using bisect searching, and the balance also changed in this block:
```
$ seth balance -B $(printf "0x%x" 2203471) 0x25eacdd7b45639142110874150ada35908046325
48023732000000000000
$ seth balance -B $(printf "0x%x" 2203472) 0x25eacdd7b45639142110874150ada35908046325
46195147000000000000
```

It's a known issue on mainnet that a success tx could be missing from explorer.

**Comment by ViktorPegy** [comment]
> I find the block `2203472` is the block that increased your nonce, using bisect searching, and the balance also changed in this block:
> 
> ```
> $ seth balance -B $(printf "0x%x" 2203471) 0x25eacdd7b45639142110874150ada35908046325
> 48023732000000000000
> $ seth balance -B $(printf "0x%x" 2203472) 0x25eacdd7b45639142110874150ada35908046325
> 46195147000000000000
> ```
> 
> It's a known issue on mainnet that a success tx could be missing from explorer.

But you can’t find this transaction in it this block, it’s not explorer issue

**Comment by yihuang** [comment]
> @yihuang But you can’t find this transaction in it this block, it’s not explorer issue

yeah, it's missing in rpc api, not explorer issue.

**Comment by jaredWu0805** [comment]
@yihuang 
Got it. Thank you for the clarification. Looking forward to the 0.7.0 upgrade.

**Comment by jaredWu0805** [comment]
@yihuang 
In what circumstances would rpc drop a success tx? And when will 0.7.0 upgrade be phased in? 
I found this issue impacts a lot since my event listener couldn't detect the events of those dropped txs and the service was malfunctioned accordingly.

**Comment by yihuang** [comment]
> @yihuang In what circumstances would rpc drop a success tx? And when will 0.7.0 upgrade be phased in? I found this issue impacts a lot since my event listener couldn't detect the events of those dropped txs and the service was malfunctioned accordingly.

it happens when the tx's execution happens to exceed block gas limit, it only happens when the block includes more transactions than block gas limit, and at most one tx in the block will have this issue. It happens more frequently recently because higher block load.
The 0.7.0 is to be released in around early May I think.

**Comment by ViktorPegy** [comment]
But state of blockchain is changed even we have dropped tx

**Comment by yihuang** [comment]
> But state of blockchain was changed even if transaction dropped

the transaction is included in the block and executed, it's just the rpc thought it failed.
