### ISSUE TITLE
Sentry node never sync after using Quicksync snapshot

### ISSUE THREAD

**Issue by gap370** [crypto-org-chain/cronos#419]
**Describe the bug**
I followed the tutorial closely on the website and use the pruned snapshot from Quicksync, but my sentry node always behind around 10k blocks. I didn't run any other programs on my server, so I am wondering whether there is any setup I missed.

**To Reproduce**
```
## download binary
curl -LOJ https://github.com/crypto-org-chain/cronos/releases/download/v0.6.5/cronos_0.6.5_Linux_x86_64.tar.gz
tar -zxvf cronos_0.6.5_Linux_x86_64.tar.gz

## init
./cronosd init XXXX --chain-id cronosmainnet_25-1

## download genesis
curl https://raw.githubusercontent.com/crypto-org-chain/cronos-mainnet/master/cronosmainnet_25-1/genesis.json > ~/.cronos/config/genesis.json

## modify seed
sed -i.bak -E 's#^(seeds[[:space:]]+=[[:space:]]+).*$#\1"0d5cf1394a1cfde28dc8f023567222abc0f47534@cronos-seed-0.crypto.org:26656,3032073adc06d710dd512240281637c1bd0c8a7b@cronos-seed-1.crypto.org:26656,04f43116b4c6c70054d9c2b7485383df5b1ed1da@cronos-seed-2.crypto.org:26656"#' ~/.cronos/config/config.toml

## download snapshot and addrbook 

## run 
./cronosd start
```

**Desktop (please complete the following information):**
ubuntu 20.04

**Comment by JayT106** [comment]
Thanks for the report. I suspect the snapshot is using the leveldb as the backend DB,  is that correct?
If that is true, I will suggest my colleague upload the snapshot using rocksDB backend. 
Also, it you don't use the `tx_search` or `block_search` rpc call, you can set the indexer from `kv` to `null` (in the config/config.toml)

**Comment by gap370** [comment]
Hi @JayT106, thanks for the reply. I suspect something is still wrong even after I used the same app.toml and config.toml compared to new node. What I found is after I run `./cronosd unsafe-reset-all`, something is still not right. Since after I delete everything in my old node, it can sync now. It couldn't sync even if I download the binary and snapshot and reset.

**Comment by JayT106** [comment]
In the description, looks like the node can sync just cannot catch up to the network's best height, right? Or is it stuck somewhere?

**Comment by gap370** [comment]
Yeah, it is syncing but in a very slow rate. I am wondering whether it's because I used 0.6.7 before and downgrade to 0.6.5. Everything works abnormally after that. Anyways, after I deleted everything and started again, it's good now.
