### ISSUE TITLE
newPendingTransaction always stopped, and sendTransaction

### ISSUE THREAD

**Issue by tokinaa** [crypto-org-chain/cronos#424]
Hello, i have try to install my full node to a server. I do with quicksync snapshot, and my nodes is run normally.

I tried to listen mempool or newPendingTransaction, then 0-60s is normally. But sometimes will stuck and cant connect again. I try to unsubscribe after subscribe newPendingTransaction, but still same. I see the logs, still normal.

Someone get problem like me too? or maybe this bugs from ethermint?

Also, i try to sending to my node, with sendTransaction. Transaction send, but for waiting receipt is too loong. I have try high gas, and lower gas. but i got same for both result/output.

Sorry for disturb, or my question is weird. I just want to ask and know. Thanks

**Comment by addo47** [comment]
I'm running into the same problem. I'm listening to pending Swap event logs on MMF router and it will randomly pause receiving new events.

**Comment by yihuang** [comment]
these issues are with the websocket subscribe api, right?

**Comment by addo47** [comment]
> these issues are with the websocket subscribe api, right?

Correct.

**Comment by huahuayu** [comment]
similar issue https://github.com/crypto-org-chain/cronos/issues/500

**Comment by mmsqe** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/1239 https://github.com/crypto-org-chain/cronos/pull/1466
