### ISSUE TITLE
JSON RPC error -32000

### ISSUE THREAD

**Issue by Percronos** [crypto-org-chain/cronos#425]
Hey team,

**Technical details**
Release: 0.6.5
OS: Ubuntu 21.04
VM: 16 CPUs, 128gb RAM, 3TO SSD disk.

I'm running a node with the 0.6.5 release, on the following VM: 16 CPUs, 128gb RAM, 3TO SSD disk.

Sometimes, when I try to send several transactions per block, some will success, but some will fail (they are not even sent by the node) with the following error messages:
-   response: '{"error":{"code":-32000,"message":"internal"},"id":6,"jsonrpc":"2.0"}',
-   response: '{"error":{"code":-32000,"message":"internal"},"id":10,"jsonrpc":"2.0"}'

Please note that: 
-  I have enough gas to pay
- The nonce are handled by a dedicated library

As some transactions are successful, it's not related to my code. 
Could it be due to network congestion ? Or should I improve some of my node parameters ?

**Expected behavior:**
 - All transactions should be successful

Thanks for your help,
T

**Comment by yihuang** [comment]
currently, if you send multiple transaction from same sender with increasing nonces concurrently, if they arrive nodes out of order, some of them will be rejected.
In 0.7.0, we'll support a batch tx mode for this use case.
Closing now, fee free to reopen if there's other issue.
