### ISSUE TITLE
The fund sent to main app deduct from source address, but main app not received.

### ISSUE THREAD

**Issue by vandison** [crypto-org-chain/cronos#426]
**Describe the bug**
The fund sent to main app deduct from source address, but main app not received.

**Screenshots**
![image](https://user-images.githubusercontent.com/89897366/163378611-108b9edb-4b45-406f-ab84-1d1c68968734.png)
![image](https://user-images.githubusercontent.com/89897366/163378631-47832e19-ff86-4850-9c1c-5a4cc1691ba4.png)

**Additional context**
TX has
0xce0678a75188db4aa0cbb86232e1e2471303000a94090d0458703dab4fda5b0a

Main app address 
0x62A73a88e40e2ee9983E329BA021545A7D494eb1

Client's address
0xb51B58592d7Ca31546b8F3Bb70e828401DD7aaaE

**Comment by yihuang** [comment]
```
$ seth call -B $(printf "0x%x" 2310054) 0xc21223249CA28397B4B6541dfFaEcC539BfF0c59 "balanceOf(address)(uint256)" 0x62A73a88e40e2ee9983E329BA021545A7D494eb1
0
$ seth call -B $(printf "0x%x" 2310055) 0xc21223249CA28397B4B6541dfFaEcC539BfF0c59 "balanceOf(address)(uint256)" 0x62A73a88e40e2ee9983E329BA021545A7D494eb1
2770571180
```

The usdc transfer happens successfully on chain in block `2310055`, but the tx don't appear in rpc and explorer due to a known bug. we'll try to work with main app to see how can we fix this.
