### ISSUE TITLE
Deployed node websocket cannot connect

### ISSUE THREAD

**Issue by qinxg** [crypto-org-chain/cronos#428]
[v0.6.5]

`
[json-rpc]

# Enable defines if the gRPC server should be enabled.
enable = true

# Address defines the EVM RPC HTTP server address to bind to.
address = "0.0.0.0:8545"

# Address defines the EVM WebSocket server address to bind to.
ws-address = "0.0.0.0:8546"

# API defines a list of JSON-RPC namespaces that should be enabled
# Example: "eth,txpool,personal,net,debug,web3"
api = "eth,txpool,personal,net,debug,web3"`

used
ws://127.0.0.1:8546
ws://ip:8546

None of them can be connected
Am I missing any configuration?

**Comment by yihuang** [comment]
`ws://127.0.0.1:8546` should work, any error messages? is the http one works?

**Comment by qinxg** [comment]
Websocket is not allowed
HTTP success

**Comment by qinxg** [comment]
How can I check the recent running log when I start the service??

**Comment by JayT106** [comment]
> 

Can you see the log show up at the terminal? you can redirect it to a file.

**Comment by qinxg** [comment]
Apr 23 16:03:43  cronosd[75288]: 4:03PM INF indexed block height=2463477 module=txindex server=node
Apr 23 16:03:47  cronosd[75288]: 4:03PM INF Starting JSON WebSocket server address=0.0.0.0:8546
Apr 23 16:03:47  cronosd[75288]: 4:03PM INF New websocket connection module=rpc-server protocol=websocket remote=127.0.0.1:33472 server=node
Apr 23 16:03:47  cronosd[75288]: 4:03PM INF Starting wsConnection service impl=wsConnection module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":33472,"Zone":""} server=node

**Comment by jon4hz** [comment]
Same error here. Beside the log from @qinxg I'm also getting these error messages:

```
May 01 23:03:59 ns3157954 cronosd[3264]: 11:03PM ERR Failed to read request err="websocket: close 1006 (abnormal closure): unexpected EOF" module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":54912,"Zone":""} server=node
May 01 23:03:59 ns3157954 cronosd[3264]: 11:03PM INF Stopping wsConnection service impl={"Logger":{}} module=rpc-server protocol=websocket remote={"IP":"127.0.0.1","Port":54912,"Zone":""} server=node
May 01 23:03:59 ns3157954 cronosd[3264]: 11:03PM ERR error while stopping connection error="already stopped" module=rpc-server protocol=websocket server=node
```

Tested by using `$ geth attach ws://$WS_HOST:8546`

```
$ eth version
Geth
Version: 1.10.17-stable
Git Commit: 25c9b49fdb74931137431c24cf28d3c65f9420d2
Git Commit Date: 20220329
Architecture: amd64
Go Version: go1.18
Operating System: linux
GOPATH=
GOROOT=go
```

**Comment by L2b2n** [comment]
you need https://www.mortysnode.nl/secure-your-strong-node-with-a-reverse-proxy/

wss will be work :)

**Comment by huahuayu** [comment]
> you need https://www.mortysnode.nl/secure-your-strong-node-with-a-reverse-proxy/
> 
> wss will be work :)

I don't think it's wss problem.

**Comment by mmsqe** [comment]
@qinxg can you give newer version a try
```
echo "{\"id\":1,\"method\":\"eth_subscribe\",\"params\":[\"logs\",{\"address\":\"0x3147894Efd526C9A00Ff432f49D34E274e0C6631\"}]}" | websocat -n -t ws://127.0.0.1:8546

{"jsonrpc":"2.0","result":"0x75f7d529b29debf1b433b16e06c9247","id":1}
{"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x75f7d529b29debf1b433b16e06c9247","result":{"address":"0x3147894efd526c9a00ff432f49d34e274e0c6631","topics":["0x1440c4dd67b4344ea1905ec0318995133b550f168b4ee959a0da6b503d7d2414"],"data":"0x000000000000000000000000000000000000000000000000000000000000002a","blockNumber":"0x28","transactionHash":"0x8e4d6654ada10858ccabce65057c311dc75c47d70dbb55c30b0084dad4339bc8","transactionIndex":"0x0","blockHash":"0x55286b23309af536d97c037d2941434f0e088413713435437fca3f9a2a5860b7","logIndex":"0x0","removed":false}}}
```
