### ISSUE TITLE
Limited number of peers (~25), best way to increase it ?

### ISSUE THREAD

**Issue by Percronos** [crypto-org-chain/cronos#447]
Hey team,

I'm running several full nodes on several cloud providers and different locations all around the world.
Most of my full nodes (at least 16+ CPUs, 60+GB RAM) are stuck at 20-30 peers.

I've downloaded the addressbook to get connected to peers faster (https://quicksync.io/addrbook.cronos.json).
What's the best way to increase the number of connected peers ?
Can I, for example, find some lists and add them through the unsafe RPC commands dial_seeds / dial_peers ?
Should I run some other modifications to the config.toml (or other) file ?

**config.tom:**
grpc_max_open_connections = 1900
max_open_connections = 1900
max_subscription_clients = 200
max_subscriptions_per_client = 10

** Comma separated list of seed nodes to connect to **
seeds = "0d5cf1394a1cfde28dc8f023567222abc0f47534@cronos-seed-0.crypto.org:26656,3032073adc06d710dd512240281637c1bd0c8a7b@cronos-seed-1.crypto.org:26656,04f43116b4c6c70054d9c2b7485383df5b1ed1da@cronos-seed-2.crypto.org:26656"

** Comma separated list of nodes to keep persistent connections to**
persistent_peers = ""

** UPNP port forwarding **
upnp = false

** Path to address book **
addr_book_file = "config/addrbook.json"

** Set true for strict address routability rules **
** Set false for private or local networks **
addr_book_strict = true

** Maximum number of inbound peers **
max_num_inbound_peers = 400

** Maximum number of outbound peers to connect to, excluding persistent peers **
max_num_outbound_peers = 100

Ulimit Sn: 65000

Thanks !

**Comment by JayT106** [comment]
Hi,
Have you tried to expose your `external_address` in `config.toml`? Also, consider to set`pex` to  true

**Comment by Percronos** [comment]
Hey,

Thanks, I'll check that and let you know !

**Comment by Percronos** [comment]
Much better indeed.
Thanks for your help @JayT106 !
