### ISSUE TITLE
Problem: db size increase too fast

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#451]
investigate to see if there are low hanging fruits to reduce the db size.

**Comment by yihuang** [comment]
For reference:
```
939G	application.db
42G	blockstore.db
1.0G	cs.wal
46M	evidence.db
4.0K	priv_validator_state.json
47M	snapshots
81G	state.db
238G	tx_index.db
```

## Remove tx_index.db

Currently we rely on tx indexer to query tx by eth tx hash, an alternative solution is to store that index in a standalone kv db in app side, so we don't need to retain all the tx indexes.

**Comment by yihuang** [comment]
## Remove tx_index.db

Currently we rely on tx indexer to query tx by eth tx hash, an alternative solution is to store that index in a standalone kv db in app side, so we don't need to retain all the tx indexes.

**Comment by JayT106** [comment]
> ## Remove tx_index.db
> Currently we rely on tx indexer to query tx by eth tx hash, an alternative solution is to store that index in a standalone kv db in app side, so we don't need to retain all the tx indexes.

yap, we should consider using a new kvstore just for storing the tx hash mapping. Also we can disable the Tendermint indexer for increasing the consensus performance.

**Comment by leejw51crypto** [comment]
ref: https://github.com/ZcashFoundation/zebra/issues/1326

**Comment by adu-crypto** [comment]
> ## Remove tx_index.db
> Currently we rely on tx indexer to query tx by eth tx hash, an alternative solution is to store that index in a standalone kv db in app side, so we don't need to retain all the tx indexes.

you mean nodes could choose not to have this tx_index.db by moving this part off-chain?

**Comment by yihuang** [comment]
> > ## Remove tx_index.db
> > Currently we rely on tx indexer to query tx by eth tx hash, an alternative solution is to store that index in a standalone kv db in app side, so we don't need to retain all the tx indexes.
> 
> you mean nodes could choose not to have this tx_index.db by moving this part off-chain?

yes, by store the eth tx hash index in another place.

**Comment by JayT106** [comment]
I will start a testing build with the custom RocksDB setup to see how good it can be improved

**Comment by yihuang** [comment]
```
# IndexEvents defines the set of events in the form {eventType}.{attributeKey},
# which informs Tendermint what to index. If empty, all events will be indexed.
#
# Example:
# ["message.sender", "message.recipient"]
index-events = []
```

There's an option to fine turn what events to be indexed in `app.toml`.

**Comment by JayT106** [comment]
> For reference:
> 
> ```
> 939G	application.db
> 42G	blockstore.db
> 1.0G	cs.wal
> 46M	evidence.db
> 4.0K	priv_validator_state.json
> 47M	snapshots
> 81G	state.db
> 238G	tx_index.db
> ```

Which block height was observed in this DB scale?

**Comment by JayT106** [comment]
Looks like` lz4` might be working, and the current `application.db` at height 1730K is around 511G. Projecting today's block height will be around 755G. And `application.db` of the full node with rocksDB using `snippy` is 1057G. roughly 25% space-saving.

Wait until the testing node fully syncs up to the network and see the final result.

**Comment by yihuang** [comment]
@tomtau mentioned we could do some statistics on the `applications.db` to see what kinds of data occupy most space, then see if there's any waste can be saved in the corresponding modules. For example, iterate the iavl tree, and sum the value lengths with the module prefixes. can you do that @JayT106 .

**Comment by yihuang** [comment]
BTW, this is `prunning=default` node size (thanks @allthatjazzleo):
```
535G	/chain/.cronosd/data/application.db
20K	/chain/.cronosd/data/snapshots
44G	/chain/.cronosd/data/blockstore.db
120G	/chain/.cronosd/data/state.db
312G	/chain/.cronosd/data/tx_index.db
20K	/chain/.cronosd/data/evidence.db
1023M	/chain/.cronosd/data/cs.wal
1011G	/chain/.cronosd/data/
```

Compared to full archive one:
```
1.1T	/chain/.cronosd/data/application.db
79M	/chain/.cronosd/data/snapshots
47G	/chain/.cronosd/data/blockstore.db
90G	/chain/.cronosd/data/state.db
260G	/chain/.cronosd/data/tx_index.db
78M	/chain/.cronosd/data/evidence.db
1.1G	/chain/.cronosd/data/cs.wal
1.5T	/chain/.cronosd/data/
```

**Comment by JayT106** [comment]
> BTW, this is `prunning=default` node size (thanks @allthatjazzleo):
> 
> ```
> 535G	/chain/.cronosd/data/application.db
> 20K	/chain/.cronosd/data/snapshots
> 44G	/chain/.cronosd/data/blockstore.db
> 120G	/chain/.cronosd/data/state.db
> 312G	/chain/.cronosd/data/tx_index.db
> 20K	/chain/.cronosd/data/evidence.db
> 1023M	/chain/.cronosd/data/cs.wal
> 1011G	/chain/.cronosd/data/
> ```
> 
> Compared to full archive one:
> 
> ```
> 1.1T	/chain/.cronosd/data/application.db
> 79M	/chain/.cronosd/data/snapshots
> 47G	/chain/.cronosd/data/blockstore.db
> 90G	/chain/.cronosd/data/state.db
> 260G	/chain/.cronosd/data/tx_index.db
> 78M	/chain/.cronosd/data/evidence.db
> 1.1G	/chain/.cronosd/data/cs.wal
> 1.5T	/chain/.cronosd/data/
> ```

the `pruning=default` only keeps last 100 states, so it will be good for running the node without query functions.

**Comment by JayT106** [comment]
Got the testing node synced up to the plan upgrade height,
using default:
```
1057776M	./application.db
45714M	./blockstore.db
88630M	./state.db
```
using `lz4`
```
1058545M	./application.db
47363M	./blockstore.db
88633M	./state.db
```
It meets the benchmark in this article. There is no gain from the compression ratio, only gains from the compression/decompression speed   
https://morotti.github.io/lzbench-web/?dataset=canterbury/alice29.txt&machine=desktop

**Comment by tomtau** [comment]
why is state.db larger in the pruned one? (120GB vs 90GB)

**Comment by JayT106** [comment]
Went through the `application.db`, Got some basic statistic numbers (at height 2933002 and the size is raw data length):
evm and ibc module use major store space in the database which is not surprised, will look at more details in these modules

evm
~24.6M kv pairs, keySizeTotal: ~1.3G, valueSizeTotal: ~976M, avg key size:52, avg value size:39
ibc
~2.6M kv pairs, keySizeTotal: ~149M, valueSizeTotal: ~58M, avg key size:57, avg value size:22

**Comment by JayT106** [comment]
In the ibc store Key patterns:
`acks/ports/transfer/channels/channel-0/sequences/...` counts 1003777
`receipts/ports/transfer/channels/channel-0/sequences/...` counts 1003777
`clients/07-tendermint-1/consensusStates/...` counts 403893
`636C69656E74732F30372D74656E6465726D696E742D31...` (hex code of clients/07-tendermint-1) counts 134631

**Comment by tomtau** [comment]
I guess some historical (i.e. older than "evidence age") states, acks, receipts... could be pruned from ibc application storage?
Do you have a more detailed breakdown of evm?

**Comment by yihuang** [comment]
https://github.com/cosmos/ibc-go/blob/release/v2.2.x/modules/light-clients/07-tendermint/types/update.go#L137
for the `consensusStates`, there's a pruning logic, but it only deletes at most one item at a time.

the sequences keys seems don't have pruning at all.

**Comment by JayT106** [comment]
> Do you have a more detailed breakdown of evm?
working on it,
The evmstore stores: 
1: code,  the key will be the prefix `01` + codehash (this part should be fine)
2: storage, the key will be the prefix `02` + eth account address +  hash of something (trying to figure out)

**Comment by yihuang** [comment]
The EVM module's storage schema is much simpler, code and storage, and the storage slots are calculated by EVM module, I guess there's not much to prune there.

**Comment by yihuang** [comment]
> 2: storage, the key will be the prefix 02 + eth account address + hash of something (trying to figure out)

it's the storage slot number, computed by evm internal.

**Comment by JayT106** [comment]
> > 2: storage, the key will be the prefix 02 + eth account address + hash of something (trying to figure out)
> 
> it's the storage slot number, computed by evm internal.

in the storage part, the address `1359135B1C9EB7393F75271E9A2B72FC0D055B2E` has 382381 kv pairs, so does it store that much slots?
https://cronos.org/explorer/address/0x1359135B1C9Eb7393f75271E9a2b72fc0d055B2E/transactions

**Comment by yihuang** [comment]
> > > 2: storage, the key will be the prefix 02 + eth account address + hash of something (trying to figure out)
> > 
> > 
> > it's the storage slot number, computed by evm internal.
> 
> in the storage part, the address `1359135B1C9EB7393F75271E9A2B72FC0D055B2E` has 382381 kv pairs, so does it store that much slots? https://cronos.org/explorer/address/0x1359135B1C9Eb7393f75271E9a2b72fc0d055B2E/transactions

to verify that, we need to have the source code, the solidity compiler can output a storage layout file which is helpful to verify the slots.

**Comment by yihuang** [comment]
I just had an idea to potentially trade some speed for disk space:
currently, the storage format is like this:
```
02 + address{20} + slot1{32} -> value1{32}
02 + address{20} + slot2{32} -> value2{32}
...
```
Alternatively:
```
02 + address{20} + slotHighBits{20} -> {slotLowBits{12} -> value, ...}
```

It groups at most `4096` values into one KV pair, I guess it helps to reduce redundancy in the keys, and intermediate overhead in iavl tree.

**Comment by yihuang** [comment]
go-ethereum stores each contract's state in an independent trie, so their structure is like this:
```
accounts-trie:
  contract address -> rootHash

rootHash:
  slot1 -> value1
  slot2 -> value2
```

So much less redundancy there.

**Comment by JayT106** [comment]
> Another thing related is, in `v0.6.x` we had a minor issue that contract suicide don't really delete the code and storage, not sure how much impact does that have on the db size though.

Does our indexer know how many (and which) contracts had been suicided? from the datastore cannot see which contract had been suicided

**Comment by JayT106** [comment]
> https://github.com/cosmos/ibc-go/blob/release/v2.2.x/modules/light-clients/07-tendermint/types/update.go#L137 for the `consensusStates`, there's a pruning logic, but it only deletes at most one item at a time. we might need to check how many expired ones are currently.
> 
> the sequence keys don't seem prune at all.

the active consensusStates is 102 (block height around 3M) and seems like about the same at the height 2M.
Maybe we can prune a lot of kv pairs?

**Comment by JayT106** [comment]
> @JayT106 do you have more insight into the EVM values? (e.g. leaf vs non-leaf)

The EVM storage(prefix 02) stores 32 bytes values in each slot according to the yellow paper
```
The set of accessed storage keys (more accurately, each
element of AK is a tuple of a 20-byte account address and
a 32-byte storage slot).
```
I think @yihuang's solution can provide around 14% raw data space-saving (not counting the IAVL structure overhead)

**Comment by tomtau** [comment]
> Would it be possible for the structure overhead of the IAVL is heavier than the Ethereum trie? meaning most of the data storage is consumed by the IAVL intermediate nodes, not the kv pair itself(if we only store small size kv pairs)?

@JayT106 could you check that, so for that ~976M, there's a breakdown of leaf vs non-leaf values?

**Comment by JayT106** [comment]
@tomtau 
reiterate the evm module at height 2933002, we can see the intermediate nodes use a lot of space more than the raw data we want to store at DB.

leaf:
count 24648017
total raw key size ~ 1.3G
total raw value size ~ 976M
total encoded data size (the actual node struct stored in DB as a value, the DB key is `node.hash`) 2.476G

non-leaf:
count 24648016
total raw key size ~ 1.3G
total raw value size  0
total encoded size ~ 3.1G

```
type Node struct {
	key       []byte
	value     []byte
	hash      []byte
	leftHash  []byte
	rightHash []byte
	version   int64
	size      int64
	leftNode  *Node
	rightNode *Node
	height    int8
	persisted bool
}
```

**Comment by yihuang** [comment]
All the nodes of evm module only add up to several gigabytes, but the total db is hundreds of gigabytes, there are another unknown factor?

**Comment by JayT106** [comment]
> 



> All the nodes of evm module only add up to several gigabytes, but the total db is hundreds of gigabytes, there are another unknown factor?

This is just for version 2933002. I didn't iterate the whole other versions of the IAVL tree

**Comment by yihuang** [comment]
> > 
> 
> > All the nodes of evm module only add up to several gigabytes, but the total db is hundreds of gigabytes, there are another unknown factor?
> 
> This is just iterating the tree version 2933002. There is an orphan data(the historical node data) in the DB, I will calculate the size.

the `prunning=default` keeps the last 100 states of every 500th block, which is `3076735 / 500 + 100 = 6253` for mainnet, the db size is still more than 500G. can you check how large the DB is if we pruning all the history versions?

**Comment by tomtau** [comment]
EVM traces are important in the historical storage, so that's something to look at: how much is consumed by them, and if it's taken most of the storage, whether they can be stored in a more resourceful way

**Comment by JayT106** [comment]
> There is an orphan data(the historical node data) in the DB, I will calculate the size.

Iterating the db with all orphans: 3,394,612,961,totalKeySize: 166G, totalValueSize: 108.6G
I think there are some intermediate nodes in the other version that haven't been calculated.

> can you check how large the DB is if we pruning all the history versions?
sure, will check it.

> EVM traces are important in the historical storage, so that's something to look at: how much is consumed by them, and if it's taken most of the storage, whether they can be stored in a more resourceful way

From https://geth.ethereum.org/docs/dapp/tracing
Geth will regenerate the desired state by replaying blocks from the closest point in time before B where it has full state. This defaults to 128 blocks max, but you can specify more in the actual call ... "reexec":1000 .. } to the tracer.

Maybe we can define the proper state pruning interval to make sure the tx re-executing is not too heavy to the node?

**Comment by tomtau** [comment]
> Iterating the db with all orphans: 3,394,612,961,totalKeySize: 166G, totalValueSize: 108.6G
> I think there are some intermediate nodes in the other version that haven't been calculated.

Not sure what the keys are like, but if the slot keys, bucketing or `sha3(contract address, slot) -> value` could perhaps help.

> Maybe we can define the proper state pruning interval to make sure the tx re-executing is not too heavy to the node?

@JayT106 you can try syncing with a different config and consult with @CeruleanAtMonaco @jun0tpyrc if that config will still be all right for dApps or exchanges that need a full or archival node-like setting.
I'd also suggest to create a test environment for experimenting with the code change impact on the storage, given it seems it's hard to tell:
1. export mainnet transactions up to a certain block height (I assume the upgrade height could give a perspective on the current storage usage)
2. create some experimental binaries forked off cronosd that will:
- be able to replay the exported transactions (without consensus) and store them
- have a patch of Ethermint that could reduce the storage size growth: slot storage changed, using v0.46.0-rc1 Cosmos SDK and its "V2" storage...

**Comment by JayT106** [comment]
> the `prunning=default` keeps the last 100 states of every 500th block, which is `3076735 / 500 + 100 = 6253` for mainnet, the db size is still more than 500G. can you check how large the DB is if we pruning all the history versions?

I think the comments on the `app.toml` is misleading. Checked in the SDK v0.44.6 & v0.45.4
The `default` pruning is:
```
PruneDefault = NewPruningOptions(362880, 100, 10)
```
meaning the app will keep the latest 362880 versions (around 21 days by 5 secs block time), and then only keep 1 version for every 100 blocks past the `keepRecent` period( the rest will be put into the pruning list), and then execute the pruning every 10 blocks.

Also, the settings are only affecting the current DB, meaning it will not prune the past version far over the `keepRecent` period if the node was set prune `nothing`

**Comment by JayT106** [comment]
> Not sure what the keys are like, but if the slot keys, bucketing or sha3(contract address, slot) -> value could perhaps help.

I think it's the slot keys, the past state (changed or removed) relates to the contract address.

**Comment by yihuang** [comment]
> > the `prunning=default` keeps the last 100 states of every 500th block, which is `3076735 / 500 + 100 = 6253` for mainnet, the db size is still more than 500G. can you check how large the DB is if we pruning all the history versions?
> 
> 
> 
> I think the comments on the `app.toml` is misleading. Checked in the SDK v0.44.6 & v0.45.4
> 
> The `default` pruning is:
> 
> ```
> 
> PruneDefault = NewPruningOptions(362880, 100, 10)
> 
> ```
> 
> meaning the app will keep the latest 362880 versions (around 21 days by 5 secs block time), and then only keep 1 version for every 100 blocks past the `keepRecent` period( the rest will be put into the pruning list), and then execute the pruning every 10 blocks.
> 
> 
> 
> Also, the settings are only affecting the current DB, meaning it will not prune the past version far over the `keepRecent` period if the node was set prune `nothing` 
> 
> 

Does that mean a more aggressive pruning setting can drop the db size a lot? 
At least validator nodes can use a much more aggressive pruning setting.

**Comment by JayT106** [comment]
I will set up a testing node to see the result of different pruning setups.

**Comment by calvinaco** [comment]
> But a problem will be they cannot be a reference node of the snapshot.

What is the significance for a validator to be a ref. node of the snapshot? If we are pushing validator to its max storage efficiency I think they don't need to be that?

**Comment by JayT106** [comment]
> What is the significance for a validator to be a ref. node of the snapshot? If we are pushing validator to its max storage efficiency I think they don't need to be that?

If our validator doesn't need to be a ref. node of the snapshot. Then yes, we can prune everything. But the outside validators will need to know the difference in setting up the different pruning options.

**Comment by JayT106** [comment]
@tomtau 
by checking the ADR-040 status, I didn't see they mentioned the `V2` storage has solved the storage size issue. On the contrary, it might cause [ key overhead](https://github.com/cosmos/cosmos-sdk/blob/1326fa2a7dfc3d83cf23dc1c1f33ff131152ad60/docs/architecture/adr-040-storage-and-smt-state-commitments.md#negative). Moreover, I feel like the current implementation is [not feature-complete](https://github.com/cosmos/cosmos-sdk/issues/9816).

However, I agree with you we can test it with the new SDK to see the impact.

**Comment by tomtau** [comment]
> @tomtau by checking the ADR-040 status, I didn't see they mentioned the `V2` storage has solved the storage size issue. On the contrary, it might cause [ key overhead](https://github.com/cosmos/cosmos-sdk/blob/1326fa2a7dfc3d83cf23dc1c1f33ff131152ad60/docs/architecture/adr-040-storage-and-smt-state-commitments.md#negative). Moreover, I feel like the current implementation is [not feature-complete](https://github.com/cosmos/cosmos-sdk/issues/9816). @adu-crypto could you share your insight on it?
> 
> However, I agree with you we can test it with the new SDK to see the impact.

Possibly, there are two things to verify:

1. it should have less overhead in terms of the intermediate nodes and metadata
2. try a more "custom" usage of ADR-040 to mimic go-ethereum's storage: https://github.com/crypto-org-chain/cronos/issues/451#issuecomment-1139235829 (SC to store root hashes, SS to store slot mappings)
> use low level db snapshots for versioning
> don’t rely on the versioning ability of the Sparse Merkle tree?
> and we can just store the contract storage in the Sparse Merkle tree
> if we rely on low level db snapshots, we may be able to extent it to do whatever we want on the database, still enjoy the atomicity and versioning
> like adopt the ethereum-like implementation, just put on a different column family

**Comment by adu-crypto** [comment]
> we've refactored a chain (evmos) to run on the testnet; now have to refactor it again, since 0.46 is reverting back to ante-handlers

currently they are refactoring evmos to test on it.
speaking of feature-completion, I think current store v2 module in main branch is not compatible with the old store v1, which means you need more effort to replace store v1 with store v2 in baseapp I think.
besides as I known, they are also working on the compatibility with IBC bridge.

**Comment by yihuang** [comment]
> From https://geth.ethereum.org/docs/dapp/tracing
> Geth will regenerate the desired state by replaying blocks from the closest point in time before B where it has full state. This defaults to 128 blocks max, but you can specify more in the actual call ... "reexec":1000 .. } to the tracer.

Sounds like a good idea, but need to do in cosmos-sdk level: https://github.com/cosmos/cosmos-sdk/issues/12183

**Comment by yihuang** [comment]
FYI, @GaryOr has synced a pruned node which only keep the recent 50 versions, the db size is:

```
1.0G	data/cs.wal
99G	data/state.db
54G	data/blockstore.db
16K	data/lost+found
295G	data/tx_index.db
12G	data/application.db
74M	data/snapshots
9.5M	data/evidence.db
458G	data/
```

noticeably, `application.db` is only `12G`.

**Comment by JayT106** [comment]
if we want more aggressive, we can set `min-retain-blocks` to 50 or something, it will prune `state.db` and `blockstore.db`.
But it is probably only for the validator's setup.

I am working on the storage migrating V1 to V2 and calculating the size.

**Comment by JayT106** [comment]
To migrate from store V1 to V2 might have a big problem. We have 24M+ kv pairs in the latest version (2933002) of my testing evm module. It took 4 days and only migrated ~1/3 kv pairs (still ongoing).
I wonder if there is a big performance downgrade when SMT is inserting a huge amount of the kv pairs.
https://github.com/cosmos/cosmos-sdk/blob/ecdc68a26bd4bd5482bb0ffe72999bdb74dcbd94/store/v2alpha1/multi/migration.go#L57

However, I tested a small amount of dataset to evaluate the DB size between storeV1 and storeV2, looks like it helps a bit if we ignore the rocksDB's `checkpoints`
https://github.com/cosmos/cosmos-sdk/issues/12251

I will try to scale the simulation to see the different numbers. But we might need to dig SMT implementation to see why the migration takes so long? @adu-crypto any idea?

**Comment by yihuang** [comment]
But using v2 store without creating checkpoints for every version don't support query historical state, right?

**Comment by tomtau** [comment]
@JayT106 how about with go-leveldb? with that SC/SS separation, maybe go-leveldb still may be viable for RPC nodes?

**Comment by JayT106** [comment]
> But using v2 store without creating checkpoints for every version don't support query historical state, right?

That sounds right, but I don't understand why checkpoints took so many disk spaces, could it be possible some implementation issue in it?

> how about with go-leveldb?

The SDK v0.46.x didn't implement the go-leveldb for supporting the v2 store.

**Comment by adu-crypto** [comment]
> To migrate from store V1 to V2 might have a big problem. We have 24M+ kv pairs in the latest version (2933002) of my testing evm module. It took 4 days and only migrated ~1/3 kv pairs (still ongoing). I wonder if there is a big performance downgrade when SMT is inserting a huge amount of the kv pairs. Because the migration is iterating the kv pairs of the v1store and then setting kv to the substore of the v2store, submitting the changes in the end. https://github.com/cosmos/cosmos-sdk/blob/ecdc68a26bd4bd5482bb0ffe72999bdb74dcbd94/store/v2alpha1/multi/migration.go#L57
> 
> However, I tested a small amount of dataset to evaluate the DB size between storeV1 and storeV2, looks like it helps when we ignore the rocksDB's `checkpoints` [cosmos/cosmos-sdk#12251](https://github.com/cosmos/cosmos-sdk/issues/12251)
> 
> I will try to scale the simulation to see the different numbers. But we might need to dig the SMT implementation to see why the migration takes so long? @adu-crypto any idea?

@JayT106  currently, smt has a slow down of more than an order of mgnitude speaking of write performance.
this is fully benchmarked and discussed:
https://github.com/cosmos/cosmos-sdk/issues/11328#issuecomment-1087613934
https://github.com/cosmos/cosmos-sdk/issues/11444
they have done some optimizations like removing the smt level key -> value cache and not recomputing root hash every time  util commit and so on.
they even have a new smt implementation.
I think this is possibly the biggest blocker for smt migration now.

**Comment by tomtau** [comment]
some ideas from turbogeth/erigon: https://github.com/ledgerwatch/erigon#more-efficient-state-storage
https://github.com/ledgerwatch/erigon/blob/devel/docs/programmers_guide/db_walkthrough.MD

**Comment by tomtau** [comment]
> Or we should look at the Cosmos SDK new SMT implementation to see anything we can contribute and then might be able to use it earlier?

Yes, I think fixing the issues in the SMT implementation is the way to proceed (plus also trying how the SMT implementation could be best leveraged in the Ethermint context, see the "custom" usage note: https://github.com/crypto-org-chain/cronos/issues/451#issuecomment-1149345547 to mimic go-ethereum).

Two related notes / issues:
- https://hackmd.io/Jrvb6WocTzqVnD9kZpDocg
- https://github.com/tendermint/tendermint/issues/8028

**Comment by yihuang** [comment]
Several updates:
- Can't run `v0.6` `fix-unlucky-tx` with pruning, because it needs to replay old tx.
 - We need to sync without pruning, run `fix-unlucky-tx`, then prune manually.

- Using minimal `index-events` config reduce `tx-index.db` to half, it still needs to store the full tx result, so it can't be reduced further by removing indexes. So I think the ethermint custom tx indexer should be much better, will try that soon.

**Comment by yihuang** [comment]
https://github.com/evmos/ethermint/pull/1121/files#issuecomment-1170680784

The tx indexer db size reduction is promising with the custom eth tx indexer.

**Comment by yihuang** [comment]
I think we can close this one now in favor of the tracking issue #869 of the development progress @tomtau
