### ISSUE TITLE
Problem: The unlucky transactions are not shown in json rpc

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#455]
## What is Unlucky Tx

The transactions whose execution happens to exceed block gas limit are not shown in json-rpc response, there's at most one in each block when it includes more tx than capacity.

Before `v0.7.0`, these transactions are executed successfully but return error in deliver tx response, after `v0.7.0`, the executions are reverted, and return the same error in response as before. In both cases, the tx can't be found in json-rpc response.

## How To Identify The Unlucky Tx

```
for tx_result in reqeusts.get('/block_results', params={'height': block_number}).json()['result']['txs_results']:
  if tx_result['Code'] == 11 and 'out of gas in location: block gas meter; gasWanted:' in tx_result['Log']:
    # this is an unlucky tx
```

### Tx Hash Index

Currently json-rpc using `/tx_search` to find tx info by eth tx hash, so we need to have those eth tx hashes indexed.
For the legacy blocks before upgrade, we need to patch the tx indexer db to add the missing txs.
For new blocks, we should change the code to emit a eth tx hash event in ante handler, so the failed tx can be indexed.

> Alternatively we can [design a new way to index the eth tx hash](https://github.com/tharsis/ethermint/issues/1075).

### Tx Result

Need to patch the tx result of the unlucky txs before v0.7.0 upgrade
- replay the block to get the correct tx result of the unlucky tx
- update the tx result in the db

## DB Keys To Patch

- Indexer DB: Key: `ethereum_tx.ethereumTxHash/{ETH_HASH}/{res.Height}/{res.Index}`, Value: tm hash.
- Indexer DB: Key: `tm hash`, Value: `abci.TxResult`.
- State DB: Key: `abciResponsesKey:{height}`, Value: `tmstate.ABCIResponses`.

## How To Replay A Block

**Comment by tomtau** [comment]
is also one solution if the tm tx indexer isn't used: https://github.com/crypto-org-chain/cronos/issues/451 ?

**Comment by yihuang** [comment]
> is also one solution if the tm tx indexer isn't used: [#451 (comment)](https://github.com/crypto-org-chain/cronos/issues/451#issuecomment-1115918818) ?

yes, I've added to it, the other thing to patch is the tx result, need to replay the block to get it.

**Comment by yihuang** [comment]
> @yihuang Does the nonce of the unlucky reverted transaction count?
> 
> If I send a tx with nonce 10, with V0.7.0 it is reverted if it is the unlucky tx. Does the next tx from this address need to have a nonce of 10 or 11? It should be 11 like a normal reverted tx.

nonce is increased too, it should be 11.
