### ISSUE TITLE
Problem: no governance managed native to contract mapping

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#46]
Follow up on: https://github.com/crypto-org-chain/cronos/issues/24

An important part in the token wrapping plan is: managing a map from native denom to external contract address with governance module.

Trying to sketch what needs to be done after https://github.com/crypto-org-chain/cronos/pull/34:

- Add a genesis field to store the mapping in genesis
- Implement a gov proposal handler to maintain the mapping (add/delete/update):
  - When a new token is mapped, should the existing native balances be moved to erc20 automatically at the proposal handler?
    - Positive: convenience for the user
    - Negative: potentially unbounded computation resource needed, 
- A message to move the native token to erc20 manually, I think we also needs this just in case?

**Comment by thomas-nguy** [comment]
```
A message to move the native token to erc20 manually, I think we also needs this just in case?
```

I vote for this proposal.

Even if we implement the gravity hook, this message is still needed in case an error happens within the hook (except if we make the gravity transfer + hook atomic, but it is too dangerous to revert a gravity transfer that already happen)

In the case users already have sent their assets to gravity bridge before we "announced" that it is supported, which should be rare case, they can use the manual transaction to convert manually their native token to erc20.

**Comment by leejw51crypto** [comment]
if we use this approach, gravity not necessary?

**Comment by calvinaco** [comment]
Agree with @thomas-nguy , If a project decides to onboard Cronos, it make more sense to expect the issue party to deploy the smart contract and add the mapping before announcing or opening up their UI for it.

So those who have accidentally send their ERC20 may need this auto-conversion. But I think this should be less of a request at this point.

**Comment by yihuang** [comment]
> if we use this approach, gravity not necessary?

gravity moves the erc20 to Cronos native token, this issue is about moving the native token to Cronos erc20 token.
