### ISSUE TITLE
Updating node from testnet rc3 to something more recent crashes, be it rc4 or pre-release

### ISSUE THREAD

**Issue by tperalta82** [crypto-org-chain/cronos#461]
**Describe the bug**
Node crashes on update to latest releases

**To Reproduce**
1.  Update testnet node from rc3 to rc4 or pre-release
2. Restart Node
3. Node crashes

**Expected behavior**
Node should start with no issues

**Screenshots**
Error Message:
2:01PM INF Dialing peer address={"id":"e65199bc579ffd89d7c021c5611f9f1c97f7ff13","ip":"54.251.209.254","port":26656} module=p2p server=node
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1546ab3]

goroutine 95 [running]:
github.com/cosmos/cosmos-sdk/x/upgrade.BeginBlocker({{0x7fff6c281318, 0x16}, 0xc004c7e9f0, {0x2dae238, 0xc004ca4570}, {0x2e12c98, 0xc001606290}, 0xc004c7f590, {0x2d9c240, 0xc000ebb380}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/abci.go:38 +0x1093
github.com/cosmos/cosmos-sdk/x/upgrade.AppModule.BeginBlock(...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/upgrade/module.go:130
github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2de7528, 0xc0000520b0}, {0x2e18c20, 0xc0741b89c0}, {{0xb, 0x0}, {0xc066d49e30, 0x13}, 0x2f2620, ...}, ...}, ...)
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x218
github.com/crypto-org-chain/cronos/app.(*App).BeginBlocker(...)
        /go/src/github.com/crypto-org-chain/cronos/app/app.go:762
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc074186220, 0x20, 0x20}, {{0xb, 0x0}, {0xc066d49e30, 0x13}, 0x2f2620, {0x12ffbfe6, ...}, ...}, ...})
        /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x9dc
github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc074186220, 0x20, 0x20}, {{0xb, 0x0}, {0xc066d49e30, 0x13}, 0x2f2620, {0x12ffbfe6, ...}, ...}, ...})
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc074186220, 0x20, 0x20}, {{0xb, 0x0}, {0xc066d49e30, 0x13}, 0x2f2620, {0x12ffbfe6, ...}, ...}, ...})
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2de8408, 0xc066a27380}, {0x2dffd40, 0xc04a0edf00}, 0xc0704f01e0, {0x2e136a8, 0xc04a0ed100}, 0x2f261f)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc066a0ed64, 0x7}}, {0xc066a10180, 0x13}, 0x1, 0x2f261f, {{0xc0665f07e0, ...}, ...}, ...}, ...)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000f1e700, 0x0)
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:398 +0xb7b
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).OnStart
        /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/blockchain/v0/reactor.go:110 +0x85

**Comment by yihuang** [comment]
Thanks for reporting, the fix is actually already merged in the release branch: https://github.com/crypto-org-chain/cronos/tree/release/v0.7.x, you can have it a try.

**Comment by tperalta82** [comment]
Awesome, setup the build env and build ASAP, thank you very much

**Comment by tperalta82** [comment]
Seems to be working, thank you very much! Will close the issue!
