### ISSUE TITLE
Problem: some transaction's receipt status is wrong

### ISSUE THREAD

**Issue by jsvisa** [crypto-org-chain/cronos#462]
**Describe the bug**
Some transaction's receipt status is wrong with json-rpc's response.  

**To Reproduce**

For [this transaction](https://cronoscan.com/tx/0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5) in croscan is Failed:
<img width="1163" alt="image" src="https://user-images.githubusercontent.com/3627395/167276459-29c60446-936b-4647-9b89-27d161bac25e.png">

But from the json-rpc, it's receipt status is success:

> request
```bash
curl -XPOST  https://evm.cronos.org  -H 'content-type: application/json' -d '{ "jsonrpc":"2.0", "method":"eth_getTransactionReceipt", "params":[	"0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5" ],"id":1 }'
```

> response

```json
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "blockHash": "0xcd2dadd6e0b753ecdf2615c7a5ff742ee1c1043990f8038d1603685fe4771986",
        "blockNumber": "0x1ff088",
        "contractAddress": "0xda042ded82503f45b70ec553f41e7d208e4f29b9",
        "cumulativeGasUsed": "0x7f0e25",
        "from": "0xd5bc265568a644b567ebc7a0902f35599e73f12e",
        "gasUsed": "0x50e163",
        "logs": [
            {
                "address": "0xda042ded82503f45b70ec553f41e7d208e4f29b9",
                "topics": [
                    "0x8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e0",
                    "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "0x000000000000000000000000d5bc265568a644b567ebc7a0902f35599e73f12e"
                ],
                "data": "0x",
                "blockNumber": "0x1ff088",
                "transactionHash": "0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5",
                "transactionIndex": "0x10",
                "blockHash": "0xcd2dadd6e0b753ecdf2615c7a5ff742ee1c1043990f8038d1603685fe4771986",
                "logIndex": "0x59",
                "removed": false
            },
            {
                "address": "0xd590cc180601aecd6eeadd9b7f2b7611519544f4",
                "topics": [
                    "0x0d3648bd0f6ba80134a33ba9275ac585d9d315f0ad8355cddefde31afa28d0e9",
                    "0x0000000000000000000000005c7f8a570d578ed84e63fdfa7b1ee72deae1ae23",
                    "0x000000000000000000000000da042ded82503f45b70ec553f41e7d208e4f29b9"
                ],
                "data": "0x0000000000000000000000006f0bd16cc638d90fcc97f1f3f8e9ecc723d2fe90000000000000000000000000000000000000000000000000000000000000083c",
                "blockNumber": "0x1ff088",
                "transactionHash": "0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5",
                "transactionIndex": "0x10",
                "blockHash": "0xcd2dadd6e0b753ecdf2615c7a5ff742ee1c1043990f8038d1603685fe4771986",
                "logIndex": "0x5a",
                "removed": false
            },
            {
                "address": "0xda042ded82503f45b70ec553f41e7d208e4f29b9",
                "topics": [
                    "0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef",
                    "0x0000000000000000000000000000000000000000000000000000000000000000",
                    "0x000000000000000000000000d5bc265568a644b567ebc7a0902f35599e73f12e"
                ],
                "data": "0x000000000000000000000000000000000000000000000000016345785d8a0000",
                "blockNumber": "0x1ff088",
                "transactionHash": "0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5",
                "transactionIndex": "0x10",
                "blockHash": "0xcd2dadd6e0b753ecdf2615c7a5ff742ee1c1043990f8038d1603685fe4771986",
                "logIndex": "0x5b",
                "removed": false
            }
        ],
        "logsBloom": "0x000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000100000090000000000010000000000000000000000000000000000001200000000000000000008000000000000000100080004100000004000000000000000000000000000000004000000000000000000000000000000000080400008000000000000000000000000000000000080000000000000000000000000024000000000000000020000400000000000000008000000000000200000000000000000000c0000000000000000000000000000000000000000200000",
        "status": "0x1",
        "to": null,
        "transactionHash": "0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5",
        "transactionIndex": "0x10",
        "type": "0x0"
    }
}
```

I have tried several different RPC Servers with success. 

**This can lead to even more serious problems, as some receipt Log-based behavior(such as CEX's ERC20 deposit/withdraw) can lead to inconsistent results that break the consensus**

After some dig, I discovered that this transaction(`0x783b07bff078fe16865a4674ffbac6f5bd7827893e6610559e85ef8279cffee5`) was actually in two blocks.

1. in block [2092673](https://cronoscan.com/block/2092673): this is failed, and it's croscan's one;
2. in block [2093192](https://cronoscan.com/block/2093192): this is success, and it's json-rpc's response.

**So, This is a hash conflict or not?**

**Why croscan return the failed one**

IMHO, croscan's blockchain etl tools will use transaction hash as the primary key of the database and save only one copy.

**Expected behavior**

**Screenshots**

Cronos verion:

 - Version: v0.6.5

**Comment by yihuang** [comment]
> So, This is a hash conflict or not?

An out-of-gas contract creation transaction doesn't increase the sender's nonce, which causes the same tx hash to appear multiple times on the chain, it's fixed in 0.7.0.

**Comment by jsvisa** [comment]
@yihuang  thanks for your quick reply. 

But I can't currently run version 0.7.0, either upgrade from 0.6.5 or straight from genesis Block, is there anything instructions?

meet this issue: #317

**Comment by yihuang** [comment]
> @yihuang thanks for your quick reply.
> 
> But I can't currently run version 0.7.0, either upgrade from 0.6.5 or straight from genesis Block, is there anything instructions?
> 
> meet this issue: #317

0.7.0 is a breaking upgrade, it'll happen at block `2693800`: https://cronoscan.com/block/countdown/2693800

**Comment by jsvisa** [comment]
> 0.7.0 is a breaking upgrade, it'll happen at block `2693800`: https://cronoscan.com/block/countdown/2693800

Does that mean that after this block 2693800, I can upgrade it directly from 0.6.5? And for the old chain data, do I need to run additional repair process?

**Comment by yihuang** [comment]
> > 0.7.0 is a breaking upgrade, it'll happen at block `2693800`: https://cronoscan.com/block/countdown/2693800
> 
> Does that mean that after this block 2693800, I can upgrade it directly from 0.6.5? And for the old chain data, do I need to run additional repair process?

yes, the 0.6.5 node will shut down automatically at that block, and you should resume it with 0.7.0 binary.
The issue won't happen again after the upgrade, but the duplicated tx hashes will still exist in the old blocks.

**Comment by jsvisa** [comment]
@yihuang thanks, one more thing, Is this a case of hash collision, and how does this happen?

**Comment by yihuang** [comment]
> @yihuang thanks, one more thing, Is this a case of hash collision, and how does this happen?

not hash collision, it's just the sender's nonce is not increased, so the same tx can be send multiple times.

**Comment by jsvisa** [comment]
thanks, very much.
