### ISSUE TITLE
Problem: released goleveldb binaries has external libc dependencies

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#464]
Right now, the goreleaser built goleveldb binaries has libc runtime dependencies, and the runtime libc version must not be lower than the building one, it could break on some old linux distributions.
For example, in v0.7.0, we updated the goreleaser building docker image, which upgraded the libc version requirement, some user who can run v0.6.x successfully fail to run v0.7.0.

Proposal: build the linux/mac goleveldb binaries with the nix bundle approach too.

**Comment by yihuang** [comment]
The bundle solution is not perfect though, we already found a case where it fails to run: https://github.com/3noch/nix-bundle-exe/issues/10

**Comment by yihuang** [comment]
Another solution is use `pkgsStatic` to build static binary for Linux platform (`pkgsStatic` don't support darwin).

**Comment by yihuang** [comment]
> The bundle solution is not perfect though, we already found a case where it fails to run: [3noch/nix-bundle-exe#10](https://github.com/3noch/nix-bundle-exe/issues/10)

So I think it's best to use arx archive executable for linux, and using the nix-bundle-exe solution for mac.

**Comment by theonekeyg** [comment]
Looks like I faced this exact issue, 0.7.0 node assumes GLIBC_2.29, with 0.6.5, the requirement was only GLIBC_2.14. Is x86-64 linux build ready for builds with older libc version?

**Comment by yihuang** [comment]
> > The bundle solution is not perfect though, we already found a case where it fails to run: [3noch/nix-bundle-exe#10](https://github.com/3noch/nix-bundle-exe/issues/10)
> 
> So I think it's best to use the arx/chroot archive executable for linux, and using the nix-bundle-exe solution for mac.

after recent improvements in `nix-bundle-exe`, I believe it's good enough for our case if we stick with `netgo`.

**Comment by yihuang** [comment]
> Looks like I faced this exact issue, 0.7.0 node assumes GLIBC_2.29, with 0.6.5, the requirement was only GLIBC_2.14. Is x86-64 linux build ready for builds with older libc version?

it should be buildable on older libc, it's just the docker image we use to build the released binaries upgraded compared to `0.6.5`.
The rocksdb version is bundled in a different way with dependencies included in itself, so it's actually more portable then the goleveldb one in this case, in next version we can build all the linux versions in the same self-include way.
