### ISSUE TITLE
Error message: `ethereum tx not found in msgs`

### ISSUE THREAD

**Issue by alex-mendez-crypto** [crypto-org-chain/cronos#466]
**Describe the bug**
querying info for `0x6c73d686bc080e6c46b0f3d139a4760131a7b4a1afc364f836fb1258dd137621` returns `ethereum tx not found in msgs`

**To Reproduce**
Node responds with the mentioned error message
`curl -X POST https://evm.cronos.org -d '{ "jsonrpc":"2.0", "method":"eth_getTransactionReceipt", "params":["0x6c73d686bc080e6c46b0f3d139a4760131a7b4a1afc364f836fb1258dd137621"],"id":1 }' -H 'content-type: application/json'`
 
Transaction is found succesful on the explorer

**Expected behavior**
Should return transaction info / transaction receipt

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yihuang** [comment]
Thanks for reporting, this looks strange, the tx `0x6c73d686bc080e6c46b0f3d139a4760131a7b4a1afc364f836fb1258dd137621` get included in block twice, not for known reason, will investigate further.

**Comment by JayT106** [comment]
The TM v0.35 mempool design should avoid this issue, no duplicate transactions (same txhash) stay in the mempool.

**Comment by yihuang** [comment]
the duplicated tx issue will in: https://github.com/crypto-org-chain/cronos/issues/523
