### ISSUE TITLE
Problem: v0.7.0 (panic: unknown field "catalyst_block" in types.ChainConfig)

### ISSUE THREAD

**Issue by zjuujz8021** [crypto-org-chain/cronos#467]
**Describe the bug**
After compiling v0.7.0 and start, it panics(panic: unknown field "catalyst_block" in types.ChainConfig).

**context**

panic: unknown field "catalyst_block" in types.ChainConfig

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/codec.(*ProtoCodec).MustUnmarshalJSON(0x2defde8, {0xc000e5c900, 0x2e21320, 0xc000064dc0}, {0x2dc96a0, 0xc001046f70})
	/home/fenghang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/codec/proto_codec.go:176 +0x45
github.com/tharsis/ethermint/x/evm.AppModule.InitGenesis({{}, _, {_, _}}, {{0x2defde8, 0xc0000d6000}, {0x2e21320, 0xc000064dc0}, {{0x0, 0x0}, ...}, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/x/evm/module.go:159 +0xd0
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x2defde8, 0xc0000d6000}, {0x2e21320, 0xc000064dc0}, {{0x0, 0x0}, {0xc001126180, 0x12}, 0x0, ...}, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:320 +0x29d
github.com/crypto-org-chain/cronos/app.(*App).InitChainer(_, {{0x2defde8, 0xc0000d6000}, {0x2e21320, 0xc000064dc0}, {{0x0, 0x0}, {0xc001126180, 0x12}, 0x0, ...}, ...}, ...)
	/home/fenghang/Projects/CroScope/cronos/app/app.go:777 +0x1f2
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc0005ab040, {{0x0, 0xed91a6d90, 0x0}, {0xc001126180, 0x12}, 0xc000e5ef00, {0x3f3cc48, 0x0, 0x0}, ...})
	/home/fenghang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:62 +0x475
github.com/tendermint/tendermint/abci/client.(*localClient).InitChainSync(0xc00117f320, {{0x0, 0xed91a6d90, 0x0}, {0xc001126180, 0x12}, 0xc000e5ef00, {0x3f3cc48, 0x0, 0x0}, ...})
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:272 +0x118
github.com/tendermint/tendermint/proxy.(*appConnConsensus).InitChainSync(0x3, {{0x0, 0xed91a6d90, 0x0}, {0xc001126180, 0x12}, 0xc000e5ef00, {0x3f3cc48, 0x0, 0x0}, ...})
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:77 +0x55
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0x1ecfdd9, 0x7}}, {0xc001126180, 0x12}, 0x1, 0x0, {{0x0, ...}, ...}, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:319 +0xd98
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc0010878a0, {0x2e22bb8, 0xc00057c1a0})
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0x1ecfdd9, 0x7}}, {0xc001126180, 0x12}, 0x1, 0x0, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc0002517c0, {0x2dc7810, 0xc000527720}, 0xc000575fe0, {0x2da5ea0, 0xc0010db9c8}, 0x0, 0x0, 0xc00059e180, {0x2df0cc8, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2e36678, 0xc00053cf00}, {0x0, 0x0}, {0x2df9d48, 0xc000252300}, ...}, ...)
	/home/fenghang/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:302 +0xc9f
github.com/tharsis/ethermint/server.StartCmd.func2(0xc00131db80, {0x3f3cc48, 0x0, 0x0})
	/home/fenghang/go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:117 +0x228
github.com/spf13/cobra.(*Command).execute(0xc00131db80, {0x3f3cc48, 0x0, 0x0})
	/home/fenghang/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000e86280)
	/home/fenghang/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/fenghang/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	/home/fenghang/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc0011c9e18, 0x16})
	/home/fenghang/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
main.main()
	/home/fenghang/Projects/CroScope/cronos/cmd/cronosd/main.go:13 +0x2c

**Comment by zjuujz8021** [comment]
I follows https://cronos.org/docs/getting-started/cronos-mainnet.html#step-1-get-the-cronos-mainnet-beta-binary to init and start the node

**Comment by softwarearchaeologist** [comment]
So basically we can't use quicksync snapshots? Because if I need to build a node from scratch I need to sync it to the hardfork blockheight first thereby defeating the purpose of the snapshots. If I use the snapshot as is the node won't start as it won't agree on the app hash.

**Comment by yihuang** [comment]
> So basically we can't use quicksync snapshots? Because if I need to build a node from scratch I need to sync it to the hardfork blockheight first thereby defeating the purpose of the snapshots. If I use the snapshot as is the node won't start as it won't agree on the app hash.

you can use a snapshot created after the v0.7.0 upgrade.
