### ISSUE TITLE
update to 0.7 error

### ISSUE THREAD

**Issue by qinxg** [crypto-org-chain/cronos#480]
used

https://github.com/crypto-org-chain/cronos/releases/download/v0.7.0/cronos_0.7.0_Linux_x86_64.tar.gz

**app.toml Modified Finish** 

[evm]

# Tracer defines the 'vm.Tracer' type that the EVM will use when the node is run in
# debug mode. To enable tracing use the '--trace' flag when starting your node.
# Valid types are: json|struct|access_list|markdown
tracer = ""
max-tx-gas-wanted = 500000

###############################################################################
###############################################################################

[json-rpc]

# Enable defines if the gRPC server should be enabled.
enable = true

# Address defines the EVM RPC HTTP server address to bind to.
address = "0.0.0.0:8545"

# Address defines the EVM WebSocket server address to bind to.
ws-address = "0.0.0.0:8546"

# API defines a list of JSON-RPC namespaces that should be enabled
# Example: "eth,txpool,personal,net,debug,web3"
api = "eth,txpool,personal,net,debug,web3"

# GasCap sets a cap on gas that can be used in eth_call/estimateGas (0=infinite). Default: 25,000,000.
gas-cap = 25000000

# FilterCap sets the global cap for total number of filters that can be created
filter-cap = 200

feehistory-cap = 100
logs-cap = 10000
block-range-cap = 10000
http-timeout = "30s"
http-idle-timeout = "120s"

**run logs..**

May 18 01:26:36 ip-172-31-6-231 systemd[1]: Started cronosd.
May 18 01:26:36 ip-172-31-6-231 cronosd[926]: 1:26AM INF Unlocking keyring
May 18 01:26:36 ip-172-31-6-231 cronosd[926]: 1:26AM INF starting ABCI with Tendermint
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting multiAppConn service impl=multiAppConn module=proxy server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting localClient service connection=query impl=localClient module=abci-client server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting localClient service connection=snapshot impl=localClient module=abci-client server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting localClient service connection=mempool impl=localClient module=abci-client server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting localClient service connection=consensus impl=localClient module=abci-client server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting EventBus service impl=EventBus module=events server=node
May 18 01:26:45 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting PubSub service impl=PubSub module=pubsub server=node
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: 1:26AM INF Starting IndexerService service impl=IndexerService module=txindex server=node
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: 1:26AM INF ABCI Handshake App Info hash="\f\\�w%y<橴���4;��O�E�\x00���٫Fp�W\f" height=2639286 module=consensus protocol-version=0 server=node software-version=0.7.0
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: 1:26AM INF ABCI Replay Blocks appHeight=2639286 module=consensus server=node stateHeight=2639286 storeHeight=2639287
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: 1:26AM INF Replay last block using real app module=consensus server=node
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: panic: UnmarshalJSON cannot decode empty bytes
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: goroutine 1 [running]:
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/cosmos/cosmos-sdk/x/params/types.Subspace.Get({{0x2e12c98, 0xc0012c1d20}, 0xc000011990, {0x2dae238, 0xc0088cb600}, {0x2dae288, 0xc0088cb6b0}, {0xc000f76f60, 0x9, 0x21}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/params/types/subspace.go:109 +0x319
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/cosmos/cosmos-sdk/x/params/types.Subspace.GetParamSet({{0x2e12c98, 0xc0012c1d20}, 0xc000011990, {0x2dae238, 0xc0088cb600}, {0x2dae288, 0xc0088cb6b0}, {0xc000f76f60, 0x9, 0x21}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/x/params/types/subspace.go:222 +0x145
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/x/feemarket/keeper.Keeper.GetParams(...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/x/feemarket/keeper/params.go:11
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/x/feemarket/keeper.Keeper.CalculateBaseFee({{0x2e12c98, 0xc0012c1d20}, {0x2dae238, 0xc0088cb690}, {{0x2e12c98, 0xc0012c1d20}, 0xc000011990, {0x2dae238, 0xc0088cb600}, {0x2dae288, ...}, ...}}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/x/feemarket/keeper/eip1559.go:17 +0x125
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/x/feemarket/keeper.(*Keeper).BeginBlock(_, {{0x2de7528, 0xc000052060}, {0x2e18c20, 0xc010105240}, {{0xb, 0x0}, {0xc007c08a20, 0x12}, 0x2845b7, ...}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/x/feemarket/keeper/abci.go:14 +0xd8
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/x/feemarket.AppModule.BeginBlock(...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/x/feemarket/module.go:139
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/cosmos/cosmos-sdk/types/module.(*Manager).BeginBlock(_, {{0x2de7528, 0xc000052060}, {0x2e18c20, 0xc010105240}, {{0xb, 0x0}, {0xc007c08a20, 0x12}, 0x2845b7, ...}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/types/module/module.go:479 +0x218
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/crypto-org-chain/cronos/app.(*App).BeginBlocker(...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/src/github.com/crypto-org-chain/cronos/app/app.go:762
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).BeginBlock(_, {{0xc010097ea0, 0x20, 0x20}, {{0xb, 0x0}, {0xc007c08a20, 0x12}, 0x2845b7, {0x2c40768a, ...}, ...}, ...})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/baseapp/abci.go:194 +0x9dc
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/abci/client.(*localClient).BeginBlockSync(_, {{0xc010097ea0, 0x20, 0x20}, {{0xb, 0x0}, {0xc007c08a20, 0x12}, 0x2845b7, {0x2c40768a, ...}, ...}, ...})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/abci/client/local_client.go:280 +0x118
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/proxy.(*appConnConsensus).BeginBlockSync(_, {{0xc010097ea0, 0x20, 0x20}, {{0xb, 0x0}, {0xc007c08a20, 0x12}, 0x2845b7, {0x2c40768a, ...}, ...}, ...})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/proxy/app_conn.go:81 +0x55
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/state.execBlockOnProxyApp({0x2de8408, 0xc00383e780}, {0x2dffd40, 0xc008308110}, 0xc000eaab40, {0x2e136a8, 0xc0082af320}, 0x2845b6)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:307 +0x3dd
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x0}, {0xc0082ad910, 0x7}}, {0xc007c080c0, 0x12}, 0x1, 0x2845b6, {{0xc00bd6c0c0, ...}, ...}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/state/execution.go:140 +0x171
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlock(_, {{{0xb, 0x0}, {0xc0082ad910, 0x7}}, {0xc007c080c0, 0x12}, 0x1, 0x2845b6, {{0xc00bd6c0c0, ...}, ...}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:503 +0x23c
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x0}, {0xc0082ad910, 0x7}}, {0xc007c080c0, 0x12}, 0x1, 0x2845b6, {{0xc00bd6c0c0, ...}, ...}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:416 +0x7ae
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc06ad8d8a0, {0x2e1a4b8, 0xc019d01040})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/consensus/replay.go:268 +0x3c8
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x0}, {0xc0082ad910, 0x7}}, {0xc007c080c0, 0x12}, 0x1, 0x2845b6, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:325 +0x1b8
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tendermint/tendermint/node.NewNode(0xc0010fb900, {0x2dbef50, 0xc00017db80}, 0xc000d6b7e0, {0x2d9d500, 0xc00bd74dc8}, 0x0, 0x0, 0xc000d6b9c0, {0x2de8408, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/tendermint/tendermint@v0.34.19/node/node.go:733 +0x578
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/server.startInProcess(_, {{0x0, 0x0, 0x0}, {0x2e2df78, 0xc0001d8e40}, {0x0, 0x0}, {0x2df1648, 0xc0012c1d20}, ...}, ...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:302 +0xc9f
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/tharsis/ethermint/server.StartCmd.func2(0xc0001e6a00, {0xc000dc5f60, 0x0, 0x2})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/crypto-org-chain/ethermint@v0.10.0-alpha1-cronos-9/server/start.go:117 +0x228
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/spf13/cobra.(*Command).execute(0xc0001e6a00, {0xc000dc5f40, 0x2, 0x2})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:856 +0x60e
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/spf13/cobra.(*Command).ExecuteC(0xc00051e000)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3bc
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/spf13/cobra.(*Command).Execute(...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/spf13/cobra.(*Command).ExecuteContext(...)
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:895
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: github.com/cosmos/cosmos-sdk/server/cmd.Execute(0x0, {0xc0012ce630, 0x14})
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.45.4/server/cmd/execute.go:36 +0x1eb
May 18 01:26:56 ip-172-31-6-231 cronosd[926]: main.main()
May 18 01:26:56 ip-172-31-6-231 cronosd[926]:         /go/src/github.com/crypto-org-chain/cronos/cmd/cronosd/main.go:13 +0x2c
May 18 01:26:56 ip-172-31-6-231 systemd[1]: cronosd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
May 18 01:26:56 ip-172-31-6-231 systemd[1]: cronosd.service: Failed with result 'exit-code'.
May 18 01:27:06 ip-172-31-6-231 systemd[1]: cronosd.service: Scheduled restart job, restart counter is at 2.
May 18 01:27:06 ip-172-31-6-231 systemd[1]: Stopped cronosd.
May 18 01:27:06 ip-172-31-6-231 systemd[1]: Started cronosd.

**Comment by yihuang** [comment]
block `2693800` is when `v0.7.0` upgrade happened, you need to use `v0.6.x` binaries to sync before that, and upgrade to `v0.7.0` after that.
Or setup [cosmovisor](https://github.com/cosmos/cosmos-sdk/tree/release/v0.45.x/cosmovisor#cosmosvisor-quick-start), which will do the switch automatically.
