### ISSUE TITLE
Problem: tx receipt missing in our self-hosted node

### ISSUE THREAD

**Issue by jsvisa** [crypto-org-chain/cronos#482]
**Describe the bug**

We took a closer look at historical tx-receipts, for those transaction receipts are missing in our self-hosted node, and some exist in https://evm.cronos.org, but the others is also not found.

See the csv file in detail:

- totally of 458 transactions
- `our_receipt/evm_receipt` are response of `eth_getTransactionReceipt` RPC

[evm_cronos.csv.gz](https://github.com/crypto-org-chain/cronos/files/8713764/evm_cronos.csv.gz)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yihuang** [comment]
which `0.6.x` version do you use to sync the blocks before `v0.7.0` upgrade?
And is there difference in the raw tx result compared with the public node. url: `https://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%27$ETH_TX_HASH%27%22`

**Comment by samuel-tay** [comment]
Hi, I just came across this issue too with varying results across rocksdb and goleveldb nodes.

I also came across #523 and #548 so just wondering if this is fixed and if the command reindex-duplicated-tx can be used?

Thanks!

**Comment by yihuang** [comment]
public rpc node has run `reindex-duplicated-tx` and `patch-unlucky-tx`, so they'll have some more txs than a normal synced node.

**Comment by yihuang** [comment]
I think this is fixed now.

**Comment by jsvisa** [comment]
thanks
