### ISSUE TITLE
Problem: broken CLI commands

### ISSUE THREAD

**Issue by tomtau** [crypto-org-chain/cronos#491]
for example: https://github.com/crypto-org-chain/cronos/issues/471

but I assume there may be more SDK-related tx commands that don't work? perhaps good to remove them?

**Comment by yihuang** [comment]
`create-vesting-account` is fixed after upgrading to 0.46.

**Comment by yihuang** [comment]
I'll close for now, feel free to reopen if there are other cli commands don't work.
