### ISSUE TITLE
ethermint version

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#504]
Hi, I noticed that cronos use ethermint v0.6.1, and the latest version is v0.15.0 why not use the latest release?

**Comment by JayT106** [comment]
the latest Cronos release is using ethermint v0.10, and there are some breaking changes after v0.11. It will require some feature integration and a network upgrade.

**Comment by yihuang** [comment]
> Hi, I noticed that cronos use ethermint v0.6.1, and the latest version is v0.15.0 why not use the latest release?

Current cronos main use ethermint main. For V0.7.0, it's to avoid bringing more breaking changes during testing phase.
