### ISSUE TITLE
Problem: EIP712 support is not tested in integration tests

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#506]
EIP712 support in ethermint allows sending cosmos native tx through web3 API. good to test it in integration test.

**Comment by yihuang** [comment]
example: https://www.npmjs.com/package/@tharsis/eip712

**Comment by mmsqe** [comment]
> example: https://www.npmjs.com/package/@tharsis/eip712

not sure if I miss config, but I see no [feePayer](https://github.com/crypto-org-chain/cronos/blob/03fa9dfd57b661e2a94deefbb5789c30ffe34880/third_party/proto/ethermint/types/v1/web3.proto#L20) error when debug eip712 tx:
```'signature verification failed; please verify account number (0) and chain-id (cronos_777-1): no feePayer on ExtensionOptionsWeb3Tx: unknown extension options [evmos/ethermint@v0.6.1-0.20220629170828-b7878fd6f125/app/ante/eip712.go:207]: unauthorized'```

**Comment by yihuang** [comment]
You need to specify `FeePayer` in the `ExtensionOptionsWeb3Tx` struct.

**Comment by mmsqe** [comment]
> You need to specify `FeePayer` in the `ExtensionOptionsWeb3Tx` struct, and the other fields: https://github.com/evmos/ethermint/blob/main/types/web3.pb.go#L26

should already included in [msg](https://gist.github.com/mmsqe/49aa1c42ad254abc352a24bf9a81206f#file-raw-msg-json-L1053), same as sender

**Comment by yihuang** [comment]
closed by https://github.com/crypto-org-chain/cronos/pull/625
