### ISSUE TITLE
dev network pre-funded account

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#507]
In order to run a local dev network, I followed this doc https://cronos.org/docs/getting-started/local-devnet.html#option-2-using-shell-script-2 and run this [script](https://raw.githubusercontent.com/crypto-org-chain/cronos-docs/master/docs/getting-started/assets/init_cronos_chain/init.sh)

There's some prefunded account, but how can I get the account's private key so I can import it to metamask to test?

**Comment by yihuang** [comment]
it generated an account on the fly, you should be able to find it in the test keyring.
