### ISSUE TITLE
Problem: mac binaries are not signed with apple developer certificates

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#510]
ref: https://localazy.com/blog/how-to-automatically-sign-macos-apps-using-github-actions

### What about the reproducibility

The stuff built before the code signing step is still reproducible, in theory, the user can check the signature against the unsigned artifacts.

```
$ codesign -d -vvv ./result/bin/cronosd 2>&1 | grep CDHash
CandidateCDHash sha256=9ca467fa78104154c7cfb578eab7f0f8143865bc
CandidateCDHashFull sha256=9ca467fa78104154c7cfb578eab7f0f8143865bce7341ebd163964e8cf586b15
CDHash=9ca467fa78104154c7cfb578eab7f0f8143865bc
```

Users can build a binary locally, and compare the cdhash against the signed one.

**Comment by leejw51crypto** [comment]
to sign it, private key is necessary.
how about for mac only, signing manually?
