### ISSUE TITLE
Problem: No integration tests for IBC timeout/failure

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#514]
Needs to write some integration tests to verify the refund behavior in case of IBC packet time out or aknowledgement failure

**Comment by tomtau** [comment]
is this a duplicate of https://github.com/crypto-org-chain/cronos/issues/398 ?

**Comment by thomas-nguy** [comment]
Yes but  #398 is confusing (see my comment). 

`send_to_ethereum` and `send_to_ibc` uses two completely different flow. 

This ticket focus only on the IBC + middleware, but we can extend the scope to test also the evm-hook `send_to_ibc` to have a complete end to end flow (even though it is worth to test to command line separately as well)

**Comment by yihuang** [comment]
fixed by: https://github.com/crypto-org-chain/cronos/pull/613
