### ISSUE TITLE
wrong Block.Header.AppHash with latest snapshot

### ISSUE THREAD

**Issue by sonderangebot10** [crypto-org-chain/cronos#536]
**Describe the bug**
While following this [guide](https://cronos.org/docs/getting-started/cronos-mainnet.html#optional-step-4-quicksync) after the 4th step I am getting a `wrong Block.Header.AppHash` error.

`4:14PM INF indexed block height=3052727 module=txindex server=node
panic: Failed to process committed block (3052728:2A36C330A4FB911B79A9474D2D4226BFEF5B7F58061EE29097B6725CC667E4C7): wrong Block.Header.AppHash.  Expected 094EB86FA2A221B2EF60A6858EB03F0DF413F0D79529A1E3881A0206A5B4C7A0, got 84FFE1C95D9F8EFF6D1AEA58FDA27CF35470D64B7A391D596FAAE7DDA8B76E2E`

**To Reproduce**
Follow throughout the whole steps in the given guide. 
Running the node without a snapshot succeeds and current block increases from 0 to beyond.
After downloading the snapshot (cronosmainnet_25-1-pruned) the is a hash mismatch.

I am running a build version 0.6.5 of cronosd. Tried once again with a previous snapshot - same issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/37372712/171908046-20b43e15-f473-4af0-a38c-9328f60b56e1.png)

**Comment by yihuang** [comment]
did you run the `v0.7.0` binary?

**Comment by sonderangebot10** [comment]
![image](https://user-images.githubusercontent.com/37372712/171914965-f84eee7f-8bed-4b54-917b-b607461e853a.png)

I've tried both `0.7.0` and `0.6.5` - same outcome. app.toml updated accordingly with `v0.7.0`

**Comment by yihuang** [comment]
> ![image](https://user-images.githubusercontent.com/37372712/171914965-f84eee7f-8bed-4b54-917b-b607461e853a.png)
> 
> I've tried both `0.7.0` and `0.6.5` - same outcome. app.toml updated accordingly with `v0.7.0`

the most important is which version do you run at first, because after you enter the situation of app hash mismatch, it doesn't recover if you switch to correct binary, you need to sync again with the correct one.

**Comment by sonderangebot10** [comment]
So just to get it right - I need to download the snapshot and then run `v0.7.0` without running it on 0th block? And it should work fine this way?

**Comment by yihuang** [comment]
> So just to get it right - I need to download the snapshot and then run `v0.7.0` without running it on 0th block? And it should work fine this way?

yes

**Comment by sonderangebot10** [comment]
Thanks! I though I had tried it this way, but I tried again and now it works :,)
