### ISSUE TITLE
Problem: cancel gravity transfer integration test fail accationally

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#553]
https://github.com/crypto-org-chain/cronos/runs/6878397070?check_suite_focus=true

because the cancel call could fail occasionally because the transfer is already included in a batch.
@thomas-nguy any idea how to assert this more deterministically?

**Comment by thomas-nguy** [comment]
batch is created every 10 blocks.

- one solution is to increase block production time and make sure that send_to_eth tx in inserted in block 10X + 1 but this is very tricky to do
- another solution is to do send_to_eth and cancel_batch in batch transaction but we won't be able to verify the amount deducted and refunded

**Comment by thomas-nguy** [comment]
I guess if it keeps failing, we will opt for solution 2?

**Comment by yihuang** [comment]
but do it in batch, you can't get the packet id?

**Comment by thomas-nguy** [comment]
yeah the txId is generated in order, if tests run sequentially within test_gravity or clean the state before each test, we will be able to get the id deterministically but is it the case in python?

**Comment by yihuang** [comment]
> yeah the txId is generated in order, if tests run sequentially within test_gravity or clean the state before each test, we will be able to get the id deterministically but is it the case in python?

I see, if you fetch the id at the beginning and increase by one, it should work.
