### ISSUE TITLE
Prometheus metrics not working

### ISSUE THREAD

**Issue by sonderangebot10** [crypto-org-chain/cronos#565]
Hello,

When changing the `config.toml` file to include Prometheus metrics nothing changes - no port is opened on the machine.
My settings:

```
[instrumentation]

# When true, Prometheus metrics are served under /metrics on
# PrometheusListenAddr.
# Check out the documentation for the list of available metrics.
prometheus = true

# Address to listen for Prometheus collector(s) connections
prometheus_listen_addr = "0.0.0.0:26660"

# Maximum number of simultaneous connections.
# If you want to accept a larger number than the default, make sure
# you increase your OS limits.
# 0 - unlimited.
max_open_connections = 3

# Instrumentation namespace
namespace = "tendermint"

**Comment by mmsqe** [comment]
@sonderangebot10 any result from `http://localhost:26660/metrics?format={text|prometheus}`, just try enable prometheus, works normal
<img width="858" alt="Screenshot 2022-07-18 at 6 12 53 PM" src="https://user-images.githubusercontent.com/2867936/179491206-07c2676b-f932-47df-8795-653f5e8d5fb1.png">

**Comment by Goldmindsx** [comment]
> Hello,
> 
> When changing the `config.toml` file to include Prometheus metrics nothing changes - no port is opened on the machine. My settings:
> 
> ```
> [instrumentation]
> 
> # When true, Prometheus metrics are served under /metrics on
> # PrometheusListenAddr.
> # Check out the documentation for the list of available metrics.
> prometheus = true
> 
> # Address to listen for Prometheus collector(s) connections
> prometheus_listen_addr = "0.0.0.0:26660"
> 
> # Maximum number of simultaneous connections.
> # If you want to accept a larger number than the default, make sure
> # you increase your OS limits.
> # 0 - unlimited.
> max_open_connections = 3
> 
> # Instrumentation namespace
> namespace = "tendermint" 
> ```


talk to crypto org via live chat https://direct.lc.chat/14345826/
