### ISSUE TITLE
Problem: unlucky tx patch is not run along with syncing

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#566]
Currently the `patch-unlucky-tx` command need to be run after a normal sync, it'd be better if it's run along with syncing automatically.

**Comment by Goldmindsx** [comment]
> Currently the `patch-unlucky-tx` command need to be run after a normal sync, it'd be better if it's run along with syncing automatically.


talk to crypto org via live chat https://direct.lc.chat/14345826/

**Comment by yihuang** [comment]
The patch process need to hold the db, impossible to run along with syncing, better to kept as a standalone command.
The the patch process could be speedup a lot with recent added export feature: https://github.com/crypto-org-chain/cronos/pull/571, where we can share the export result, then patch from it is much faster than replay the tx on the fly.
Closing now.
