### ISSUE TITLE
Problem: `patch-unlucky-tx` don't handle duplicated tx correctly

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#576]
When `patch-unlucky-tx` try to reindex a failed tx, it should check if there's a successful one already, otherwise, it'll override a successful one with a failed one.

An example case:

- `1489403 115`, exceed block gas limit
- `1489412 39`, success, override indexer
after patch-unlucky-tx:
- `1489403 115`, replay with a failed result, override indexer
reindex-duplicated-tx:
figure that 1489412 39 need re-override.

while on production, it’s success already

**Comment by mmsqe** [comment]
do we disable concurrency and record patched block height with tnx hash + index as key to check check with?

**Comment by yihuang** [comment]
Previous logic:
1. iterate blocks to find exceed block gas limit transactions
2. for v0.6 blocks, replay the tx to get result
3. for v0.7 blocks, just add some events to it
4. update block results and reindex the tx

The step 1 should be changed to:
1. a) iterate blocks to find exceed block gas limit transactions
    b) if the cosmos tx hash exists in tx indexer and status is successful, skip
