### ISSUE TITLE
Problem: does the problem of TX missing been solved after upgrade to v0.7.1-rc0

### ISSUE THREAD

**Issue by jsvisa** [crypto-org-chain/cronos#579]
**Describe the bug**
I've upgraded the Cronos to https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.1-rc0 and `reindex-duplicated-tx`, but the issue of tx missing happened again: 

this tx was missed in my node https://cronoscan.com/tx/0x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431

So does the tx missing issue has been completely solved?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yihuang** [comment]
> So does the tx missing issue has been completely solved?

yes, as far as we know.

> but the issue of tx missing happened again

May I know if the whole block is missing or only the specific tx?

**Comment by jsvisa** [comment]
> May I know if the whole block is missing or only the specific tx? And does this query return anything: http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431%27%22

The block exists, but the  tx not found in the transaction list:

```
In [20]: w3.eth.get_block(3631518)
Out[20]:
AttributeDict({'baseFeePerGas': 4964575214552,
 'difficulty': 0,
 'extraData': HexBytes('0x'),
 'gasLimit': 20000000,
 'gasUsed': 14854506,
 'hash': HexBytes('0xcc632028a75e0fa9e25a77eb6ac475ac81c3e9814f56b17e64ba3aa7bb8805bb'),
 'logsBloom': HexBytes('0x18300020000400000000004080000000100000000000c000000046000000080001008002000002001000080c0000000600000000004000820000200800201000020504000000000000010008800400602500100100004000a0000005800800000a1000000000000000200000008801000000000200101400002422100000020080000100000080040000030000800000400080014000008800010043000002800a000000000401000a004041020000010000d0181102000000004028001040000000202220001402000061600402021000040000004000100000280000040c000111200900008000009034080100040100300010050008500020304400000010'),
 'miner': '0x968b38589cC2c2dD4b42986643a69f0FF60D8B96',
 'mixHash': HexBytes('0x0000000000000000000000000000000000000000000000000000000000000000'),
 'nonce': HexBytes('0x0000000000000000'),
 'number': 3631518,
 'parentHash': HexBytes('0xcf66c26a8d33a76c0b92353de769f0989ba84627f5f9c4de0b07c6330d8077fc'),
 'receiptsRoot': HexBytes('0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421'),
 'sha3Uncles': HexBytes('0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347'),
 'size': 39566,
 'stateRoot': HexBytes('0x0539e91f9a6f92aacaea727c0ace4eb52df7b602f2b0bff97027764d41e5f2d5'),
 'timestamp': 1657495869,
 'totalDifficulty': 0,
 'transactions': [HexBytes('0xaaa001cb849f125e256df84ffdf8f75b90d6816647868d7bf7012de8b4d0eeb4'),
  HexBytes('0xa55bc86bd337266fbdd626640a2bbd52244dc97d63e0157bc49ad65509e813c5'),
  HexBytes('0x162f7d099874f2474043951888c5cbcb909a61aad1f48f142390c6af7f17dd38'),
  HexBytes('0x06de2341bf4321f67961101d4e79318b428990c38fb1ffd927087947da28aa51'),
  HexBytes('0x3c41082f294a795f2152abbeb4dfd0b5aafaf96704cfb689768c083dc6276af2'),
  HexBytes('0x69efe283822a51ae8a3ca35ba54c866dab05cbaf69c0e6fc0956ba0fd993aee5'),
  HexBytes('0x8899b38dfc04110dd626c93b3410a1e577957380537e945054d307f0d31a3be0'),
  HexBytes('0xa34d84b8eb24c57a9dbcd4205de48bc66d51be45268ff82ed335c107695ecdbe'),
  HexBytes('0x2dcb848dc8fa91a523f0fbb24053764b8cc41ef691e79cd58ca35356116e2719'),
  HexBytes('0x4c7029cd64a18c8840095e79eb0abe737baf99c94a2ad022ce1c24b1be8409d3'),
  HexBytes('0x5f40d1a11e5ceda7b4514fcbfee46e75070991c5038ce18cc6dea4b033b3a3a5'),
  HexBytes('0xc23c8b7d84f95777ff2abff3e88a8d8436002d891752e32998d68cb4e2bb02de'),
  HexBytes('0x5c76e24935b8690c0668ef1d4e389b44d9745ae14791d92a6c34538ad2ffa90d'),
  HexBytes('0xa5d1c47fb5f6a5d44fb351ea46ee0f56d181ba21a88199cd718a622130bae953'),
  HexBytes('0x6d52ecb715d9d1eb9ef16b9f9b34624af0f73e4907a07f958ffa37518b0ef6f6'),
  HexBytes('0x2e22bdd49eb5063f4046e3c71b1646b55f04bb772ac1f74b1bca44e60c4cec54'),
  HexBytes('0x5a7d14639dc97ef62516db6f8c959af4e6563ca5a37d5a209099eeb5be0c163e'),
  HexBytes('0xe4125b3441c9b3348e3fdd9050954257fc62c3464a30b55284c4ddf84eb5009b'),
  HexBytes('0xd45a1b2bfb29a5a1f92a7ec8e95c355ce1f9f3ae58868c2d6d3d22dfc5bbc9b7'),
  HexBytes('0xada79a94c767446b98e942cad32ad7f488cb503bacaa8b0250a4ecc57e499342'),
  HexBytes('0xc9599bab470f3b2936bf97e3d32ccbc533d264dc48afdf09e2e6dd9fd6ae2cb9'),
  HexBytes('0xb8b5a9831f25a05448b4389c0832f75d90555f7cd583331e68993cf62340058f'),
  HexBytes('0xaa9250aa9456fd9b98e7d8f7fd16ac11554391023097de5d9f99c6b09021faeb'),
  HexBytes('0x3ee38a52bd8ef2a65a303bedf236c3f85175d29d5f333a65899deb575ed6eb96'),
  HexBytes('0xdc96821c38ab090782aaf012f53afdb07afa0b845b5232d0c832e92b63ea0125'),
  HexBytes('0x1f48de769e522dc829cc20e6fb9b1ecc9ba5aa08eb0e8ca61b134d05926cfc35'),
  HexBytes('0xb0d279fda66909e6260dc2a44b4ffbbda444bcb8a95035e5b099527cf4b1aa19'),
  HexBytes('0x4d6818d0b3b8f9da22cc26424c42ffc900d9ba7de8b5d1a5f57f5276ff44ef7b'),
  HexBytes('0x91c159c5356580af211eb43709f3fe56633a2cdcfd8811d6b9f27510ac4b1db6'),
  HexBytes('0x5fa2b58596f7867af1f29ab624a03057a48deff91a52f2d47c4dd2ca51772253'),
  HexBytes('0x776ebdaaff1955a0bfc1436c1e1a2d15d8d9ac76d79e8e8ba66d08b93db22704'),
  HexBytes('0x4bbe87d8cd65776ef4abe92ab5b14f5b63f4cb0dd06914c3a64bad40a983175b'),
  HexBytes('0x45d4829f60245a5514cced37d57ecbdc0e96f6acbdc4f5f78bc3a3f757c8f774'),
  HexBytes('0x7319961a6d9ad5447acb0473764c4c2cea5b4ddb107b7eab1c45ce69ec4838fa'),
  HexBytes('0xa7114fd245fcb276cc8980c50bb24b7e8af794f0e325fd50ec42802798d3c0ba'),
  HexBytes('0x20a2cdc417108b3eb0a9913f89285c859112913e998f3adcc51f74cd2b8fc5be'),
  HexBytes('0x03abbde6e844b646e0d5889ccb95194c28c3fb3db3046334be22dc67ff1b7056'),
  HexBytes('0x45e47e470895b3c7856dbca65403e26af12a0beb0bd2bfff2b62be6ee413d365'),
  HexBytes('0x395d2c941afcc43e5ea1cc4a7e2a6f869491791b7da9b9c45fba2240586de405'),
  HexBytes('0x4e8802c44402bec761c2e80e4a7a8612a9574fdea1fe469c6edadf99ca7d1970'),
  HexBytes('0x860b75d3e2c0dbf7a0f2973bb7393b0d2b61b5a11b5285c42b91f144085c9627'),
  HexBytes('0x3e09d3d5061465b4cc33184630d7732ecd9c26c7460b04275da707db1680e8ae')],
 'transactionsRoot': HexBytes('0x7dcf44fb4d87ccab780d3c8b8c606b552fc5a55c7f3d1e1fddf5a1503c777877'),
 'uncles': []})
```

> And does this query return anything: 

```
curl "http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431%27%22"
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "txs": [],
    "total_count": "0"
  }
}
```

**Comment by yihuang** [comment]
I guess this request doesn't return anything as well? `https://rpc-cronos.crypto.org/tx?hash=0xF5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318`

**Comment by jsvisa** [comment]
> I guess this request doesn't return anything as well? `http://localhost:26657/tx?hash=0xF5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318`

```
curl http://localhost:26657/tx?hash=0xF5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318
{
  "jsonrpc": "2.0",
  "id": "",
  "error": {
    "code": -32603,
    "message": "Internal error",
    "data": "Tx (F5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318) not found"
  }
}
```

**Comment by jsvisa** [comment]
BTW, https://cronoscan.com/tx/0xF5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318 this tx also does not exists, where does it from, and what does this mean?

**Comment by yihuang** [comment]
> BTW, https://cronoscan.com/tx/0xF5FA03E0DBCCE6B3AA0CC8DBA5F51A12977CA6FFF57321D73A21C1C09BDC2318 this tx also does not exists, where does it from, and what does this mean?

this is the cosmos tx hash corresponding to the eth tx.

**Comment by yihuang** [comment]
http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270xa34d84b8eb24c57a9dbcd4205de48bc66d51be45268ff82ed335c107695ecdbe%27%22

So what does this query returns there?
It seems on your node the 7eth tx hash of the block is different from normal nodes, which is very strange.

**Comment by jsvisa** [comment]
> http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270xa34d84b8eb24c57a9dbcd4205de48bc66d51be45268ff82ed335c107695ecdbe%27%22
> 
> So what does this query returns there? It seems on your node the 7th(0 based) tx hash of the block is different from normal nodes, which is very strange.

```
curl "http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270xa34d84b8eb24c57a9dbcd4205de48bc66d51be45268ff82ed335c107695ecdbe%27%22"
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "txs": [],
    "total_count": "0"
  }
}
```

**Comment by jsvisa** [comment]
> http://localhost:26657/block?height=3631518

[3631518.json.zip](https://github.com/crypto-org-chain/cronos/files/9082267/3631518.json.zip)

> http://localhost:26657/block_results?height=3631518

```json
{
  "jsonrpc": "2.0",
  "id": "",
  "result": {
    "height": "3631518",
    "results": {
      "deliver_tx": null,
      "end_block": {
        "validator_updates": null
      },
      "begin_block": {}
    }
  }
}
```

**Comment by yihuang** [comment]
> I seem to understand the possible cause, I have Polygon and Cronos deployed on the same machine, there may be a conflict on the cosmos listening port 26657?

Yeah, that's highly likely the issue

**Comment by jsvisa** [comment]
After switching the port from 26657 to Cronos' port, the response of 

> http://localhost:26657/tx_search?query=%22ethereum_tx.ethereumTxHash=%270x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431%27%22 

[0x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431.json.zip](https://github.com/crypto-org-chain/cronos/files/9082419/0x58c0179ac7ab5517604ac3519694785510abdf7be86ec28eeeac830813f75431.json.zip)

**Comment by yihuang** [comment]
looks fine now.

**Comment by jsvisa** [comment]
so, what's the root cause of this tx missing?

**Comment by yihuang** [comment]
> so, what's the root cause of this tx missing?

port conflict, does it still missing after fixing the port number?

**Comment by jsvisa** [comment]
> port conflict, does it still missing after fixing the port number?

yeah.

**Comment by yihuang** [comment]
> > http://localhost:26657/block?height=3631518
> 
> [3631518.json.zip](https://github.com/crypto-org-chain/cronos/files/9082267/3631518.json.zip)
> 
> > http://localhost:26657/block_results?height=3631518
> 
> ```json
> {
>   "jsonrpc": "2.0",
>   "id": "",
>   "result": {
>     "height": "3631518",
>     "results": {
>       "deliver_tx": null,
>       "end_block": {
>         "validator_updates": null
>       },
>       "begin_block": {}
>     }
>   }
> }
> ```

With correct port, is the block_result still empty?

**Comment by jsvisa** [comment]
block height: 

[3631518.json.zip](https://github.com/crypto-org-chain/cronos/files/9091641/3631518.json.zip)

block results:
[block_result_3631518.json.zip](https://github.com/crypto-org-chain/cronos/files/9091642/block_result_3631518.json.zip)

**Comment by yihuang** [comment]
Same issue as here: https://github.com/evmos/ethermint/pull/1176, will be fixed after we backport a non-breaking version to `v0.7.1`.

**Comment by yihuang** [comment]
fixed by: https://github.com/crypto-org-chain/cronos/pull/584
