### ISSUE TITLE
Problem: no integration test for ibc refund case

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#606]
In case the packet cannot be transmitted such as time out or packet aknowledgement error. the transfer amount should be refunded to users and ibc middleware convert back those coins to crc20.

There are missing integration tests for those scenarios

**Comment by yihuang** [comment]
seems duplicated: https://github.com/crypto-org-chain/cronos/issues/514

**Comment by thomas-nguy** [comment]
yes
