### ISSUE TITLE
Problem: Include evm_log_handlers errors in ethereum logs

### ISSUE THREAD

**Issue by thomas-nguy** [crypto-org-chain/cronos#61]
The evm hook allows us to process logs from an ethereum transaction. 

I would be nice that the details of the `evm_log_handlers.go` errors would also appear on eth logs or returned to the client so that he would be aware why the transaction fails

**Comment by yihuang** [comment]
The `"internal"` error message has been fixed by this PR: https://github.com/tharsis/ethermint/pull/786.
In 0.7.0, the client should see `"failed to execute post processing"` if tx failed in hooks.
