### ISSUE TITLE
can not find v0.7.0-hotfix source code 

### ISSUE THREAD

**Issue by zjuujz8021** [crypto-org-chain/cronos#617]
error: UPGRADE "v0.7.0-hotfix" NEEDED at height: 3982500
but where can I get the source code of v0.7.0-hotfix?
"Source code" here in https://github.com/crypto-org-chain/cronos/releases/tag/v0.7.0-hotfix-temp seems to be outdated

**Comment by yihuang** [comment]
It's a security patch, it'll be disclosed very soon.

**Comment by kaber2** [comment]
You need to rethink your security policy. It is inacceptable to distribute binaries without the corresponding source code available, for so many reasons, not the least of which is license compliance. This is a clear violation of the GPLv2.

**Comment by tomtau** [comment]
https://github.com/crypto-org-chain/cronos/releases/tag/v0.8.0
