### ISSUE TITLE
Problem:CRC20 standard is not settled down and documented

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#62]
# Early stage proposal

## native denom conversion

- `mint_by_cronos_module(address user, uint256 amount)`
- `burn_by_cronos_module(address user, uint256 amount)`
- `native_denom() returns (string)`

## bridge call

- `send_to_ibc(address recipient, uint256 amount)`
- `send_to_ethereum(address recipient, uint256 amount)`

## native call events

- `__CronosSendToAccount(address recipient, uint256 amount)`
- `__CronosSendToEthereum(address eth_recipient, uint256 amount, uint256 bridge_fee)`
- `__CronosSendToIBCChannel(address recipient, uint256 amount)`

**Comment by CeruleanAtMonaco** [comment]
I think this issue can be closed now, given we've been using https://github.com/crypto-org-chain/cronos/blob/main/contracts/src/ModuleCRC20.sol?

Or we will only close after we add some proper documentation?
Should the documentation be an ADR in https://github.com/crypto-org-chain/cronos/tree/main/docs/architecture? If not, where else is best to place it? @yihuang @tomtau @calvinaco @thomas-nguy thanks ahead!

**Comment by thomas-nguy** [comment]
maybe 
- Write ADR for the bridge solution ETH <-> Cronos which document the hook logic and ModuleCRC20 contract
- For CRC20 standard or other CRCXX standard, lets open a new repository

For now CRC20 and ModuleCRC20 are almost the same, so we could just create an ADR

**Comment by yihuang** [comment]
Consider it fixed by the new repo: https://github.com/crypto-org-chain/cronos-public-contracts.
