### ISSUE TITLE
Problem: sim workflow has syntax error

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#620]
https://github.com/crypto-org-chain/cronos/actions/runs/2802679618/workflow#L23

The sim workflow has syntax error.
And it shouldn't run when closing an issue, I guess it just misses a `)`.

**Comment by adu-crypto** [comment]
yes, `)` in line 24 is missing, it should be:
```yaml
(github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/runsim')) ||
      github.event_name == 'push' || github.event_name == 'pull_request'
```
