### ISSUE TITLE
v0.8.0 stops working after synchronizing

### ISSUE THREAD

**Issue by sonderangebot10** [crypto-org-chain/cronos#628]
Previously I was running `v0.7.0` with zero issues. Then I got an error that I should be using `v0.7.0-hotfix`, but it never worked for me so I just waited for a new proper release. Now I tried running client `v0.8.0` and initially with the latest snapshot `cronosmainnet_25-1-xxx-pruned` from https://quicksync.io/networks/cronos.html it starts syncing, however once it reaches the latest block it just stops. After the restart same thing happens - syncing until latest block and stops.

Here is the screenshot of the logs:
![image](https://user-images.githubusercontent.com/37372712/183625963-f1bfec6f-223e-4120-8464-e591e008bad8.png)

**Comment by yihuang** [comment]
Can you post the full log file?

**Comment by sonderangebot10** [comment]
Problem resolved - just needed to initialize the node with fresh configs.
