### ISSUE TITLE
Is it safe to upgrade v0.7 -> v0.8 now

### ISSUE THREAD

**Issue by huahuayu** [crypto-org-chain/cronos#630]
Hi since my v0.7 is stopped for several days, current release is v0.8 but I can see there are some issues raised for v0.8.
https://github.com/crypto-org-chain/cronos/issues/624
https://github.com/crypto-org-chain/cronos/issues/628

So is it safe to upgrade from v0.7 -> v0.8 now, any documentation?

**Comment by yihuang** [comment]
we have upgraded many nodes, it works fine. I need to understand more about the user's report to understand why.

**Comment by huahuayu** [comment]
Let's say 0.7 -> 0.8
Do I need to use a new genesis file (if there has a new one) or direct replace cronosd binary and restart?

**Comment by yihuang** [comment]
replace cronosd binary and restart, just like 0.6 -> 0.7.

**Comment by huahuayu** [comment]
done, let's see...hope everything is fine.

**Comment by huahuayu** [comment]
So far so good, syncing~~

**Comment by huahuayu** [comment]
Btw, do you have snapshots, if sync from scratch(let's say I want to set up a new node), I have to use 0.6.* to sync to some block and then switch to v0.8?

**Comment by yihuang** [comment]
https://quicksync.io/networks/cronos.html
there are plenty here.

**Comment by yihuang** [comment]
> I have to use 0.6.* to sync to some block and then switch to v0.8?

0.6 -> 0.7 -> 0.8

**Comment by huahuayu** [comment]
> > I have to use 0.6.* to sync to some block and then switch to v0.8?
> 
> 0.6 -> 0.7 -> 0.8

But If I use snapshot, then don't bother right?
