### ISSUE TITLE
 I need help setting up an archive node

### ISSUE THREAD

**Issue by hongwei520** [crypto-org-chain/cronos#631]
first question:

I downloaded cronosmainnet_25-1-rocksdb-archive in quick sync is there any difference between him and cronosmainnet_25-1-leveldb-archive

second question:
Where should the downloaded and decompressed directory be placed? Is it placed in the data at the same level as the configuration file directory or at the same level as cronosd, if it is the same as the configuration file directory, an error will be reported

third question:
I get an error when starting

![image](https://user-images.githubusercontent.com/39451921/183912294-0d544c99-2b42-4d35-a4ba-a9b023f3d1d6.png)

**Comment by yihuang** [comment]
> I get an error when starting

Are you trying to start from genesis with 0.8 binary? If from genesis you should use 0.6 first.

**Comment by hongwei520** [comment]
@yihuang Can version 0.8.0 directly load archive snapshots?

**Comment by hongwei520** [comment]
> if the snapshot is taken after v0.7.0-hotfix upgrade, then yes

What do I need to do? I did some operations, but an error was reported. That's the third question.

**Comment by yihuang** [comment]
From the screenshot, it's starting from block 0, snapshot is not used

**Comment by hongwei520** [comment]
> 从截图来看，它是从块 0 开始的，没有使用快照

I think so too, but I downloaded the snapshot. According to the documentation, it was unzipped in the configuration file directory, but the execution directly reported an error. Then I moved to the same directory as the binary file. It can be run, but it is the error of the third problem.

**Comment by hongwei520** [comment]
@yihuang 
This is my latest error
![image](https://user-images.githubusercontent.com/39451921/184270005-4c54302a-8679-44f3-b6e8-5da1540b1cf1.png)

**Comment by yihuang** [comment]
> @yihuang This is my latest error ![image](https://user-images.githubusercontent.com/39451921/184270005-4c54302a-8679-44f3-b6e8-5da1540b1cf1.png)

This looks alright, the websocket dropped an abnormal client, but chain is still syncing.

**Comment by hongwei520** [comment]
@yihuang 
There is still this error, is it just a small error and does not affect the overall operation?
![image](https://user-images.githubusercontent.com/39451921/184270708-eedcbf04-8f83-4189-a272-be3084e6f943.png)

**Comment by yihuang** [comment]
> @yihuang There is still this error, is it just a small error and does not affect the overall operation? 

yes, small error, peers come and go due to networking or operation issues.

**Comment by hongwei520** [comment]
@yihuang ok thanks for your help

**Comment by yihuang** [comment]
no problem
