### ISSUE TITLE
Problem: ibc relayer don't work well with default tx prioritization stretegy

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#634]
Implement the workarounds. https://github.com/informalsystems/ibc-rs/issues/2350

**Comment by yihuang** [comment]
Two solutions:
- Hard code a constant priority in custom `TxFeeChecker` for ibc txs (txs that contains only ibc messages).
- Customize relayer tx building logic to include extension option `ExtensionOptionDynamicFeeTx` and set the `max_priority_price` to a constant value, set the gas_price to maxint, so it'll end up with a constant priority value.

**Comment by tomtau** [comment]
not sure how many external relayer operators there are, but I assume they'll be running the vanilla relayer binaries without any patches and `TxFeeChecker` may work better?

**Comment by yihuang** [comment]
> not sure how many external relayer operators there are, but I assume they'll be running the vanilla relayer binaries without any patches and `TxFeeChecker` may work better?

yeah, I guess that's simpler in the short term.

**Comment by tomtau** [comment]
or if that second workaround is a normal option in one of the relayer official releases, it should be ok as well
