### ISSUE TITLE
Problem: strange failure in sim test with sdk 0.46

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#645]
After upgrade to sdk 0.46, it's strange that [this commit](https://github.com/crypto-org-chain/cronos/pull/578/commits/249444ed5a649fae59dd48e26eaee0ba83eca8e4) is necessary for the sim test to pass. Maybe there's some deeper issue in the SDK sim test itself.

**Comment by adu-crypto** [comment]
If we reset this commit(`git reset --hard HEAD~1`), and print some debugging information:
```txt
Simulating... block 22/50, operation 0/357. random unbonding entry index: 1
staking cancel bond amount: 2663067285, balance: 5485945019
index 0 entry: balance: "2397748260"
completion_time: "2103-10-03T03:17:50Z"
creation_height: 4
initial_balance: "2397748260"

index 1 entry: balance: "5485945019"
completion_time: "2103-10-03T03:17:50Z"
creation_height: 4
initial_balance: "5485945019"

actual unboding entry index: 0
skaing actual cancel amount: 2663067285, actual balance: 2397748260
```
we can find that we have tow `unBondingDelegationEntries` with the same create `CreationHeight`.
By comparing the index and the `balance`, we find that the intended `unBondingDelegationEntry` is no matched with the actual `unBondingDelegationEntry` that was executed by the staking msgServer.

**Comment by adu-crypto** [comment]
Referring to the [sdk v0.46 code](https://github.com/cosmos/cosmos-sdk/blob/release/v0.46.x/x/staking/keeper/msg_server.go#L434-L452) , we find how `msgServer. CancelUnbondingDelegation` find the matched `unBondingDelegationEntry` based on  `CreationHeight `:
```go
for i, entry := range ubd.Entries {
		if entry.CreationHeight == msg.CreationHeight {
			unbondEntry = entry
			unbondEntryIndex = int64(i)
			break
		}
	}
```

**Comment by adu-crypto** [comment]
definitely, this logic is not accurate and could match with unintended `unBondingDelegationEntry` if we have two entries with the same `CreationHeight`.
Besides, it is legal to have two entries with the same `CreationHeight` but different `balance` according to the (staking module specifications)[https://github.com/cosmos/cosmos-sdk/blob/release/v0.46.x/x/staking/spec/03_messages.md#msgundelegate].

**Comment by tomtau** [comment]
open an issue on SDK?

**Comment by adu-crypto** [comment]
> open an issue on SDK?

sure

**Comment by yihuang** [comment]
fixed in sdk.
