### ISSUE TITLE
Problem: mempool integration tests are not stable

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#649]
`test_mempool.py`, `test_basic.py::test_tx_inclusion`, `test_filters.py:: test_pending_transaction_filter` fails occasionally in CI, need to make then run more stabely.

**Comment by mmsqe** [comment]
mempool one is strange, I leave the test [ran](https://github.com/mmsqe/cronos/commit/3ebe554b3d45113313b36193e7b3ea3ab4c30f20) for night and fail to reproduce once

**Comment by yihuang** [comment]
> mempool one is strange, I leave the test [ran](https://github.com/mmsqe/cronos/commit/3ebe554b3d45113313b36193e7b3ea3ab4c30f20) for night and fail to reproduce once

without changing anything?

**Comment by mmsqe** [comment]
ok, but rest two are easier to reproduce, maybe fix 1st

**Comment by mmsqe** [comment]
from reproduced log, unstable comes from block number change when we send one by one, concurrent send txs will help a bit

**Comment by mmsqe** [comment]
there's a `websocket close 1006 (abnormal closure): unexpected EOF` error, pending filter cant get confirmed txs after ws reconnect, not sure we should adjust test since this it's more like ws retry issue
