### ISSUE TITLE
Problem: archive node takes a long time to startup

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#666]
Right now, archive node on mainnet takes a long time to startup, the main suspicion is iavl tree load all the roots on startup, that's time consuming on an archive node which has lots of historical versions.
iavl 0.19.0's optimization may help with that.

**Comment by tomtau** [comment]
related issue https://github.com/cosmos/cosmos-sdk/issues/4326

**Comment by JayT106** [comment]
I remembered @yihuang had tried `LazyLoadVersion` but there was no significant difference?

**Comment by yihuang** [comment]
> I remembered @yihuang had tried `LazyLoadVersion` but there was no significant difference?

lazy loading only support read only cases.

**Comment by yihuang** [comment]
`v0.8.x` and main branch all using iavl 0.9 now, closing this one.
