### ISSUE TITLE
TXs are not arranged correctly based on their gas prices in blocks

### ISSUE THREAD

**Issue by dandavid3000** [crypto-org-chain/cronos#734]
**Describe the bug**
Validator does not arrange transactions based on gas prices. This has been occurring many times from my observation

**To Reproduce**
Send a transaction with different gas prices to check

**Expected behavior**
TXs should be arranged correctly based on their gas prices

**Example**
In block [4996012](https://cronoscan.com/txs?block=4996012), many TXs with gas 10000 were arranged before TXs with gas 14000

**Comment by yihuang** [comment]
tx prioritization based on gas price only supported after v1.0(same as v0.9) which is still on testnet, currently mainnet is FIFO.

**Comment by yihuang** [comment]
Prioritization on mainnet now, closing
