### ISSUE TITLE
Problem: different result from `eth_getProof` comparing with Ethereum

### ISSUE THREAD

**Issue by macong-cdc** [crypto-org-chain/cronos#749]
**Describe the bug**
Result from `eth_getProof` RPC method is different from [Ethereum EIP-1186](https://eips.ethereum.org/EIPS/eip-1186)

**To Reproduce**
You may try
```shell
curl --location --request POST 'https://evm-t3.cronos.org' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "eth_getProof",
    "params": [
        "0x4CecAA8ad42Ba5c0D69C6F68a273901C6fd52B02",
        ["0x1"],
        "0x588200"
    ],
    "id": 0
}'
```

**Expected behavior**
`accountProof` and `proof` under `storageProof` in the json returned are not hex-strings.

**Comment by adu-crypto** [comment]
https://github.com/ethereum/go-ethereum/blob/5b1a04b9c749d804b51159fe12246c56de8515c1/internal/ethapi/api.go#L702

it seems geth simply encoding bytes as hex string with `0x` prefix

**Comment by yihuang** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/764
