### ISSUE TITLE
Problem: rocksdb compaction could cause write rate to drop to mimimum

### ISSUE THREAD

**Issue by adu-crypto** [crypto-org-chain/cronos#759]
**Is your feature request related to a problem? Please describe.**

rocksdb compaction could cause the write QPS to drop to minimum, which slows down the node performance.

**Describe the solution you'd like**

rocksdb 7.5.3 said that it fixed a bug related to `concurrent compactions might cause unnecessary further write stalling`, and this could possibly solve this problem.
maybe we could test and upgrade rocksdb to latest version to mitigate this.
https://github.com/facebook/rocksdb/releases/tag/v7.5.3

> Bug Fixes
>      * Fix a bug in which backup/checkpoint can include a WAL deleted by RocksDB.
>      * `Fix a bug where concurrent compactions might cause unnecessary further write stalling. In some cases, this might cause write rate to drop to minimum.`

**Comment by JayT106** [comment]
Does the concurrent compactions issue happen in v6.29.5?

I remembered the rocksDB V7 is API breaking.
It will require modifying `tm-db`

**Comment by adu-crypto** [comment]
> Does the concurrent compactions issue happen in v6.29.5?

it seems discussed in this [issue](https://github.com/facebook/rocksdb/pull/10270) and the solutions seem not backported.

**Comment by yihuang** [comment]
it seems not hard to make gorocksdb build with v7: https://github.com/cosmos/gorocksdb/pull/7

**Comment by yihuang** [comment]
closed by #813
