### ISSUE TITLE
eth_subscribe don't work on testnet nodes

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#778]
> I have trouble to subscribe logs events in Cronos testnet node, and would like to know the reason why testnet doesn’t a stream of logs.
> The mainnet node do it correctly, but in testnet node when I send message to ws connection:
> {"id": 25, "method": "eth_subscribe", "params": ["logs"]}
> I just received like below as an example:
> { "jsonrpc": "2.0", "result": "0xf6ffbe4f2f785845e2538c2a0a3b1c82", "id": 25 }
> But in mainnet I do recieve this responce and stream of logs:

![image](https://user-images.githubusercontent.com/236070/204937341-ec846eea-4055-4103-b6be-eca7c4085a5e.png)

**Comment by mmsqe** [comment]
just try subscribe for a contract tnx, seems normal based on current [main](https://github.com/crypto-org-chain/cronos/commit/7dc3c4ced510b94e9287b51b4784caee12dfea74)
<img width="978" alt="Screenshot 2022-12-01 at 8 40 07 AM" src="https://user-images.githubusercontent.com/2867936/204938228-e970fc6a-a86b-4e18-a169-26c62f7f08cd.png">
