### ISSUE TITLE
Problem: no command to delete orphan records

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#787]
Move this tool to cronosd cmd: https://gist.github.com/yihuang/7031416e592f0a2f85201a775269f6a3

**Comment by calvinaco** [comment]
Does it make sense to make this a regular job when run with `cronosd start`? This way node operators won't need to run this command on a regular basis.

**Comment by yihuang** [comment]
> Does it make sense to make this a regular job when run with `cronosd start`? This way node operators won't need to run this command on a regular basis.

it's alright, we'll have new tricks soon ;D

**Comment by yihuang** [comment]
I'll close this since we have versiondb merged, much better solution for reducing db size
