### ISSUE TITLE
Problem: no command to patch gasUsed in pior-v0.7 blocks

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#792]
Before `v0.7.0` upgrade, due to [this bug](https://github.com/evmos/ethermint/pull/751), the reverted tx get charged full gas limit, so the reported `gasUsed` don't match the deducted fee, it confuse some clients, better to patch the tx results to change the gasUsed to gasLimit.

Alternatively:
- we can patch the rpc endpoints logic somehow.
- client just track the fee_collector flows for actual fee deducted.

**Comment by mmsqe** [comment]
option 1 is only patch in rpc api instead of tm db right?

**Comment by yihuang** [comment]
> option 1 is only patch in rpc api instead of tm db right?

yes
