### ISSUE TITLE
Problem: cronosd starts then quit every few seconds

### ISSUE THREAD

**Issue by chenyanming** [crypto-org-chain/cronos#84]
**Describe the bug**
I built `cronosd` in macOS Big Sur, but failed to run. It starts then quits every few seconds.

**To Reproduce**
`make build` # build cronosd
`./scripts/start-cronos scripts/devnet.yaml /tmp/cronos` # It failed, starts then exit every few seconds

**Expected behavior**
Run stably.

**Screenshots**
![image](https://user-images.githubusercontent.com/3462132/133955088-75a32144-e0a3-4232-87b0-d06f2fec5fdd.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Version: Big Sur 11.2.3

**Additional context**

**Comment by chenyanming** [comment]
Using `init.sh` script from https://github.com/leejw51crypto/cronos/tree/dev/my/apple

Seems it works.

Before run `init.sh`, need to `export MYMNEMONICS="visit craft resemble online window solution west chuckle music diesel vital settle comic tribe project blame bulb armed flower region sausage mercy arrive release"` first. A *VALID* MYMNEMONICS is necessary.

![image](https://user-images.githubusercontent.com/3462132/133968409-b80e1dc0-f060-4344-b0d2-2c146ea66fc2.png)

**Comment by damoncro** [comment]
This issue is no longer applicable in latest version.
