### ISSUE TITLE
Problem: not using latest rocksdb for windows build

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-org-chain/cronos#863]
change rocksdb to v7.9.2 on windows
use msys2 mingw64

**Comment by leejw51crypto** [comment]
working now

**Comment by leejw51crypto** [comment]
this pr  
https://github.com/facebook/rocksdb/pull/11217/files

will fix this issue

**Comment by leejw51crypto** [comment]
on windows, `extern ROCKSDB_LIBRARY_API` is necessary to expose function to final dll

**Comment by yihuang** [comment]
closed by: #868
I fix windows build issue by patch grocksdb to remove those apis, easier to do than patch rocksdb.
