### ISSUE TITLE
Problem: Cosmos SDK v0.47 is not used

### ISSUE THREAD

**Issue by JayT106** [crypto-org-chain/cronos#875]
Cosmos SDK v0.47 introduced new ABCI methods and other changes. Cronos needs to adopt the new SDK version for solving some block propose issues regarding the transaction gas/fee.

It might require some module migration including `ethermint`, `ibc-go`. Will update more details in this ticket.

- [ ] Update Ethermint dep with Cosmos SDK v0.47 https://github.com/evmos/ethermint/issues/1667
- [ ] Should the gravity bridge module updates the dep? Currently is using tendermint v0.34.x

**Comment by JayT106** [comment]
submit PR https://github.com/evmos/ethermint/pull/1687 , remains to update the `Makefile` and `proto-gen-tool` script with the correct proto-gen-tool path.

**Comment by mmsqe** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/1272
