### ISSUE TITLE
WebSocket on Mainnet not listening to Events emitted

### ISSUE THREAD

**Issue by jingxuan98** [crypto-org-chain/cronos#886]
**Describe the bug**

Baiscally I'm not able to listen and subscribe to mainnet Events Logs, but it works fine on testnet

It was working like 1 week ago when i started my node but now its not working

**To Reproduce**
1. The script i use to test can be found at https://github.com/jingxuan98/cronos-mainnet-eventIssue
2. Clone the repo and `go get` the packages and run `go run main.go`
3. Deploy a ERC20 Token at Testnet and Mainnet and Test accordingly (RMB to change the token addresses adn WSS address)

**Expected behavior**
1. Able to Listen to the Events on Testnet when a "transfer()" function is invoke follow by an "Transfer" event emitted, but not on Mainnet

**Screenshots**
Listening on Testnet
<img width="959" alt="Screenshot 2023-02-20 at 12 23 19 AM" src="https://user-images.githubusercontent.com/43902263/219960865-9e3bbb61-6501-4e10-92d7-dcd8847bfff6.png">

But for Mainnet its not listening
<img width="960" alt="Screenshot 2023-02-20 at 12 23 51 AM" src="https://user-images.githubusercontent.com/43902263/219960895-88c2ac75-99a6-4d1b-9406-660de16cc1ea.png">

Macbook Pro M2 
Golang 1.19

**Comment by JayT106** [comment]
Hi @jingxuan98 , it might relate to this tendermint issue https://github.com/tendermint/tendermint/issues/6729, we will check our mainnet node settings to ensure the value is setup properly.

**Comment by jingxuan98** [comment]
Ok thanks for the reply @JayT106 , btw just some add-ons that we face this issue with emitting even just a few events instead of 100 like the OP of https://github.com/tendermint/tendermint/issues/6729. Hope the issue can be solved soon, thanks!

**Comment by mmsqe** [comment]
@jingxuan98 I find it hard to reproduce the issue, I tried one case might no response at all is pass outer contract address instead of [inner](https://github.com/crypto-org-chain/cronos/pull/901/files#diff-ae83dd6ce556ee432c621817c6c151bff9ab7c6628d6f95b6e3606780d23e27cR144) address, may I ask the contract address you subscribe with?

**Comment by jingxuan98** [comment]
@mmsqe basically in the test above I just deploy a simple ERC20 on mainnet using remix and listen to the transfer event and transfer the tokens among accounts to test that, the token contract address i use is 0x926f2e39eab3c828215d7bd807659af5672a11a6

**Comment by mmsqe** [comment]
> @mmsqe basically in the test above I just deploy a simple ERC20 on mainnet using remix and listen to the transfer event and transfer the tokens among accounts to test that, the token contract address i use is 0x926f2e39eab3c828215d7bd807659af5672a11a6

Subscription might get cancell for slower client like ci fail when set smaller [iterations](https://github.com/crypto-org-chain/cronos/pull/901/commits/14b6b051655b9c05b0de66b935446e399fbed4a5#diff-ae83dd6ce556ee432c621817c6c151bff9ab7c6628d6f95b6e3606780d23e27cR131), while current long-poll enhancement process [more](https://github.com/evmos/ethermint/pull/1694/files#diff-82f58fd15f6378cdbcb760a552229357908a6f1b6dfca55c217f139ae8bfc483R121) and much faster.

**Comment by jingxuan98** [comment]
I'm still facing this issue, any workarounds?

**Comment by mmsqe** [comment]
fixed by https://github.com/crypto-org-chain/cronos/pull/1239
