### ISSUE TITLE
json-rpc ws protocol : invalid type for connection ID: string

### ISSUE THREAD

**Issue by sundafa** [crypto-org-chain/cronos#891]
**Describe the bug**
ws connects to nodes and sends requests
When the id is set to an integer of type int, it returns normally, but when the id is a string, it returns normally when accessing eth and other geth series software rpc.

error request:
```
{
    "jsonrpc": "2.0",
    "method": "web3_clientVersion",
    "params": [],
    "id": "0"
}
```
result:
`{"jsonrpc":"2.0","error":{"code":-32600,"message":"invalid type for connection ID: string"},"id":null}
`

**Expected behavior**
Receive id string type and return normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ubutnu 20.04

**Comment by yihuang** [comment]
fixed in recent version.
