### ISSUE TITLE
Cronos RPC node issues

### ISSUE THREAD

**Issue by HarishankarVj12** [crypto-org-chain/cronos#973]
I am not able to start the Cronos node with version v0.8.3

Error Message:

1:45PM INF Unlocking keyring
1:45PM INF starting ABCI with Tendermint
1:45PM ERR failed to open DB error="failed to initialize database: resource temporarily unavailable"
Error: failed to initialize database: resource temporarily unavailable
Usage:

**Comment by yihuang** [comment]
the latest chain is using `v1.0.x` though.

**Comment by HarishankarVj12** [comment]
https://user-images.githubusercontent.com/116081867/232423903-99d57241-c3c2-4f43-99dd-f44fb580e97a.png
We are facing issues on ERR failing to open DB error="failed to initialize database: resource temporarily unavailable" could you please help me to solve this issues then we update new version of v1.0.1

**Comment by yihuang** [comment]
you probably has another node open the db exclusively?

**Comment by anshugarg401** [comment]
#1427

**Comment by yihuang** [comment]
see: https://github.com/crypto-org-chain/cronos/issues/973#issuecomment-1566437493

closing now.
