### ISSUE TITLE
Problem: memiavl cache store is not optimal

### ISSUE THREAD

**Issue by yihuang** [crypto-org-chain/cronos#982]
There were some ideas proposed to cosmos-sdk cache store, since we implemented custom store wrappers with memiavl, it'll be good to implement a better cache store with it.

**Comment by catShaark** [comment]
is this the idea on how to improve the cache store: https://github.com/cosmos/cosmos-sdk/issues/14377

**Comment by yihuang** [comment]
> is this the idea on how to improve the cache store: [cosmos/cosmos-sdk#14377](https://github.com/cosmos/cosmos-sdk/issues/14377)

yes

**Comment by yihuang** [comment]
it's merged in [forked repo](https://github.com/crypto-org-chain/cosmos-sdk/tree/release/v0.50.x/store)
